### ISSUE TITLE
error delay loading library "metahook/fmodex.dll"

### ISSUE THREAD

**Issue by hcrcbw** [hzqst/MetaHookSv#1]
将build文件夹里的文件复制到游戏根目录后创建带有-game svencoop的metahook的快捷方式，运行之后跳出error delay loading library "metahook/fmodex.dll"的窗口，点击确定后游戏退出。
曾试过在游戏根目录创建名为metahook的文件夹，然后把svencoop文件夹里的fmodex.dll文件复制进去，之后再运行快捷方式不会跳出这个窗口，并且可以创建本地游戏，但是会出现无法搜索到服务器、游戏文件读取不完全（例如玩家模型数量减少，本地插件未启用），玩家视角转动受限制的问题，hdr、对话字幕等功能也没有，也无法用新增的指令进行调试。
![问题](https://user-images.githubusercontent.com/78557545/106934729-705dab00-6755-11eb-9cf5-f0219fbfba0b.png)

**Comment by hzqst** [comment]
目前需要自行添加-game svencoop，下版本会默认添加该参数

**Comment by hzqst** [comment]
最新版本已经会自动添加-game svencoop

**Comment by hcrcbw** [comment]
已解决，谢谢大佬
