### ISSUE TITLE
水底闪烁

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#101]
好久不见，我已经很久没有关注更新了 不知你是否还记得我

我测试了最新版本 发现当我在水底时 最放的水会有闪烁的情况 希望修复

**Comment by q52888940** [comment]
> 好久不见，我已经很久没有关注更新了 不知你是否还记得我
> 
> 我测试了最新版本 发现当我在水底时 最放的水会有闪烁的情况 希望修复
最下方的水

**Comment by hzqst** [comment]
有没有能复现这个问题的地图？

**Comment by q52888940** [comment]
是在CS1.6测试，地图为官方地图 "AS_OILRIG"

**Comment by hzqst** [comment]
![Uploading 20220112121936_1.jpg…]()
无法复现
