### ISSUE TITLE
二次元渲染和地图影子角度设置无效果

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#102]
测试游戏 "CS零点行动"
{
"origin" "-2176 -1088 7"
"_distance" "300.0"
"_light" "172 232 251 110"
"classname" "light_environment"
"_specular" "1.0"
"_specularpow" "10"
"pitch" "-40"
}
地图数据
测试地图"DE_CBBLE_CZ"

**Comment by hzqst** [comment]
自定义阴影角度请参考https://github.com/hzqst/MetaHookSv/blob/main/Renderer.md#env_shadow_control

celshade相关请参考https://github.com/hzqst/MetaHookSv/blob/main/Renderer.md#outline-celshade-and-rimlight和https://github.com/hzqst/MetaHookSv/blob/main/Build/svencoop_addon/models/player/GI_Keqing/GI_Keqing_external.txt

**Comment by q52888940** [comment]
所以自定义阴影我需要在地图里添加env_shadow_control实体吗？那么entity记事本是做什么的

**Comment by hzqst** [comment]
> 所以自定义阴影我需要在地图里添加env_shadow_control实体吗？那么entity记事本是做什么的

关于自定义实体有三种添加方法，两种是利用txt，一种是添加到bsp文件本身：https://github.com/hzqst/MetaHookSv/blob/main/Renderer.md#new-entities

**Comment by q52888940** [comment]
![YUEB@XKH9NY) E)JN`}@UTN](https://user-images.githubusercontent.com/68973128/149331660-3a1c9565-b0a8-48d9-9798-94be9fbc2179.png)
这是我在地图里增加了env_shadow_control实体，影子出现在墙上而不是地下，无论我怎么调整pitch他都是在墙上出现而不是在地图斜偏着的效果 我该怎么做

**Comment by hzqst** [comment]
> ![YUEB@XKH9NY) E)JN`}@UTN](https://user-images.githubusercontent.com/68973128/149331660-3a1c9565-b0a8-48d9-9798-94be9fbc2179.png) 这是我在地图里增加了env_shadow_control实体，影子出现在墙上而不是地下，无论我怎么调整pitch他都是在墙上出现而不是在地图斜偏着的效果 我该怎么做

调整angles为90 0 0

**Comment by q52888940** [comment]
pitch是做什么的 我没有理解 我更换数值没有看出具体效果
