### ISSUE TITLE
几个错误与问题

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#103]
![MYS GMCL72(DWGCW@2`HA58](https://user-images.githubusercontent.com/68973128/149378693-89ab61a9-7d2d-4055-9f76-a4ec636dcbca.png)
1.选项挡住了原有的地方
2.在CS中刚进入游戏发第一个无线电 游戏会卡顿一下并且不会显示左下角字幕，直到第二个无线电发出或者聊天发出
3.为什么抗锯齿时开启的FXAA，不能开启MSAA吗？
4.他使我的FOV插件失效了 我不清楚渲染插件和FOV插件有什么关联。。。为什么会失效
5.我怎么设置队伍的颜色，比如在原来的CS中,CT打字时是蓝色,T是红色，现在全变成了白色、
6.他使我CS的gunsmoke命令失效了，我的枪口现在不在冒烟了
7.这个开枪时的粒子效果可否关闭，他让我觉得很奇怪，我更想使用CS的原版。。
8.能否给我二次元渲染和地图天空遮蔽方面的说明,我关闭或开启没有发现区别

**Comment by hzqst** [comment]
1.将来会修正位置
2.请提供字幕文件
3.因为MSAA跟延迟渲染模式不兼容
4.渲染器自带r_vertical_fov 0/1, r_adjust_fov 0/1两个参数覆盖了原版的FOV设定
5.以后会修复，或者也可以临时禁用chat dialog：cap_newchat 0
6.如何复现？
7.什么粒子效果？
8.CelShade需要模型的贴图本身设定为flatshade模式，使用[HLAM](https://github.com/SamVanheer/HL_Tools/wiki/Half-Life-Asset-Manager)可以修改贴图渲染模式。天空遮挡属于bugfix，不是特效。

**Comment by q52888940** [comment]
![de_dust0004](https://user-images.githubusercontent.com/68973128/149805058-e982184a-c633-436a-b2d2-3c8690948a5f.jpg)
bu
补图7
击中地面的粒子效果在CS中非常奇怪，并且原来的被屏蔽了

**Comment by hzqst** [comment]
1e9011895232a74972680cdc3948de7080d6ed6e修正了问题1、2、5

**Comment by hzqst** [comment]
问题7 已在9079660d390bdf334289cbd7890ca8f3a04a15d5中修复

**Comment by hzqst** [comment]
> 无需提供字幕文件，请在CS零点行动中进入游戏第一件事随便点击一个无线电，左下角消息不会第一时间出现并且会卡顿一下，直到第二个消息出去(是左下角聊天信息而不是字幕BUG")
> 
> r_vertical_fov 0/1, r_adjust_fov 0/1 区别是什么 关于BUG6,请在原版CS中控制台输入gunsmoke可以看出枪口会有枪烟出现 7 ![de_dust0002](https://user-images.githubusercontent.com/68973128/149804846-27db8da7-85e2-4195-a955-f85327fb84bc.jpg) 8 flatshade模式是fullbright贴图吗

r_vertical_fov 1是Sven Co-op版本的宽屏FOV模式，r_adjust_fov 1是Xash3D版本的宽屏FOV模式，如果分辨率不是4:3则无效果

flatshade贴图渲染模式：
![aa](https://user-images.githubusercontent.com/12287588/150640143-71ac03d1-fde7-4ac2-9a67-50e2a2ca8c09.png)
