### ISSUE TITLE
SPR颜色被削弱

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#104]
在CS中测试

**Comment by hzqst** [comment]
图呢？

**Comment by q52888940** [comment]
![de_dust0000](https://user-images.githubusercontent.com/68973128/149803692-ee748fdf-d769-4594-9bac-405a423eb528.jpg)
![de_dust0002](https://user-images.githubusercontent.com/68973128/149803696-1478e828-2367-40d2-8c86-2da50fd9d38c.jpg)

**Comment by q52888940** [comment]
你会修复它吗 包括打地面的粒子效果
