### ISSUE TITLE
布娃娃问题

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#107]
![Uploading 0I[3[O`O~8YW%T25A@HY)XI.png…]()
我在CS中使用布娃娃插件成功，尝试给模型pLAYER/GIGN写布娃娃，但在游戏里没有效果
以下是我的配置文件
[DeathAnim]
101 80
102 120
103 120
104 80
105 120
106 150
107 30
108 150
109 150
110 150

[RigidBody]
Pelvis  1   24   capsule   -4.0  7.0  0.1   6
L Thigh 24   26   capsule   -4.0  7.0  0.1   6
L Calf   25  29   capsule   -4.0  7.0  0.1   6
L Foot 26   31  capsule   -4.0  7.0  0.1   6
R Thigh 29   1   capsule   -4.0  7.0  0.1   6
R Calf 30  3  capsule   -4.0  7.0  0.1   6
R Foot 31   4  capsule   -4.0  7.0  0.1   6
Spine1 3   5  capsule   -4.0  7.0  0.1   6
Spine2 4   7   capsule   -4.0  7.0  0.1   6
Spine3 5   6   capsule   -4.0  7.0  0.1   6
Neck 6   9   capsule   -4.0  7.0  0.1   6
Head 7   10   capsule   -4.0  7.0  0.1   6
L Clavicle 8   11   capsule   -4.0  7.0  0.1   6
L UpperArm 9  17   capsule   -4.0  7.0  0.1   6
L Forearm 10   8   capsule   -4.0  7.0  0.1   6
L Hand 11   4   capsule   -4.0  7.0  0.1   6
R Clavicle 16   1  capsule   -4.0  7.0  0.1   6
R UpperArm 17   5   capsule   -4.0  7.0  0.1   6
R Forearm 18   3   capsule   -4.0  7.0  0.1   6
R Hand 19   7   capsule   -4.0  7.0  0.1   6
L Hand 8    16   capsule   -4.0  7.0  0.1   6

[Constraint]
Spine  Head   conetwist 6 15   0 0 0     0  6  0        0.01  0.01  0.2
Pelvis Spine  conetwist 1 5    0 0 4     0 -4  0        0.0  0.0  0.1

Spine  LArm   conetwist 7 8    0 0 0     0 -4  0        0.33 0.33 1.0
LArm   LArm2  conetwist 8 9    0 0 0     0 -4  0        0.2  0.2  0.2
LArm2  LHand  conetwist 9 10   0 0 0     0  3  0        0.2  0.2  0.3

Spine  RArm   conetwist 11 12  0 0 0     0 -4  0        0.33 0.33 1.0
RArm   RArm2  conetwist 12 13  0 0 0     0 -4  0        0.2  0.2  0.2
RArm2  RHand  conetwist 13 14  0 0 0     0  3  0        0.2  0.2  0.3

Pelvis LLeg   conetwist 41 41  0 0 0     0 -7  0        0.1  0.1  0.25
LLeg2  LLeg   hinge     41 41  0 0 0     0 8 0         -0.6  0.0  0

Pelvis RLeg   conetwist 46 46  0 0 0     0 -7  0        0.1  0.1  0.25
RLeg2  RLeg   hinge     46 46  0 0 0     0 8 0         -0.6  0.0  0

[Barnacle]
LLeg2   dof6          0  8  0     40000   4   16
LLeg2   chewlimit     0  0  0     0       1.0  4
RLeg    dof6          0  0  0     30000  -16  16
RLeg    chewlimit     0  0  0     0       1.0  4
Pelvis  chewforce     0  0  0     8000    1.0  0

[Gargantua]
Head    GargMouth   dof6z        0  0  0     20000  -8  16
Spine   GargMouth   dof6z        0  0  0     20000  -16  32
Pelvis  GargMouth   dof6z        0  0  0     20000  -24  64

**Comment by q52888940** [comment]
![0I 3 O`O~8YW%T25A@HY)XI](https://user-images.githubusercontent.com/68973128/150289402-2c68f6b1-6cab-498d-ad5c-8675a77dbde4.png)

**Comment by q52888940** [comment]
![3LPA$JMG`6~_QPQVSC@C`@5](https://user-images.githubusercontent.com/68973128/150289563-6a924f5b-9b07-4c04-8ced-7b66e9248414.png)

**Comment by hzqst** [comment]
txt跟模型放一起了吗？

**Comment by q52888940** [comment]
放一起了，我想问他是不是不支持CS的人物模型

**Comment by q52888940** [comment]
我尝试给CS的人质加入布娃娃是成功的，但是人物一直没有成功

**Comment by hzqst** [comment]
> 我尝试给CS的人质加入布娃娃是成功的，但是人物一直没有成功

可能是绘制玩家模型用的CGameStudioRenderer::StudioDrawPlayer函数没有hook成功

**Comment by q52888940** [comment]
你会考虑修复这个吗

**Comment by hzqst** [comment]
9e50acede913dad327e8ded7ba18fce5a480cd0b 中已解决该问题
