### ISSUE TITLE
创建假人闪退

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#108]
你好，我在cs中使用AMXX插件创建了一个假的模型，但是使用HDR插件后发生了闪退，我想知道是什么原理

**Comment by q52888940** [comment]
#include <amxmodx>
#include <fakemeta>
#include <engine>
#include <hamsandwich>

#define PLUGINNAME		"ClivelMa"
#define VERSION			"ClivelMa"
#define AUTHOR			"ClivelMa"

#define CLASS 	"ent_camara"

#define CAMERA_MODEL 	"models/null.mdl"
#define CAMERA_MINS Float: { -10.0, -10.0, 0.0 }
#define CAMERA_MAXS Float: { 10.0, 10.0, 25.0 }
#if AMXX_VERSION_NUM < 183
#define OBS_NONE                        0
#endif

/*
死后像CSGO那样追踪目标
*/

new killer[33]
new las_obs[33]
new play[33]

new Float:g_freeze_origin[33][33][3]
new g_freeze_sequence[33][33]
new g_freeze_frame[33][33]
new g_freeze_framerate[33][33]
new Float:g_freeze_angles[33][33][3]
new g_freeze_gaitsequence[33][33]
new g_freeze_weaponmodel[33][33]

new bool:g_bfreeze[33]

public plugin_init()
{
	register_plugin(PLUGINNAME, VERSION, AUTHOR);
	register_clcmd("cl_disablefreezecam", "pfn_cam")
	register_think(CLASS, "pfn_camera_think")
	RegisterHam(Ham_Killed,"player","pfn_death")
	register_forward(FM_AddToFullPack, "AddToFullPack", 1)
	register_event("TextMsg", "pfn_unfreeze", "b", "2&#Spec_Mode")
	RegisterHam(Ham_Spawn, "player", "OnSpawnPlayer", 1)
	register_touch("player", CLASS, "OnTouchCamera")
}
public plugin_precache()
{
	precache_model(CAMERA_MODEL)
	precache_sound("ui/freeze_cam.wav")
}
pfn_SpawnCamera(id, target)
{
	freeze_map(id)
	new ent = create_entity("info_target")
	if(!is_valid_ent(ent))
	{
		client_print(id, print_chat, "实体生成失败")
		return
	}
	new Float:origin[3], Float:angles[3], Float:o2[3]
	entity_get_vector(target, EV_VEC_origin, o2)
	o2[2] += 25.0
	entity_get_vector(id, EV_VEC_origin, origin)
	//entity_get_vector(id, EV_VEC_v_angle, angles)
	//angles[0] = angles[0] * -1.0
	entity_set_model(ent, CAMERA_MODEL)
	entity_set_int(ent, EV_INT_movetype, MOVETYPE_NOCLIP)
	entity_set_string(ent, EV_SZ_classname, CLASS)
	entity_set_int(ent, EV_INT_solid, SOLID_TRIGGER)
	entity_set_vector(ent, EV_VEC_origin, origin)
	entity_set_vector(ent, EV_VEC_angles, angles)
	entity_set_edict(ent, EV_ENT_owner, id)
	
	client_cmd(id, "spk ui/freeze_cam.wav")
	
	//set aim
	entity_set_aim(ent, o2)
	// set speed
	set_speed(ent, calculate_speed(id, target), o2)
	//
	attach_view(id, ent);
	entity_set_float(ent, EV_FL_nextthink, halflife_time() + 0.001)
	set_task(5.0, "pfn_remove_ent", id)
}
public pfn_remove_ent(id)
{
	remove_task(id)
	new ent = find_ent_by_owner(-1, CLASS, id)
	if(is_valid_ent(ent))
	{
		remove_entity(ent)
	}
}
public pfn_camera_think(e)
{
	if(!is_valid_ent(e))
	{
		return;
	}

	if(get_entity_distance(e, killer[entity_get_edict(e, EV_ENT_owner)]) < 100)
	{
		entity_set_vector(e, EV_VEC_velocity, Float:{0.0,0.0,0.0})
	}
	entity_set_float(e, EV_FL_nextthink, halflife_time() + 0.001)
}
public pfn_test(id)
{
	new players[32], count
	get_players(players, count, "ae", "TERRORIST")
	new t = players[random(count)];
	ExecuteHam(Ham_TakeDamage, id, t, t, 101.0, DMG_BULLET);
}
public pfn_cam(id)
{
	play[id] = !play[id]
	//client_print(id, print_chat, "Acercamiento al morir %sactivado", play[id] ? "":"des")
}
public pfn_death(v,k)
{
	if(!is_user_connected(k) || v == k)
	{
		return
	}
	
	if(!play[v]) return	
	killer[v] = k
	set_task(0.5, "dead_post", v)	
}
public dead_post(id)
{
	set_pev(id, pev_iuser1, OBS_NONE)
	las_obs[id] = pev(id, pev_iuser1);
	pfn_SpawnCamera(id, killer[id])
}

public AddToFullPack(es, e, ent, host, hostflags, player, pSet)
{
	if(!player)
	{
		return
	}
	if(g_bfreeze[host])
	{
		set_es(es, ES_Angles, g_freeze_angles[host][ent])
		set_es(es, ES_Origin, g_freeze_origin[host][ent])
		set_es(es, ES_Sequence, g_freeze_sequence[host][ent])
		set_es(es, ES_Frame, g_freeze_framerate[host][ent])
		set_es(es, ES_FrameRate, g_freeze_framerate[host][ent])
		set_es(es, ES_GaitSequence, g_freeze_gaitsequence[host][ent])
		set_es(es, ES_WeaponModel, g_freeze_weaponmodel[host][ent])
	}
}

freeze_map(id)
{
	static szWM[60]
	for(new i = 1; i <= get_maxplayers() ; i++)
	{
		if(!is_user_connected(i))
		{
			continue;
		}
		entity_get_vector(i, EV_VEC_origin, g_freeze_origin[id][i])
		g_freeze_sequence[id][i] = entity_get_int(i, EV_INT_sequence)
		g_freeze_frame[id][i] = entity_get_int(id, EV_FL_frame)
		g_freeze_framerate[id][i] = entity_get_int(id, EV_FL_framerate)
		entity_get_vector(i, EV_VEC_angles, g_freeze_angles[id][i])
		g_freeze_gaitsequence[id][i] = entity_get_int(i, EV_INT_gaitsequence)
		entity_get_string(i, EV_SZ_weaponmodel, szWM, charsmax(szWM))
		g_freeze_weaponmodel[id][i] = engfunc(EngFunc_ModelIndex, szWM);
	}
	g_bfreeze[id] = true
}
public pfn_unfreeze(id)
{
	g_bfreeze[id] = false
	attach_view(id, id)
}
public client_putinserver(id)
{
	g_bfreeze[id] = false
	play[id] = true
}
public OnSpawnPlayer(id)
{
	if(!is_user_alive(id))
	{
		return
	}
	pfn_unfreeze(id)
}
stock Float:calculate_speed(u1, u2)
{
	return (float(get_entity_distance(u1, u2)) / 0.3)

}
public OnTouchCamera(ted, ter)
{
	new id = pev(ter, pev_owner)
	if(ted == killer[id])
	{
		entity_set_vector(ter, EV_VEC_velocity, Float:{0.0,0.0,0.0})
	}
}


// CHR ENGINE
stock entity_set_aim(ent,const Float:origin2[3],bone=0)
{
	if(!pev_valid(ent))
		return 0;

	static Float:origin[3]
	origin[0] = origin2[0]
	origin[1] = origin2[1]
	origin[2] = origin2[2]

	static Float:ent_origin[3], Float:angles[3]

	if(bone)
		engfunc(EngFunc_GetBonePosition,ent,bone,ent_origin,angles)
	else
		pev(ent,pev_origin,ent_origin)

	origin[0] -= ent_origin[0]
	origin[1] -= ent_origin[1]
	origin[2] -= ent_origin[2]

	static Float:v_length
	v_length = vector_length(origin)

	static Float:aim_vector[3]
	aim_vector[0] = origin[0] / v_length
	aim_vector[1] = origin[1] / v_length
	aim_vector[2] = origin[2] / v_length

	static Float:new_angles[3]
	vector_to_angle(aim_vector,new_angles)

	new_angles[0] *= -1

	if(new_angles[1]>180.0) new_angles[1] -= 360
	if(new_angles[1]<-180.0) new_angles[1] += 360
	if(new_angles[1]==180.0 || new_angles[1]==-180.0) new_angles[1]=-179.999999

	set_pev(ent,pev_angles,new_angles)
	set_pev(ent,pev_fixangle,1)

	return 1;
}
set_speed(ent, Float:speed, Float:origin[3])
{
	static Float:origin1[3]
	pev(ent,pev_origin,origin1)

	static Float:new_velo[3]

	new_velo[0] = origin[0] - origin1[0]
	new_velo[1] = origin[1] - origin1[1]
	new_velo[2] = origin[2] - origin1[2]

	new Float:y
	y = new_velo[0]*new_velo[0] + new_velo[1]*new_velo[1] + new_velo[2]*new_velo[2]

	new Float:x
	if(y) x = floatsqroot(speed*speed / y)

	new_velo[0] *= x
	new_velo[1] *= x
	new_velo[2] *= x

	if(speed<0.0)
	{
		new_velo[0] *= -1
		new_velo[1] *= -1
		new_velo[2] *= -1
	}

	set_pev(ent,pev_velocity,new_velo)
}

**Comment by q52888940** [comment]
以上是我的代码

**Comment by hzqst** [comment]
建议下个Visual Studio自己以Debug模式编译，直接F5调试游戏

**Comment by q52888940** [comment]
最低需要VS什么版本

**Comment by hzqst** [comment]
> 最低需要VS什么版本

https://github.com/hzqst/MetaHookSv#build-requirements

**Comment by q52888940** [comment]
感谢

**Comment by q52888940** [comment]
我在此提供另一个问题，在CS中无法开启屏幕空间反射，另外我有办法开启MSAA吗

**Comment by hzqst** [comment]
> 我在此提供另一个问题，在CS中无法开启屏幕空间反射，另外我有办法开启MSAA吗

屏幕空间反射需要在_detail.txt中指定SPECULAR贴图：
https://github.com/hzqst/MetaHookSv/blob/main/Renderer.md#screen-space-reflection

例子参考：https://github.com/hzqst/MetaHookSv/blob/main/Build/svencoop_addon/maps/restriction03_detail.txt

**Comment by q52888940** [comment]
你最近有更新的打算吗，在CS中他有一些小问题

**Comment by hzqst** [comment]
> 

什么问题？

**Comment by q52888940** [comment]
SPR透明度变低了，手雷爆炸尤为明显，字幕插件聊天框在第一个消息出现时不会显示并且会卡顿一下,
另外我不知道
![DEPSUN_GAZ`QWK($XWJ0NHJ](https://user-images.githubusercontent.com/68973128/150633434-0eccaf33-0225-4a03-b68c-fd52970a3e17.png)
这是有意改成这样的还是BUG，他让CS原版攻击地面的粒子效果消失了，取而代之是这个

**Comment by q52888940** [comment]
这导致CS比如下雪效果，看不到了 或者说非常透明

**Comment by hzqst** [comment]
> SPR透明度变低了，手雷爆炸尤为明显，字幕插件聊天框在第一个消息出现时不会显示并且会卡顿一下, 另外我不知道 ![DEPSUN_GAZ`QWK($XWJ0NHJ](https://user-images.githubusercontent.com/68973128/150633434-0eccaf33-0225-4a03-b68c-fd52970a3e17.png) 这是有意改成这样的还是BUG，他让CS原版攻击地面的粒子效果消失了，取而代之是这个

这些都修复了，见 9079660d390bdf334289cbd7890ca8f3a04a15d5、b829368aaedeaf2faf5f93c20b335532e5fbccd1
