### ISSUE TITLE
BUG未修复

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#109]
1.视频设置依然没在正确的位置上
2.聊天依然会卡顿并且不会播放
3.聊天字体颜色依然不是原版字体(CS无线电是绿色黄色等)
4.
![1_UEMY8_(`%1EPV4C2QIY1K](https://user-images.githubusercontent.com/68973128/150641572-eb9016d0-c799-45db-b4c9-add4095cee9a.png)
你好像确实修复了打击地面的粒子效果，但是他不是原版CS的而是,SVEN-COOP，但我觉得他更好,希望你保留
5.SPR手雷好像是修复了，但其他的依然没有修复，比如在我测试的地图中又env_snow实体，我基本看不到下雪的痕迹

**Comment by q52888940** [comment]
关于4,cs原版是又黄色的粒子效果的，现在他没了，而是多了一群黑色的粒子，这本来没什么，但他数量很大，而且重力是飘着的，看着很难受 你可以使他变少然后让他重力正常吗

**Comment by q52888940** [comment]
6打玻璃的印花弹孔没有了，依然是普通的弹孔，CS打玻璃原本会有特殊的玻璃弹孔
7.为什么手电筒或者我创造的light不能在黑暗下加亮V模型了

**Comment by hzqst** [comment]
![111](https://user-images.githubusercontent.com/12287588/150644700-597de422-5277-42b8-8083-f90474f21b37.png)
我这里这些bug都是修复了的状态，建议你使用mh_pluginlist观察一下插件版本，是不是使用了以前的插件

**Comment by hzqst** [comment]
> 7.为什么手电筒或者我创造的light不能在黑暗下加亮V模型了

因为`_light_dynamic 1`状态下的手电筒光照方式是照亮一个锥形区域，而v模并不在锥形区域内，想要照亮v模请换回`r_light_dynamic 0`

**Comment by q52888940** [comment]
我重新安装了版本，但是5-6还是没有修复啊，下雪依然看不到，打玻璃材质弹孔还是错误的

**Comment by q52888940** [comment]
你会修复吗，我现在看不到下雪

**Comment by hzqst** [comment]
![3](https://user-images.githubusercontent.com/12287588/162181601-92842dcb-d4f9-419b-af98-544ed71fcadc.png)
下雪的粒子效果已在 b9dfc80cec39ff99afa3a42c533d3603d076aa8a 中修复。
