### ISSUE TITLE
Viewmodel Color Remapping is broken.

### ISSUE THREAD

**Issue by mariotime1287** [hzqst/MetaHookSv#11]
This one's a bit odd. Recolorable viewmodels are completely broken, and the active HUD elements and particles cause changes to the color palette. 

https://user-images.githubusercontent.com/69475944/123993174-38703200-d99a-11eb-9fd0-63490c0b30ef.mp4

Here's a colorable viewmodel pack to test it with: https://gamebanana.com/mods/167480

(The bug happens with multiple colorable viewmodel packs)

Also, it's for sure a Renderer issue, because here's a video taken with the same models, just without MetaHookSv:

https://user-images.githubusercontent.com/69475944/123994640-918c9580-d99b-11eb-9bb8-979e6b276363.mp4

**Comment by hzqst** [comment]
Fixed in f96bea8.
