### ISSUE TITLE
环境光遮蔽在CS中不起效果

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#112]
我尝试在SVEN COOP使用成功 但在CS中没有任何效果
另外你是否会考虑设置每个不同V模型不同的FOV，因为使用了HDR我原来的设置V模型不同的FOV的插件失效了，我真的很需要他，不然在高FOV时拉伸手臂令我非常难受

**Comment by hzqst** [comment]
环境光遮蔽看起来没效果可能是因为intensity设置的太低了

intensity=0.0：
![4](https://user-images.githubusercontent.com/12287588/154401571-e023bf93-b82d-45fb-84bd-79c9d7e241aa.png)

intensity=5.0：
![3](https://user-images.githubusercontent.com/12287588/154401573-9bdf194a-c42f-4cf5-a1e8-885425aed3b6.png)

**Comment by hzqst** [comment]
将来会增加分离`viewmodel FOV` 跟 `世界画面 FOV`的功能，也就是说将来会支持以**不同FOV**渲染`viewmodel` 和 `世界画面`

**Comment by q52888940** [comment]
如何设置intensity

**Comment by q52888940** [comment]
ssao只有在r_vertical_fov 为1的时候才会出现效果，CS默认的FOV是90..

**Comment by q52888940** [comment]
![ST3SL8I 8 {99R992E$5PCO](https://user-images.githubusercontent.com/68973128/154402704-088531fe-7a0f-4d8c-bd9d-91749d106dab.png)
![PIE58~NK)4FUT3OYP7PEUP8](https://user-images.githubusercontent.com/68973128/154402717-40aa01a1-dc4d-41e2-ba78-35e2153216e2.png)

**Comment by q52888940** [comment]
在高FOV时，SSAO才会出现SSAO效果，我尝试用插件更改FOV也同样有效

**Comment by hzqst** [comment]
FOV小于一定数值时SSAO会出现闪烁问题，所以我故意在低FOV时禁用了SSAO效果。
