### ISSUE TITLE
请问二次元渲染需要自己写贴图名吗

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#114]
我看到你的文件里FACE是你贴图的前缀，我的模型脸贴图前缀不是FACE我是否需要把所有贴图名都写一下呢，可我直接复制你的进入游戏也是有效果

**Comment by hzqst** [comment]
添加了`STUDIO_NF_CELSHADE_FACE`的贴图只是亮部暗部分布方式不一样而已，其他没有任何区别，不加也没有问题。只要贴图同时存在`STUDIO_NF_CELSHADE`和`STUDIO_NF_FLATSHADE`就可以成功添加CelShade效果。如果贴图本身没有`STUDIO_NF_FLATSHADE`的标记，可以用[HLAM](https://github.com/SamVanheer/HL_Tools/wiki/Half-Life-Asset-Manager)手动添加，或者在_external.txt文件里添加
```
{
    "classname" "studio_texture"
    "basetexture" "*"
    "flags" "STUDIO_NF_FLATSHADE"
}
```
