### ISSUE TITLE
为什么在CS中没有模型描边

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#115]
![20220207175942_1](https://user-images.githubusercontent.com/68973128/152766634-3281af78-a267-4b8c-afd4-dae21ee6a8a1.jpg)
![cesces0000](https://user-images.githubusercontent.com/68973128/152766768-98377148-228f-4e02-83b0-7124e62dde07.jpg)

**Comment by q52888940** [comment]
同样的模型同样的设置 在CS中二次元只有简单的反光效果，另外SSAO也只有在某些分辨率下正常显现

**Comment by q52888940** [comment]
在CS中 在某些地图不规律的闪退，我没办法找到原因，如果有什么方法能找到原因请告诉我，我愿意帮你找漏洞

**Comment by q52888940** [comment]
在cs零点行动测试

**Comment by hzqst** [comment]
猜测是CZ的GameStudioRenderer的StudioRenderModel函数没hook上，画描边需要hook StudioRenderModel

**Comment by hzqst** [comment]
commit 0f1e52659e86a8f61425607772b1204fe82b9718 中已经修复该问题

问题来源：CS:CZ的client GameStudioRenderer虚表排列跟Sven Co-op不一致，导致之前硬编码的虚函数index在CS:CZ中定位到了错误的StudioRenderModel函数
![2](https://user-images.githubusercontent.com/12287588/154400457-f121a748-3bd8-4310-828d-83cd7ca8685a.png)

修正方式：将硬编码改为使用动态定位的方式，尽量保证在各种mod中都能定位到正确的StudioRenderModel函数

修正结果：
![20220217113000](https://user-images.githubusercontent.com/12287588/154400753-b01458d0-d272-4344-8d37-d2af63cabf0e.png)
