### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#116]
![#de_aztec_css0000_看图王](https://user-images.githubusercontent.com/68973128/153520829-6fe83e37-c6d4-4d5c-8807-74f3e3bd9fda.png)
在CZ中，某些地图开局购买AK47开火就会崩溃，有时V模还会成这样
我真的希望您希望修复这个BUG，因为他我很多地图都会出现闪退崩溃

**Comment by q52888940** [comment]
链接：https://pan.baidu.com/s/1asMy2vw2VVElpFerM3K2ww 
提取码：w14d

**Comment by hzqst** [comment]
无法复现

**Comment by q52888940** [comment]
感谢你回复我 但是我在某些地图会经常性闪退，有什么办法知道闪退原因吗

**Comment by hzqst** [comment]
[F5调试](https://github.com/hzqst/MetaHookSv/blob/main/READMECN.md#%E8%B0%83%E8%AF%95)

**Comment by q52888940** [comment]
打开METAHOOK.SLN
---------------------------
Microsoft Visual Studio
---------------------------
未能正确加载解决方案中的一个或多个项目。

有关详细信息，请参见“输出”窗口。
---------------------------
确定   
---------------------------
VS2019

**Comment by q52888940** [comment]
无法找到V143生成工具

**Comment by q52888940** [comment]
E:\MetaHookSv-main\MetaHook.vcxproj : error  : 找不到导入的项目“E:\MetaHookSv-main\global.props”。请确认 Import 声明“global.props”中的表达式正确，且文件位于磁盘上。  E:\MetaHookSv-main\MetaHook.vcxproj


E:\MetaHookSv-main\Plugins\CaptionMod\CaptionMod.vcxproj : error  : 找不到导入的项目“E:\MetaHookSv-main\global.props”。请确认 Import 声明“..\..\global.props”中的表达式正确，且文件位于磁盘上。  E:\MetaHookSv-main\Plugins\CaptionMod\CaptionMod.vcxproj


E:\MetaHookSv-main\Plugins\BulletPhysics\BulletPhysics.vcxproj : error  : 找不到导入的项目“E:\MetaHookSv-main\global.props”。请确认 Import 声明“..\..\global.props”中的表达式正确，且文件位于磁盘上。  E:\MetaHookSv-main\Plugins\BulletPhysics\BulletPhysics.vcxproj


E:\MetaHookSv-main\Plugins\StudioEvents\StudioEvents.vcxproj : error  : 找不到导入的项目“E:\MetaHookSv-main\global.props”。请确认 Import 声明“..\..\global.props”中的表达式正确，且文件位于磁盘上。  E:\MetaHookSv-main\Plugins\StudioEvents\StudioEvents.vcxproj


E:\MetaHookSv-main\Plugins\SteamScreenshots\SteamScreenshots.vcxproj : error  : 找不到导入的项目“E:\MetaHookSv-main\global.props”。请确认 Import 声明“..\..\global.props”中的表达式正确，且文件位于磁盘上。  E:\MetaHookSv-main\Plugins\SteamScreenshots\SteamScreenshots.vcxproj


E:\MetaHookSv-main\Plugins\Renderer\Renderer.vcxproj : error  : 找不到导入的项目“E:\MetaHookSv-main\global.props”。请确认 Import 声明“..\..\global.props”中的表达式正确，且文件位于磁盘上。  E:\MetaHookSv-main\Plugins\Renderer\Renderer.vcxproj


E:\MetaHookSv-main\Plugins\CommunicationDemo\CommunicationDemo.vcxproj : error  : 找不到导入的项目“E:\MetaHookSv-main\global.props”。请确认 Import 声明“..\..\global.props”中的表达式正确，且文件位于磁盘上。  E:\MetaHookSv-main\Plugins\CommunicationDemo\CommunicationDemo.vcxproj


E:\MetaHookSv-main\Plugins\SCModelDownloader\SCModelDownloader.vcxproj : error  : 找不到导入的项目“E:\MetaHookSv-main\global.props”。请确认 Import 声明“..\..\global.props”中的表达式正确，且文件位于磁盘上。  E:\MetaHookSv-main\Plugins\SCModelDownloader\SCModelDownloader.vcxproj


E:\MetaHookSv-main\Plugins\StudioEvents\StudioEvents.vcxproj : error  : 找不到导入的项目“E:\MetaHookSv-main\global.props”。请确认 Import 声明“..\..\global.props”中的表达式正确，且文件位于磁盘上。  E:\MetaHookSv-main\Plugins\StudioEvents\StudioEvents.vcxproj


E:\MetaHookSv-main\MetaHook.vcxproj : error  : 找不到导入的项目“E:\MetaHookSv-main\global.props”。请确认 Import 声明“global.props”中的表达式正确，且文件位于磁盘上。  E:\MetaHookSv-main\MetaHook.vcxproj

**Comment by hzqst** [comment]
https://github.com/hzqst/MetaHookSv/blob/main/READMECN.md#%E6%9E%84%E5%BB%BA%E6%96%B9%E6%B3%95

先正常构建一次再执行调试

**Comment by hzqst** [comment]
你没有安装[git客户端](https://gitforwindows.org/)？
