### ISSUE TITLE
关于FOG

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#117]
![de_inferno_cz0001](https://user-images.githubusercontent.com/68973128/153690936-3df7af63-a14e-4ce1-aea4-3ed8346eafa3.jpg)
![de_inferno_cz0000](https://user-images.githubusercontent.com/68973128/153690937-fe8b0e56-f6c1-44c2-8c68-0ecc36ca8a66.jpg)
渲染器的FOG实体密度是不是有些过于大了

**Comment by q52888940** [comment]
![csg_dust20001](https://user-images.githubusercontent.com/68973128/153691289-4565b07a-eb11-4b00-b523-2919e6aea421.jpg)
![csg_dust20002](https://user-images.githubusercontent.com/68973128/153691290-90107f0d-fafa-4b03-9d28-44f41245c2a8.jpg)
在某些地图本来应该隐藏的纹理没有隐藏

**Comment by hzqst** [comment]
地图名？

**Comment by q52888940** [comment]
所有带有FOG实体的地图，请在CZ随便找一个地图并开启雾化

**Comment by q52888940** [comment]
麻烦你下载此地图
https://gamebanana.com/mods/85490
因为我没办法上传
请测试此地图，并且最好游玩一会儿并且在重新进入此地图，有时候会导致崩溃，我这边没办法测试原因

**Comment by q52888940** [comment]
我已经测试了最新版 非常好
但FOG与游戏崩溃的原因依然没解决，这个真的很重要，在我发的这张地图游玩一会儿在重新进入是100%游戏崩溃的，不只是这一张地图，还有很多地图，但我没办法调试我的插件，所以能麻烦你测试一下原因吗

另外我给玩家模型设置了附带模型(背枪)如果一时间出现太多的话游戏也会崩溃

**Comment by hzqst** [comment]
FOG的问题已经在commit 3ea99292428581c0a32e21b33ebd0e4bc02a293b中修复
效果如下：
![1](https://user-images.githubusercontent.com/12287588/154421104-9d8d543c-3058-42e3-9a5a-46f2d7766ca4.png)

**Comment by hzqst** [comment]
游戏崩溃可能跟你的AMXX插件有关系，建议上传崩溃时的dmp文件（C:\Program Files (x86)\Steam\dumps\*.dmp）

**Comment by q52888940** [comment]
我已经关闭AMXX测试过，他还是会崩溃，崩溃的触发条件是:
游玩一会儿在进入一次这张地图
进入另一张地图玩一会儿在进入这张地图

**Comment by hzqst** [comment]
有没有替换游戏根目录(`\steamapps\common\Half-Life`)下的SDL2.dll？有没有崩溃dmp？

**Comment by q52888940** [comment]
SDL2.dll与FreeImage.dll都是替换过的，我尝试过关闭所有插件
他不只在一张地图会崩溃，在CZ一些官方地图也会崩溃，崩溃的原因不详，但最大的触发条件是，游玩一会儿换一张地图就会崩溃

**Comment by hzqst** [comment]
所以说到底有没有崩溃dmp文件？

**Comment by hzqst** [comment]
csg_dust2地图中黑色方块是用VIS裁剪的方式隐藏的，而renderer.dll修改了BSP渲染方式之后已经忽略了VIS裁剪，所以 89d182490fde41f4966f5ff58846d7b1999bed26 中忽略了名称以_HIDDEN结尾的纹理，来缓解该问题。

**Comment by q52888940** [comment]
感谢更新
另外崩溃可能是META_audio造成的，所以抱歉
