### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#118]
好吧 我现在坚信是渲染插件让我的游戏崩溃了，他没有DMP文件
我说一个我刚研究的100%闪退方法
首先进入CZ官方地图de_torn_cz,随便选择一个人物，然后在进入官方地图,de_stadium_cz
100%必闪退，麻烦请你测试

**Comment by q52888940** [comment]
这个方法我测试了很多遍 每次都会闪退。。

**Comment by hzqst** [comment]
无法复现

**Comment by hzqst** [comment]
建议建立HLDS服务器之后connect进去测试，不要建立本地ListenServer，排除服务端影响

**Comment by q52888940** [comment]
经测试使用hlds开服务器暂时没有崩溃的情况，请问这是什么原因

**Comment by hzqst** [comment]
> 经测试使用hlds开服务器暂时没有崩溃的情况，请问这是什么原因

服务端插件（如AMXX）有问题，或者加载的模型、地图有问题，也有可能是本地建立listenserver时游戏进程使用的内存过多导致内存不足（超过1.5GB时崩溃，但是这种可能性很低）。

**Comment by q52888940** [comment]
我重新在了CZ测试 并且没有安装AMXX 依然有时会在换地图闪退 并且是不规律的，我本以为是我的配置问题，所以我更换使用了其他电脑测试，但结果依然是不确定性的闪退
有没有可能下个版本会在崩溃时给出闪退原因？

**Comment by hzqst** [comment]
这里强烈建议你安装Visual Studio之后自己F5调试游戏，如果崩溃的话会中断在VS调试器里，可以看到明确的崩溃原因

**Comment by q52888940** [comment]
OK 感谢 我会尝试一下
