### ISSUE TITLE
Specific method of invisibility broken.

### ISSUE THREAD

**Issue by mariotime1287** [hzqst/MetaHookSv#12]
Got another weird one for you. Certain interactive objects with multiple normally invisible parts will not be invisible, namely in the conversion of the mod Uplinked ( http://scmapdb.wikidot.com/map:uplinked ) . The issues I've found are as such: Extra legs appearing on the cargo-robot (hl_u12_a5), duplicated submarines everywhere that the submarine stops at (hl_u12_a6), the Proto-Gluon having cubes where the spiral would be (hl_u12_a7), and finally, the satellite dish is duplicated (hl_u12_a9).
![image](https://user-images.githubusercontent.com/69475944/124362684-8be5b880-dc04-11eb-9d62-565151f7dcfa.png)
![image](https://user-images.githubusercontent.com/69475944/124362695-9bfd9800-dc04-11eb-9262-a4b31ae9d1ee.png)
![image](https://user-images.githubusercontent.com/69475944/124362779-1201ff00-dc05-11eb-8699-9abc673f74df.png)

I'm unsure what method these use for invisibility, but it seems to be one that's broken in MetaHookSv. Loading without it shows each of these instances working correctly.

**Comment by hzqst** [comment]
fixed in commit 31da8e0

https://user-images.githubusercontent.com/12287588/124377157-1ac60400-dcdd-11eb-8ce0-5b72870c1442.mp4
