### ISSUE TITLE
[Renderer] Add shadow map for dynamic light(flashlight)?

### ISSUE THREAD

**Issue by hzqst** [hzqst/MetaHookSv#134]

**Comment by di57inct** [comment]
Does this mean having the flashlight cast dynamic shadows like the one from Trinity Renderer? Would be really awesome.
https://steamcommunity.com/sharedfiles/filedetails/?id=751636726

**Comment by hzqst** [comment]
Has been added in the latest version of Renderer

**Comment by di57inct** [comment]
❤️❤️❤️
