### ISSUE TITLE
CS是否无法使用BulletPhysics

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#14]
CS是否无法使用BulletPhysics

**Comment by hzqst** [comment]
目前暂时不行，触发布娃娃化的条件（也就是死亡动画的动作序列）目前是强制写死在代码里的，过段时间我会将其修改成支持非SC的其他mod。

**Comment by anchurcn** [comment]
```c
pseqdesc = (mstudioseqdesc_t*)((byte*)m_pStudioHeader + m_pStudioHeader->seqindex) + m_pCurrentEntity->curstate.sequence;
if (pseqdesc->activity == ACT_DIE_BACKSHOT || ACT_DIESIMPLE || ACT_DIEBACKWARD...)
{
	// current entity is playing die sequence
}
```

**Comment by q52888940** [comment]
所以只要修改序列就可以使用在CS上？

**Comment by q52888940** [comment]
我使用VS2013编译错误

**Comment by hzqst** [comment]
> 我使用VS2013编译错误

编译至少需要VS2017

![image](https://user-images.githubusercontent.com/12287588/126466980-11ef94f8-09f8-4f26-bb37-84832630d9d5.png)

**Comment by q52888940** [comment]
你还会支持CS吗 我已经迫不及待了

**Comment by hzqst** [comment]
Added support for other mods in https://github.com/hzqst/MetaHookSv/commit/d2194d1ddcf192724a2df3a0c0643e387769d1e4
