### ISSUE TITLE
[BulletPhysics][CS 1.6] Ragdolls not working?

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#143]
EDIT: I even tried with the original "zombie.mdl" from half life converted to use as a player model in CS and with your original ragdoll text file except i edited the animations' IDs. Still doesn't work: https://www.youtube.com/watch?v=IJ8fT1vbSh8

Currently using @q52888940 's ragdoll file. Can't understand what's wrong. Here is a video, the file and the model bone list.
https://www.youtube.com/watch?v=VhvmnPi0K_o

```
] version
Protocol version 48
Exe version 1.1.2.7 (cstrike)
Exe build: 19:53:27 Aug  3 2020 (8684)
] mh_pluginlist 
|index|api|             plugin name|          plugin version|
|    0| v4|        StudioEvents.dll|     2021-12-06T13:31:04|
|    1| v4|       BulletPhysics.dll|     2022-06-13T13:51:33|
|    2| v4|            Renderer.dll|     2022-06-13T13:47:48|
|    3| v4|          CaptionMod.dll|     2022-06-13T13:51:00|
```

```
[DeathAnim]
101 0
102 0
103 0
104 0
105 0
106 0
107 0
108 0
109 0
110 0

[RigidBody]
Pelvis 1 24 capsule -4.0 7.0 0.1 6
L Thigh 24 26 capsule -4.0 7.0 0.1 6
L Calf 25 29 capsule -4.0 7.0 0.1 6
L Foot 26 31 capsule -4.0 7.0 0.1 6
R Thigh 29 1 capsule -4.0 7.0 0.1 6
R Calf 30 3 capsule -4.0 7.0 0.1 6
R Foot 31 4 capsule -4.0 7.0 0.1 6
Spine1 3 5 capsule -4.0 7.0 0.1 6
Spine2 4 7 capsule -4.0 7.0 0.1 6
Spine3 5 6 capsule -4.0 7.0 0.1 6
Neck 6 9 capsule -4.0 7.0 0.1 6
Head 7 10 capsule -4.0 7.0 0.1 6
L Clavicle 8 11 capsule -4.0 7.0 0.1 6
L UpperArm 9 17 capsule -4.0 7.0 0.1 6
L Forearm 10 8 capsule -4.0 7.0 0.1 6
L Hand 11 4 capsule -4.0 7.0 0.1 6
R Clavicle 16 1 capsule -4.0 7.0 0.1 6
R UpperArm 17 5 capsule -4.0 7.0 0.1 6
R Forearm 18 3 capsule -4.0 7.0 0.1 6
R Hand 19 7 capsule -4.0 7.0 0.1 6
L Hand 8 16 capsule -4.0 7.0 0.1 6

[Constraint]
Spine Head conetwist 6 15 0 0 0 0 6 0 0.01 0.01 0.2
Pelvis Spine conetwist 1 5 0 0 4 0 -4 0 0.0 0.0 0.1

Spine LArm conetwist 7 8 0 0 0 0 -4 0 0.33 0.33 1.0
LArm LArm2 conetwist 8 9 0 0 0 0 -4 0 0.2 0.2 0.2
LArm2 LHand conetwist 9 10 0 0 0 0 3 0 0.2 0.2 0.3

Spine RArm conetwist 11 12 0 0 0 0 -4 0 0.33 0.33 1.0
RArm RArm2 conetwist 12 13 0 0 0 0 -4 0 0.2 0.2 0.2
RArm2 RHand conetwist 13 14 0 0 0 0 3 0 0.2 0.2 0.3

Pelvis LLeg conetwist 41 41 0 0 0 0 -7 0 0.1 0.1 0.25
LLeg2 LLeg hinge 41 41 0 0 0 0 8 0 -0.6 0.0 0

Pelvis RLeg conetwist 46 46 0 0 0 0 -7 0 0.1 0.1 0.25
RLeg2 RLeg hinge 46 46 0 0 0 0 8 0 -0.6 0.0 0

[Barnacle]
LLeg2 dof6 0 8 0 40000 4 16
LLeg2 chewlimit 0 0 0 0 1.0 4
RLeg dof6 0 0 0 30000 -16 16
RLeg chewlimit 0 0 0 0 1.0 4
Pelvis chewforce 0 0 0 8000 1.0 0

[Gargantua]
Head GargMouth dof6z 0 0 0 20000 -8 16
Spine GargMouth dof6z 0 0 0 20000 -16 32
Pelvis GargMouth dof6z 0 0 0 20000 -24 64
```

```
  0 "Bip01" -1
  1 "Bip01 Pelvis" 0
  2 "Bip01 Spine" 1
  3 "Bip01 Spine1" 2
  4 "Bip01 Spine2" 3
  5 "Bip01 Spine3" 4
  6 "Bip01 Neck" 5
  7 "Bip01 Head" 6
  8 "Bip01 L Clavicle" 6
  9 "Bip01 L UpperArm" 8
 10 "Bip01 L Forearm" 9
 11 "Bip01 L Hand" 10
 12 "Bip01 L Finger0" 11
 13 "Bip01 L Finger01" 12
 14 "Bip01 L Finger1" 11
 15 "Bip01 L Finger11" 14
 16 "Bip01 R Clavicle" 6
 17 "Bip01 R UpperArm" 16
 18 "Bip01 R Forearm" 17
 19 "Bip01 R Hand" 18
 20 "Bip01 R Finger0" 19
 21 "Bip01 R Finger01" 20
 22 "Bip01 R Finger1" 19
 23 "Bip01 R Finger11" 22
 24 "Bip01 L Thigh" 1
 25 "Bip01 L Calf" 24
 26 "Bip01 L Foot" 25
 27 "Bip01 L Toe0" 26
 28 "-- L Knee" 24
 29 "Bip01 R Thigh" 1
 30 "Bip01 R Calf" 29
 31 "Bip01 R Foot" 30
 32 "Bip01 R Toe0" 31
 33 "Object04" 2
```

**Comment by hzqst** [comment]
There was a problem with Renderer.dll finding incorrect GameStudioRenderer virtual function index in Counter-Strike client dll which was found in #107 and has been fixed in commit 9e50acede913dad327e8ded7ba18fce5a480cd0b. I'm not sure if it's the same issue but I'll have a try.

**Comment by di57inct** [comment]
I used the latest version as of yesterday(17.06.2022).

**Comment by hzqst** [comment]
The rigid body creation progress works fine on Sven but not on Counter-Strike, might be some issue with bone matrix or some what, I am digging into it.

**Comment by hzqst** [comment]
Looks like the StudioSetupBones is at vftable[6] instead of vftable[7]
![image](https://user-images.githubusercontent.com/12287588/174442238-f4873493-eca9-4301-845f-57c9eb57d51f.png)
That explain why bonematrix was messed up

**Comment by hzqst** [comment]
![image](https://user-images.githubusercontent.com/12287588/174443964-78f8c4c4-7f90-4682-b300-bdb2b90bb6f8.png)

A gign ragdoll configuration for reference :
https://github.com/hzqst/MetaHookSv/blob/main/Build/cstrike_hd/models/player/gign_ragdoll.txt

Should work on latest commit.

**Comment by di57inct** [comment]
Will test as soon as possible. Thank you very much <3

**Comment by di57inct** [comment]
Works fine, there is a problem though. The spheres from the torso and pelvis collide when enabled, giving the weird look you can also see in your picture. The same file also doesn't work for the rest of the hd models, but it should because as far as I know the bone names and IDs are the same(not sure, will look into it).
![20220618203006_1](https://user-images.githubusercontent.com/3608544/174451205-9ca4a74e-d473-45c8-ba75-50b211182dc2.jpg)
