### ISSUE TITLE
[Renderer][CS 1.6] Studio/brush models and some sprites aren't reflected in water

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#144]
Note that the trail and ring sprites were reflected, but anything else(like the studio/brush models, some sprites, etc) other than the map itself wasn't.
https://www.youtube.com/watch?v=G-GfDgGat2Y

It used to work(sort of - notice the wrong positioning of the player and other studio models reflection) in previous versions:
https://www.youtube.com/watch?v=cpuIs_LEnQ0
https://www.youtube.com/watch?v=F3lbyFdawRM
https://www.youtube.com/watch?v=u-CeqMkKEy8

```
] version
Protocol version 48
Exe version 1.1.2.7 (cstrike)
Exe build: 19:53:27 Aug  3 2020 (8684)
] mh_pluginlist 
|index|api|             plugin name|          plugin version|
|    0| v4|        StudioEvents.dll|     2021-12-06T13:31:04|
|    1| v4|       BulletPhysics.dll|     2022-06-13T13:51:33|
|    2| v4|            Renderer.dll|     2022-06-13T13:47:48|
|    3| v4|          CaptionMod.dll|     2022-06-13T13:51:00|
```

**Comment by hzqst** [comment]
Water don't reflect entities unless `"level" "WATER_LEVEL_REFLECT_WORLD"` is changed to `"level" "WATER_LEVEL_REFLECT_ENTITY"` in `/gamedir/renderer/default_entity.txt`.

tips: performance will be bad if too many entities are rendered in reflect view.

**Comment by di57inct** [comment]
That sounds like it explains why the performance on the previous tests was also worse, it was probably enabled.
Also don't forget about the erroneus reflections bug.

It would be nice to be able to select what to render in the following categories:
1. Map entities(brush/studio/sprites) - since it looks bad when not having the entire map rendered in reflections and usually there usually aren't many anyway so it wouldn't be such a big performance killer
2. Player(1 -> MaxPlayers) models + sprites(radio message/weapon muzzle flashes)
3. Third party studio models(others than map entities and players)
4. Sprites(I don't think sprites have such a big impact on performance so there's probably no need to disable them or to have a 3rd party option though)

Thank you very much for this outstanding project :)

**Comment by di57inct** [comment]
That sounds like it explains why the performance on the previous tests was also worse, it was probably enabled.
