### ISSUE TITLE
Rendering problem when resizing window

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#145]
When resizing the window, the following problem occurs. It gets fixed when the window is resized to its original startup size.
![Untitled](https://user-images.githubusercontent.com/3608544/174351436-967c3f7b-95ec-4cb1-8e22-cc92f58bec21.png)

**Comment by hzqst** [comment]
![image](https://user-images.githubusercontent.com/12287588/174434544-2fffd9db-343d-4748-8147-852797014de0.png)
problem with resizing window has been fixed in commit  74a28f20faf782861ee736360709ff2b4f45a81f

**Comment by di57inct** [comment]
Thank you :)
