### ISSUE TITLE
[Renderer] bindless textures are not working on AMD cards?

### ISSUE THREAD

**Issue by hzqst** [hzqst/MetaHookSv#146]

**Comment by di57inct** [comment]
Tell me how to test this and give you a result. I have an AMD card.

**Comment by hzqst** [comment]
> Tell me how to test this and give you a result. I have an AMD card.

AMD card got black screen or flickering in game unless -nobindless added to launch parameter ( at least on my Radeon RX 6800 )

**Comment by di57inct** [comment]
Works fine for me on both CS and SVC. Tested in both windowed and fullscreen.
RX 580 - driver version 22.5.1(28.04.2022)

**Comment by hzqst** [comment]
There was something wrong with my AMD graphic driver, after reinstalling the graphic driver everything just works fine,
