### ISSUE TITLE
[Renderer] Full entity being rendered in reflections instead of only the part that is "visible" to the reflective area

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#147]
https://user-images.githubusercontent.com/3608544/174451465-77853a23-6470-4134-ad98-6936cae6eba2.mp4

**Comment by hzqst** [comment]
Should be fixed : d1f35f878ac3c3bbb1132748d154494336d063e8
![333](https://user-images.githubusercontent.com/12287588/174478322-61937ded-e468-4d38-9063-d69ade4f1aa5.png)

**Comment by di57inct** [comment]
Tested. Looks like it's fixed now. Thank you <3
