### ISSUE TITLE
[Renderer] Shadows being fully drawn multiple times

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#148]
`r_shadow_angles "45 35 0"`

![20220618212139_1](https://user-images.githubusercontent.com/3608544/174451613-ab2d7b09-d91b-4c10-b841-b3790056633c.jpg)
![20220618192839_1](https://user-images.githubusercontent.com/3608544/174451669-c3d09650-1824-46f7-947e-9eb7d8ec73b8.jpg)
![20220618235034_1](https://user-images.githubusercontent.com/3608544/174457178-29c7d04d-84d7-45cb-a57f-141b85b0b078.jpg)

This is probably related to the same problem too:

https://user-images.githubusercontent.com/3608544/174456325-812c2dd0-1cbd-4747-8007-34e25348d36f.mp4

**Comment by hzqst** [comment]
This also occurs in Source 2007 and Source 2013

There is no way to avoid shadow leaking unless we render shadow for the whole scene just like what Counter-Strike : Global Offense does in de_dust2, but it will be another thing. (and how to deal with shadow indoor?)

![3](https://user-images.githubusercontent.com/12287588/174462145-2216a6e0-1e98-4926-a405-635e59bd43a1.png)

**Comment by di57inct** [comment]
I still think there's something wrong.

https://user-images.githubusercontent.com/3608544/175105845-7c79ae07-8985-4057-bbf2-456cf47bdc9d.mp4

![vlcsnap-00002](https://user-images.githubusercontent.com/3608544/175106982-801e6838-75ff-49a2-b8fc-c0dd62ce6cfc.png)

**Comment by di57inct** [comment]
More examples on this:

https://user-images.githubusercontent.com/3608544/177643225-d500cbe7-a838-44e1-8222-db6eaef384b0.mp4

https://user-images.githubusercontent.com/3608544/177643237-35817f93-b9c8-493f-829e-3de4f3348d9f.mp4

**Comment by di57inct** [comment]
Another example on this. Seems distance also has a role in it.

https://user-images.githubusercontent.com/3608544/179060931-3723c661-314d-4094-b94e-d9ae934f32d9.mp4
