### ISSUE TITLE
是否还支持3DSKY

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#15]
我在制作地图时一直想把起源一些地图的3DSKY搬来，于是我使用了老版本的渲染器，但他不能把固体实体或模型的3DSKY在游戏世界显示，我想请问新版是否解决了此问题

**Comment by hzqst** [comment]
Meta Renderer for Sven-Coop 不再支持一切破解引擎硬编码限制的功能（因为SvEngine本来就会提升这些最大限制），如：允许加载的最大纹理尺寸、最大动态光源数量、最大可见实体数量、lightmap大小限制，以及任何Sven-Coop本身支持的功能，如：3d skybox、镜子等。

**Comment by q52888940** [comment]
也就是说除了画质 我无法在使用置换贴图等功能了吗

**Comment by hzqst** [comment]
置换贴图是指把bsp的wad贴图换成外部贴图？这个功能还是保留了的，只是使用方法和以前不一样

**Comment by q52888940** [comment]
是否有使用方法的链接
StudioEvents能否说下他的用途

**Comment by q52888940** [comment]
是否能告诉我使用的方法或相关教学连接

**Comment by hzqst** [comment]
> 是否有使用方法的链接
> StudioEvents能否说下他的用途

你可以用细节纹理(_detail.txt)暂时替代，效果和替换贴图差不了多少，等功能可用了再全部换成替换贴图。

StudioEvents的文档正在完善中。

**Comment by q52888940** [comment]
最后一个问题 StudioEvents的用途是什么

**Comment by q52888940** [comment]
StudioEvents.DLL

**Comment by hzqst** [comment]
> StudioEvents.DLL

[DOCUMENTATION](StudioEvents.md) [中文文档](StudioEventsCN.md)
