### ISSUE TITLE
[Renderer] Reflection issues

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#153]
```
] version 
Protocol version 48
Engine version 5.0.1.7 (svencoop)
Engine build: 11:20:57 Jun 12 2021 (8948)
] mh_pluginlist 
|index|api|             plugin name|          plugin version|
|    0| v4|    SteamScreenshots.dll|     2021-12-06T13:30:23|
|    1| v4|   SCModelDownloader.dll|     2022-05-26T19:41:28|
|    2| v4|   CommunicationDemo.dll|     2022-06-13T13:51:21|
|    3| v4|        StudioEvents.dll|     2021-12-06T13:31:04|
|    4| v4|  BulletPhysics_AVX2.dll|     2022-06-18T22:57:00|
|    5| v4|       Renderer_AVX2.dll|     2022-06-18T18:54:21|
|    6| v4|          CaptionMod.dll|     2022-06-13T13:51:00|
```
![20220617215410_1](https://user-images.githubusercontent.com/3608544/174388031-61ac4adf-36f5-4cea-b483-133650f6a9e9.jpg)
![20220617215416_1](https://user-images.githubusercontent.com/3608544/174388028-7c2a9025-85d6-4b6f-bacd-3e3ddcb46b5b.jpg)

https://user-images.githubusercontent.com/3608544/174456437-613b9d07-9b16-45d9-b983-049956e1bdc7.mp4

**Comment by di57inct** [comment]
More examples on this issue:

https://user-images.githubusercontent.com/3608544/175719165-119ecdba-8892-44ae-b8a7-d36dcf0f278e.mp4

**Comment by hzqst** [comment]
![3](https://user-images.githubusercontent.com/12287588/177929082-acf1ca33-b0c1-44bb-a3e0-c436ff47058f.png)
Same issue as #153
Impossible to fix until I found a solution to cull those meshes off from rendering.

**Comment by di57inct** [comment]
Idk if it helps, but notice that in my last video it also reflects what's under the reflective area instead of just the content above.

**Comment by di57inct** [comment]
Here's another example(and the last since I don't know how helpful these are). Not too different from the previous...

https://user-images.githubusercontent.com/3608544/180070506-ee08a588-d3d3-40c1-9ced-b0a72e9dc31b.mp4

**Comment by hzqst** [comment]
Should've been fixed since bsp node based culling introduced.
