### ISSUE TITLE
[BulletPhysics] Ragdoll fails to update position

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#156]
https://user-images.githubusercontent.com/3608544/174457405-6a2b80b5-2392-4b3e-888d-bae98115e326.mp4

https://user-images.githubusercontent.com/3608544/174457406-e58e7c2e-9b43-4114-9c04-d654d169897b.mp4

https://user-images.githubusercontent.com/3608544/174457408-4ef1616c-bfa7-43d9-9637-bec1ad95d152.mp4

**Comment by hzqst** [comment]
It makes no sense to update invisible ragdolls for players who are in firstperson mode and not able to see themself, isn't it?

**Comment by di57inct** [comment]
In CS and CZ, when you die, your body becomes visible(the camera goes into 3rd person mode) while the death animation plays by default unless the server is modded and sets you back to first person.
So, in the videos' cases, ragdoll position should of been updated on every death.
This also happens if debugging is off.
I think it's because the ragdoll triggers on frame 0 of the death anim which happens before the player is switched to 3rd person.

**Comment by di57inct** [comment]
Here are a couple of tests with your latest ragdoll text file. It seems like frame number trigger is not the problem since they all start at 100.

https://user-images.githubusercontent.com/3608544/174471858-fe00f426-ba7a-400e-b568-792a556bd8fb.mp4


https://user-images.githubusercontent.com/3608544/174471861-bde33136-d819-477a-ba7a-a98eccd52b23.mp4

**Comment by hzqst** [comment]
> 

Just want to ask an out-of-topic question, did you ever encounter mp.dll (my dll is signed by Valve at Aug. 4th 2020) crash when player get hit by env_laser?
like this:
![image](https://user-images.githubusercontent.com/12287588/174474922-34a919dc-5056-4192-8714-c1f56cf03483.png)

And the [reverse-engineered server dll code](https://github.com/number201724/CS16ND/blob/8217b59923873966f2fde1ba64b3338406ed08b0/dlls/player.cpp#L567) says the type-cast `CBasePlayer::Instance(pevAttacker)` that cast `pevAttacker` (it's env_laster) into `CBasePlayer *` caused the crash. just wonder if you have the problem too or if it's just my fault.

**Comment by hzqst** [comment]
> Here are a couple of tests with your latest ragdoll text file. It seems like frame number trigger is not the problem since they all start at 100. Also notice that the ragdoll is still updating on the ground even if the player can't see his body.
> 

Should be fixed on commit 1c317aedb99a9ff40fc086735117da6098726fb1

**Comment by di57inct** [comment]
> > 
> 
> Just want to ask an off-topic question, did you ever encounter mp.dll (my dll is signed by Valve at Aug. 4th 2020) crash when player get hit by env_laser? like this: ![image](https://user-images.githubusercontent.com/12287588/174474922-34a919dc-5056-4192-8714-c1f56cf03483.png)
> 
> The [reverse-engineered server dll code](https://github.com/number201724/CS16ND/blob/8217b59923873966f2fde1ba64b3338406ed08b0/dlls/player.cpp#L567) says the type-cast `CBasePlayer::Instance(pevAttacker)` that cast `pevAttacker` (it's env_laster) into `CBasePlayer *` caused the crash. just wonder if you have the problem too or if it's just my fault.

My game has never crashed like that for a very long time now. If you can provide me with some maps to test it I will come back with a result.

> Should be fixed on commit [1c317ae](https://github.com/hzqst/MetaHookSv/commit/1c317aedb99a9ff40fc086735117da6098726fb1)

Will test. Thank you.

**Comment by hzqst** [comment]
[movewith.zip](https://github.com/hzqst/MetaHookSv/files/8935250/movewith.zip)
move across the env_laser and game will crash

**Comment by di57inct** [comment]
Tested. Marking as fixed.

> > 
> 
> Just want to ask an off-topic question, did you ever encounter mp.dll (my dll is signed by Valve at Aug. 4th 2020) crash when player get hit by env_laser? like this: ![image](https://user-images.githubusercontent.com/12287588/174474922-34a919dc-5056-4192-8714-c1f56cf03483.png)
> 
> The [reverse-engineered server dll code](https://github.com/number201724/CS16ND/blob/8217b59923873966f2fde1ba64b3338406ed08b0/dlls/player.cpp#L567) says the type-cast `CBasePlayer::Instance(pevAttacker)` that cast `pevAttacker` (it's env_laster) into `CBasePlayer *` caused the crash. just wonder if you have the problem too or if it's just my fault.

> [movewith.zip](https://github.com/hzqst/MetaHookSv/files/8935250/movewith.zip) move across the env_laser and game will crash

Works fine for me:
Please add me on Steam if you want so I can further help you with testing when needed :)
https://bit.ly/D7StProfile

https://user-images.githubusercontent.com/3608544/174493880-2a3db2a4-c685-4f2c-bcb8-37d50b485027.mp4

https://user-images.githubusercontent.com/3608544/174493881-556c946c-1b29-4f15-ad62-968425d0f202.mp4
