### ISSUE TITLE
[BulletPhysics] Corpse buoyancy dependeant on client FPS

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#158]
https://user-images.githubusercontent.com/3608544/174472495-b474d2c0-0842-4f70-947d-9db454aeccb4.mp4

https://user-images.githubusercontent.com/3608544/174472496-5889a4b2-cbdd-49c9-aa3f-f42d04df8224.mp4

**Comment by di57inct** [comment]
I think this applies to ragdoll calculations in general too as far as i noticed.

**Comment by hzqst** [comment]
Changing `bv_pretick` to 0 should fix the issue.

**Comment by di57inct** [comment]
https://user-images.githubusercontent.com/3608544/174492756-3b713d8f-2ac7-4718-ad2a-3b6170eaa4e6.mp4

**Comment by di57inct** [comment]
Confirming this as fixed. FPS doesn't affect it anymore, but there is another issue as in they are not floating to the surface anymore. More testing is needed by changing ragdoll files and will come back with an update.

https://user-images.githubusercontent.com/3608544/177826057-52d434c2-8511-4d4c-bddf-dc58f748b5dd.mp4

**Comment by di57inct** [comment]
Updated the ragdoll files with buoyancy force set to 1.01. This is the result. Seems good enough to me with both low and high fps. Please close the issue if you think nothing more needs to be done.

https://user-images.githubusercontent.com/3608544/178265358-df019185-e56a-44fe-9bcf-f00e21911f9a.mp4
