### ISSUE TITLE
Fov

### ISSUE THREAD

**Issue by haophan1996** [hzqst/MetaHookSv#159]
Hi developers,
I want to change FOV, is the a way to change fov or modify it

**Comment by hzqst** [comment]
try `r_adjust_fov 0/1` or `r_vertical_fov 0/1` or `viewmodel_fov [VALUE]`

**Comment by haophan1996** [comment]
it not work, is there a file that I can look at the code

**Comment by hzqst** [comment]
default_fov already does what you want in Half-Life or Sven Co-op, do you mean Counter-Strike or other mod that blocks default_fov changing?

**Comment by haophan1996** [comment]
I think so. default_fov does not working , it just make mouse sensitive fast or slower

**Comment by haophan1996** [comment]
im using the module of the csbte

**Comment by hzqst** [comment]
You will have to create a new metahook plugin that hijack user message ["SetFOV"](https://wiki.alliedmods.net/Half-life_1_game_events#SetFOV) as it's transmitted from game server in [Counter-Strike based mod](https://github.com/CKFDevPowered/CKF3Alpha/blob/4e1ee1bdb2aeebe3548eb57b104f2a9cf4dccf97/src/Client/hud.cpp#L988).

**Comment by haophan1996** [comment]
it just not working, maybe not work with csbte metahook, thank you for your help
