### ISSUE TITLE
地图的置换功能

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#16]
哈哈 又是我 真不好意思 但我很激动能在CS用到这个插件
我在detail文件里写了cugroundi_PARALLAX tides_brick_wall_a.png 8 8, cugroundi_NORMAL tides_brick_wall_a_normal.png 8 8
控制台没有报错误，但当我打开r_wsurf_detail 1时 地图没有更换纹理 反而是让我地图上的其他纹理替换了上去,cugroundi是我的纹理名，是我的写法有问题吗 我想替换地图的材质给地图增加法线贴图 另外我想问我如何使用原来的细节纹理
你在这个文档中没有给出更多的写法

**Comment by hzqst** [comment]
[原贴图名]_PARALLAX 是视差贴图

[原贴图名]_NORMAL 是法线贴图，需要手电之类的动态光照才能看出效果，静态lightmap下是没效果的

普通的细节纹理就跟原版GoldSrc里的细节纹理用法一样的啊，tga放置的位置也是一样的。

**Comment by q52888940** [comment]
如何让模型获得法线纹理，如何置换原有的纹理成为另一张图，是否自带模型高亮功能呢？抱歉我这么多的问题

**Comment by hzqst** [comment]
> 如何让模型获得法线纹理，如何置换原有的纹理成为另一张图，是否自带模型高亮功能呢？抱歉我这么多的问题

模型目前暂不支持法线贴图，替换贴图目前暂不支持，高亮功能只需要修改模型贴图的flag即可（使用HLMV或者[HLAM](https://github.com/SamVanheer/HalfLifeAssetManager)都可以修改）：
![1111](https://user-images.githubusercontent.com/12287588/126291631-5992f302-e658-4769-9829-d3b97c19904f.png)

**Comment by q52888940** [comment]
![de_youxiceshi0000](https://user-images.githubusercontent.com/68973128/126292258-9c66b309-5f34-4bde-beb3-38bb13b5a82a.jpg)
当我使用原版细节纹理功能并打开细纹纹理功能时 我的贴图变成了全黑

**Comment by hzqst** [comment]
> ![de_youxiceshi0000](https://user-images.githubusercontent.com/68973128/126292258-9c66b309-5f34-4bde-beb3-38bb13b5a82a.jpg)
> 当我使用原版细节纹理功能并打开细纹纹理功能时 我的贴图变成了全黑

可以把你测试用的地图和对应的细节纹理文件、_detail.txt文件一起打包发来我试试吗？

**Comment by q52888940** [comment]
[新建文件夹 (5).zip](https://github.com/hzqst/MetaHookSv/files/6847097/5.zip)

**Comment by q52888940** [comment]
[新建文件夹 (5).zip](https://github.com/hzqst/MetaHookSv/files/6847108/5.zip)

**Comment by hzqst** [comment]
已修复： d80a5eb

**Comment by q52888940** [comment]
我使用了最新版 但我觉得他并没有被修复 甚至出现了一些闪屏的状况

**Comment by q52888940** [comment]
你可以在检查一下吗

**Comment by q52888940** [comment]
![cs_assault0000](https://user-images.githubusercontent.com/68973128/126314264-5262976b-4069-4c54-be61-03fb752a1c70.jpg)
甚至在assault这张图在我扭转方向时屏幕成为了这样

**Comment by q52888940** [comment]
![cs_assault0001](https://user-images.githubusercontent.com/68973128/126314411-cda51954-000a-45c0-9e00-94eafdc0c9a7.jpg)
我的天空怪怪的 旁边好像有一条线

**Comment by hzqst** [comment]
已修复：901bb10

**Comment by q52888940** [comment]
可以发布DLL文件吗

**Comment by hzqst** [comment]
> 可以发布DLL文件吗

updated in c4e4864

**Comment by q52888940** [comment]
他有效 谢谢
你能顺便解决我的字幕问题吗

**Comment by hzqst** [comment]
替换贴图功能已经在fe2572e中增加


![image](https://user-images.githubusercontent.com/12287588/126326532-e55a8b8b-7f3d-43ba-a828-41ff2f9d07c3.png)


https://user-images.githubusercontent.com/12287588/126326494-c675c5b1-73ea-48cb-903b-281f8dfd014a.mp4
