### ISSUE TITLE
[BP] Ragdolls getting stuck in broken func_breakable

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#160]
https://user-images.githubusercontent.com/3608544/175105181-eea98781-19bb-4c72-81de-7892f30a07af.mp4

**Comment by hzqst** [comment]
Probably because broken func_breakable (its effects has been marked with EF_NODRAW bit and not sent to clients anymore) not removed from physic world.

**Comment by di57inct** [comment]
This has been sort of fixed in the latest update. Now it goes through even when the entity is solid.

https://user-images.githubusercontent.com/3608544/175710642-ef67e47a-681f-4e82-846a-2c43d9d6f338.mp4

**Comment by hzqst** [comment]
Should have been fixed in 257a788f03b8d363b85903434ba33f117fbc299f

**Comment by di57inct** [comment]
Fully tested. Fix confirmed. Ty <3
