### ISSUE TITLE
[BP] Crash when breaking a func_breakable

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#164]
https://user-images.githubusercontent.com/3608544/175109237-ffbe4a79-0608-45a1-940e-cc1654f127f7.mp4

**Comment by hzqst** [comment]
Uploading 2022-06-23 10-51-06.mp4…

Can't repro with movewith.bsp
Better have a try with HLDS and see if it's a server-side crash?

**Comment by di57inct** [comment]
It seems it crashes if you modify "_radgdoll.txt" files while the game is running. Further testing is needed on a dedicated server to make sure it's not actually a server crash.
