### ISSUE TITLE
[Suggestion] Make chat color follow con_color CVar values

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#168]

**Comment by hzqst** [comment]
Should have been done in fbe80cdc567d6c267c3ae082809cd0a3019c0296.

**Comment by di57inct** [comment]
Tested, confirmed. Ty ^^

**Comment by di57inct** [comment]
Tested. Input is still white. Otherwise, already printed chat messages remain the color they were printed with at the time before changing con_color but I don't really consider this as a bug.
![image](https://user-images.githubusercontent.com/3608544/177808931-69d984d8-8457-4302-8bba-ce86c1abf183.png)

**Comment by hzqst** [comment]
chat input entry can be configured in `TextEntry.TextColor`. not considered as a bug.
