### ISSUE TITLE
细节纹理

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#17]
原版
![de_dust_cz0003](https://user-images.githubusercontent.com/68973128/126339567-8d1d099f-9938-4a5b-b15a-c0cb83225cb3.jpg)
新的
![de_dust_cz0000](https://user-images.githubusercontent.com/68973128/126339578-42ae7442-7e9f-4dc2-bc62-f989cbb101c8.jpg)

**Comment by q52888940** [comment]
请问这算是错误吗 还是就是这样 我如何调整到原版的细节纹理状态

**Comment by hzqst** [comment]
是不是放大倍数的原因？ 
`detail/dt_stone2 1.0 1.0`  这两个1.0是细节纹理的放大倍数，可能我的8.0相当于原版的0.125，我的0.125相当于原版的8.0？

**Comment by q52888940** [comment]
我非常建议您试一下 因为我把比例调整为0.1时 出现了一些不好说的BUG。。

**Comment by hzqst** [comment]
Fixed in latest commit.
