### ISSUE TITLE
阴影错误

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#18]
![20210720200727_1](https://user-images.githubusercontent.com/68973128/126343260-cbbfe153-836f-4558-bcb7-eab3b6caf936.jpg)
![20210720200721_1](https://user-images.githubusercontent.com/68973128/126343269-71529127-3303-4ec3-9e78-3085c2c9f1f6.jpg)
![20210720200722_1](https://user-images.githubusercontent.com/68973128/126343275-6c21f318-699f-4e96-b946-24d1d0a19491.jpg)
我不清楚这是不是错误。

另外2个BUG：
1，在CS中 人质的阴影和玩家是相反的 玩家输入90是在正前方 而人质却在正后方。
2,在CS中 玩家死亡后尸体方向会立刻转向，也许这是因为玩家死后身体并不是一个实体的缘故？

**Comment by q52888940** [comment]
bug3
![de_dust0000](https://user-images.githubusercontent.com/68973128/126352697-d5e05c0c-9c99-460d-9ed6-99738de8a122.jpg)

**Comment by q52888940** [comment]
bug4 
![de_dust0001](https://user-images.githubusercontent.com/68973128/126353322-56b3dbe8-93c1-4e03-9cee-7b04925a800c.jpg)

**Comment by hzqst** [comment]
> bug3
> ![de_dust0000](https://user-images.githubusercontent.com/68973128/126352697-d5e05c0c-9c99-460d-9ed6-99738de8a122.jpg)

图中没看出有什么问题啊？

**Comment by q52888940** [comment]
请看隧道前方 能看到的最大距离好像被限制了
正常的
![de_dust0000(1)](https://user-images.githubusercontent.com/68973128/126357519-94f0b782-97c2-4c5c-b168-136642de3964.jpg)

为什么我在游戏内的FPS被锁定在了200？或者也许我只能到达这么高
我的显卡时2060S

**Comment by q52888940** [comment]
你会修复这三个错误吗 这样我就可以等待新版本在下载

**Comment by q52888940** [comment]
错误4
我刚刚下载了修复缩放纹理版本 但当我打开手电筒时。。
![de_dust2_cz0001](https://user-images.githubusercontent.com/68973128/126360454-d5ac9f93-ad59-4437-9cf8-8a2549f066a8.jpg)

**Comment by hzqst** [comment]
> 错误4
> 我刚刚下载了修复缩放纹理版本 但当我打开手电筒时。。
> ![de_dust2_cz0001](https://user-images.githubusercontent.com/68973128/126360454-d5ac9f93-ad59-4437-9cf8-8a2549f066a8.jpg)

这个问题是因为你给地面应用了不正确的法线贴图

**Comment by hzqst** [comment]
> 已修改:BUG3是地图原因导致所以无需修复
> 
> 为什么我在游戏内的FPS被锁定在了200？或者也许我只能到达这么高
> 我的显卡是 2060S

引擎本身限制最大200fps，再高物理计算会出问题

**Comment by hzqst** [comment]
阴影穿墙的问题是因为渲染阴影用的深度图中拿不到地面的位置信息，早期版本的起源引擎也是这样的，这里不会修复，也无法修复。

![gm_construct0000](https://user-images.githubusercontent.com/12287588/126404311-90c67472-f0e1-4181-8466-a9251425b6b7.jpg)

![gm_flatgrass0000](https://user-images.githubusercontent.com/12287588/126404315-d844b298-51a2-43e2-8927-3f97126bfb88.jpg)

**Comment by q52888940** [comment]
![image](https://user-images.githubusercontent.com/68973128/126436545-65367a96-02ec-48b0-99a1-abe9d355951a.png)
![image](https://user-images.githubusercontent.com/68973128/126436560-8392c1e3-abd4-4809-ac3e-821c6db13c6d.png)
在这个两个图中我没有使用任何法线纹理 我只使用了原版自带的细节纹理 请检查一下
另外我的CS在原版FPS可以达到200-300之间 这不是很大的问题 我只是想问一下

**Comment by q52888940** [comment]
也请您注意这两个bug
1，在CS中 人质的阴影和玩家是相反的 玩家输入90是在正前方 而人质却在正后方。
2,在CS中 玩家死亡后尸体方向会立刻转向，也许这是因为玩家死后身体并不是一个实体的缘故？
他们并没有这么严重 您可以选择性修复
但我迫切的希望您修复上面图中的细节纹理问题

**Comment by q52888940** [comment]
![de_dust2_cz0003](https://user-images.githubusercontent.com/68973128/126438665-4284befc-17b5-4594-9243-adf7213270e5.jpg)
![de_dust2_cz0002](https://user-images.githubusercontent.com/68973128/126438671-2f3923e1-785f-4ba9-8f0b-7bc13c523941.jpg)

**Comment by q52888940** [comment]
R_LoadDetailTextures: Missing basetexture mosque_roof1
R_LoadDetailTextures: Missing basetexture mosque_roof2
R_LoadDetailTextures: Missing basetexture pi_cratebig
R_LoadDetailTextures: Missing basetexture pi_cratebigt
R_LoadDetailTextures: Missing basetexture pi_rust
R_LoadDetailTextures: Missing basetexture SandCCrete
R_LoadDetailTextures: Missing basetexture SandRoadTgtB
R_LoadDetailTextures: Missing basetexture SandWllDoor2
R_LoadDetailTextures: Missing basetexture sky
R_LoadDetailTextures: Missing basetexture wll_hllway_orn
R_LoadDetailTextures: Missing basetexture wll_msq_top
R_LoadDetailTextures: Missing basetexture wll_msq_trm
R_LoadDetailTextures: Missing basetexture wll_sndstn_pln
也许你的细节纹理不支持一些贴图？ 我没有更改官方自带的细节纹理的任何设置

**Comment by hzqst** [comment]
> ![image](https://user-images.githubusercontent.com/68973128/126436545-65367a96-02ec-48b0-99a1-abe9d355951a.png)
> ![image](https://user-images.githubusercontent.com/68973128/126436560-8392c1e3-abd4-4809-ac3e-821c6db13c6d.png)
> 在这个两个图中我没有使用任何法线纹理 我只使用了原版自带的细节纹理 请检查一下
> 另外我的CS在原版FPS可以达到200-300之间 这不是很大的问题 我只是想问一下

Fixed in 5ffe254

**Comment by q52888940** [comment]
![Uploading de_dust2_cz0002.jpg…]()
![Uploading de_dust2_cz0003.jpg…]()

**Comment by q52888940** [comment]
他有效 已解决
