### ISSUE TITLE
[BP] Ragdolls clipping through solids

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#185]
https://user-images.githubusercontent.com/3608544/179210368-abe3507c-6e99-4a40-bd22-b3fa36bb0bf4.mp4

**Comment by di57inct** [comment]
Is it recommend though to change those CVars to higher values? As far as I've understood messing with bv_scale is not recommended. And what impact will they have on client performance?

**Comment by hzqst** [comment]
> Is it recommend though to change those CVars to higher values? As far as I've understood messing with bv_scale is not recommended. And what impact will they have on client performance?

From what I've seen in the previous test, bv_scale = 10 performs better than bv_scale = 1 as rigidbody movement in each simulation step is much more accurate.

**Comment by di57inct** [comment]
Idk why but the CVar on my side is somehow defaulted to 0.5. I tried setting bv_simrate to 128 and haven't seen any difference. Also, how about the performance impact?

**Comment by hzqst** [comment]
> bv_scale

A map restart is required after changing bv_scale

**Comment by di57inct** [comment]
Using bv_scale 7.5 and bv_simrate 96 or above fixes this issue as far as I've noticed. Closing until proven otherwise.
