### ISSUE TITLE
水不见了

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#19]
![20210721142914_1](https://user-images.githubusercontent.com/68973128/126441911-45d3dddd-a98d-4687-95d0-499e761f9fe0.jpg)
我测试了最新版 有些地图水不见了，有些地图水的质量大大不如上个版本 因为他们好像没有混合着原版的纹理？

**Comment by hzqst** [comment]
> ![20210721142914_1](https://user-images.githubusercontent.com/68973128/126441911-45d3dddd-a98d-4687-95d0-499e761f9fe0.jpg)
> 我测试了最新版 有些地图水不见了，有些地图水的质量大大不如上个版本 因为他们好像没有混合着原版的纹理？


着色器文件有更新，你是不是只替换了dll文件但是没有覆盖着色器文件？

![image](https://user-images.githubusercontent.com/12287588/126442345-eb81733e-5b12-4992-8d71-31a9bac63d4e.png)

**Comment by q52888940** [comment]
哦 是的 不好意思 已解决
