### ISSUE TITLE
VGUI unusable if custom options are opened

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#190]
If the advanced video or subtitle options are opened, VGUI menu like buying weapons, choosing team, etc is unusable both with cursor and keys.

https://user-images.githubusercontent.com/3608544/182030477-1706cdd4-7511-46b6-a3c9-a2a243a154c7.mp4

**Comment by hzqst** [comment]
Should have been fixed in 47c6052655b3ca28396e0e67bba00409494e9571

**Comment by di57inct** [comment]
Confirming fix. Options close on menu exit/resuming game. Closing the issue :)
