### ISSUE TITLE
VERY long game loading time with .dds textures (DXT5)

### ISSUE THREAD

**Issue by d3nchk** [hzqst/MetaHookSv#193]
For some unknown reason, when using textures format .dds game takes a very long time to load.
It's not about the iron, because the old version of nagist does not suffer from such an affliction.
The game is installed on an NVME SSD
The resolution of the texture does not play a role.
If you use a format other than .dds it loads quickly, but this is not the solution.
It should be just the other way around, textures in .dds format are loaded directly into memory without any extra processing.

Translated with www.DeepL.com/Translator (free version)

**Comment by hzqst** [comment]
![image](https://user-images.githubusercontent.com/12287588/186634442-07372cd6-cbd7-4a8e-95f5-f8f47add90c0.png)
Did you ever check the "Generate Mipmaps" when exporting textures?
If not, the graphic driver has to decompress the texture, generate mipmaps, and compress the mipmaps into DXT format which will take a bunch of time.

**Comment by d3nchk** [comment]
> ![image](https://user-images.githubusercontent.com/12287588/186635678-8cc34a81-05cd-4912-b0eb-20a13ea18370.png) Did you ever check the "Generate Mipmaps" when exporting textures? If not, the graphic driver has to decompress the texture, generate mipmaps, and compress the mipmaps into DXT format which will take a bunch of time.

Yes, of course, this is not the first time I've used this format.
Also, as you may have noticed, I pointed out that the problems a not playable on the previous (old version, metahook 1.5c (not sv)).
Also I made a retexture of other projects in the same format, there is no problem with it, here is clearly a problem, but there is no logs, and I can not even see at what stages of delay occurs. After loading the map errors in the console no.
And long loading and in use in the file [map].detail
and in [model].external
Resolution again, does not play a role, equally long loading and textures 1024x1024 and 4096x4096.
Please look at what's the matter there.

Translated with www.DeepL.com/Translator (free version)

**Comment by hzqst** [comment]
You said "If you use a format other than .dds it loads quickly"
So you have tried using a format other than .dds in MetaHookSv?

**Comment by d3nchk** [comment]
> You said "If you use a format other than .dds it loads quickly" So you have tried using a format other than .dds in MetaHookSv?

It doesn't work for me. I'm refining the project for 4k
Re-textured map cs_assault with 4096x4096 texture resolution, takes up a lot of space in video memory, as well as on the disk, if you use formats other than .dds (dxt 5).
In this case we are talking about VRAM more than 8GB (I have only 8)
So this is not the way out. You can, of course, just abandon the idea. But I decided to write here first, hoping that the issue will be resolved, because it is specifically faulty render, but not a format .dds

**Comment by hzqst** [comment]
> > You said "If you use a format other than .dds it loads quickly" So you have tried using a format other than .dds in MetaHookSv?
> 
> It doesn't work for me. I'm refining the project for 4k Re-textured map cs_assault with 4096x4096 texture resolution, takes up a lot of space in video memory, as well as on the disk, if you use formats other than .dds (dxt 5). In this case we are talking about VRAM more than 8GB (I have only 8) So this is not the way out. You can, of course, just abandon the idea. But I decided to write here first, hoping that the issue will be resolved, because it is specifically faulty render, but not a format .dds

Try add `-nobindless` to the launch parameter to rule out the influence of bindless-mode.

Btw, Did you compare the loading time of DXT5 with other formats in 512x512 or smaller size that fits in your VRAM? or did you just compare the loading time of MetaHookSv with older verison or MetaRenderer and make the conclusion that MetaHookSv has impact on performance loading DXT textures?

**Comment by d3nchk** [comment]
> > > You said "If you use a format other than .dds it loads quickly" So you have tried using a format other than .dds in MetaHookSv?
> > 
> > 
> > It doesn't work for me. I'm refining the project for 4k Re-textured map cs_assault with 4096x4096 texture resolution, takes up a lot of space in video memory, as well as on the disk, if you use formats other than .dds (dxt 5). In this case we are talking about VRAM more than 8GB (I have only 8) So this is not the way out. You can, of course, just abandon the idea. But I decided to write here first, hoping that the issue will be resolved, because it is specifically faulty render, but not a format .dds
> 
> Try add `-nobindless` to the launch parameter to rule out the influence of bindless-mode.
> 
> Btw, Did you compare the loading time of DXT5 with other formats in 512x512 or smaller size that fits in your VRAM? or did you just compare the loading time of MetaHookSv with older verison of MetaRenderer and make the conclusion that MetaHookSv has impact on performance loading DXT textures?

Okay, I will try to apply the specified command line parameter.

Regarding the texture resolution and trying to apply-yes, I tried that.
In this case, I tried throwing textures on weapons, there resolution did not exceed 1024x1024, the situation is exactly the same. Plus, in addition to the increased startup time, there was a hard lag when purchasing weapons, lag of about 3 seconds.

**Comment by hzqst** [comment]
> Why game startup time (I mean engine startup, not map loading) is much longer than it was?
Because MetaHookSv does code analysis on engine instead of simple signatures search at game startup every time, which will take a bunch of time.
> Why cost gigs of VRAM?
Because all vertices, indices and some other data that required for rendering are loaded into VRAM. and those data are resident on VRAM which means they will not be freed until next level change.

**Comment by hzqst** [comment]
> > > > You said "If you use a format other than .dds it loads quickly" So you have tried using a format other than .dds in MetaHookSv?
> > > 
> > > 
> > > It doesn't work for me. I'm refining the project for 4k Re-textured map cs_assault with 4096x4096 texture resolution, takes up a lot of space in video memory, as well as on the disk, if you use formats other than .dds (dxt 5). In this case we are talking about VRAM more than 8GB (I have only 8) So this is not the way out. You can, of course, just abandon the idea. But I decided to write here first, hoping that the issue will be resolved, because it is specifically faulty render, but not a format .dds
> > 
> > 
> > Try add `-nobindless` to the launch parameter to rule out the influence of bindless-mode.
> > Btw, Did you compare the loading time of DXT5 with other formats in 512x512 or smaller size that fits in your VRAM? or did you just compare the loading time of MetaHookSv with older verison of MetaRenderer and make the conclusion that MetaHookSv has impact on performance loading DXT textures?
> 
> I applied the parameter, it had no effect It hangs on the "precaching resources" stage for a very long time I caught it with a stopwatch, a total of 25 textures (diffuse+normal maps), loaded 1 minute 10 seconds (and this is not a cold start). This is a very long time.

Did you try some simple-box map like bloodstrike or what?

**Comment by d3nchk** [comment]
> > Why game startup time (I mean engine startup, not map loading) is much longer than it was?
> > Because MetaHookSv does code analysis on engine instead of simple signatures search at game startup every time, which will take a bunch of time.
> > Why cost gigs of VRAM?
> > Because all vertices, indices and some other data that required for rendering are loaded into VRAM. and those data are resident on VRAM which means they will not be freed until next level change.

I wrote it wrong, sorry. Loading the map is exactly a long time, not the start of the game

**Comment by d3nchk** [comment]
> Did you try some simple-box map like bloodstrike or what?

In this case, I tried only 3 maps - de_dust, cs_assault, de_celtic

**Comment by hzqst** [comment]
> > Did you try some simple-box map like bloodstrike or what?
> 
> In this case, I tried only 3 maps - de_dust, cs_assault, de_celtic

Better have a try on simple-box map like bloodstrike. if bloodstrike loads in a remarkable short time, that means uploading BSP nodes and leaves to VRAM takes too much time.

**Comment by d3nchk** [comment]
Anyway, why on the old renderer 1.5s , there are no such problems? Maps are loaded quickly, there is no lag when purchasing weapons.
On the old renderer other problems, he is old, there are many commands, such as enhanced fov, texture size limitation 2048x2048, and a number of other inconveniences.
That's why I got hooked on the sv-version of the renderer.

**Comment by d3nchk** [comment]
The bloodstrike map has no wad file, I don't know what textures are used there to replace them

**Comment by hzqst** [comment]
> Anyway, why on the old renderer 1.5s , there are no such problems?

* the old renderer never does somethings like "uploading vertices, indices, bsp nodes and leaves to VRAM at map loading", that is why the old renderer looks faster than MetaHookSv at map loading stage.

> Why do I upload those data to VRAM ?
* To accelerate the real-time rendering.

**Comment by hzqst** [comment]
> The bloodstrike map has no wad file, I don't know what textures are used there to replace them

Use [bspguy](https://github.com/wootguy/bspguy) to check what textures are used.

**Comment by d3nchk** [comment]
Unfortunately, bloodstrike does not pick up textures, for what reason - I do not know.
With the help of bspguy textures I tracked, .txt file created, pickup does not happen
Screenshot attache
![1](https://user-images.githubusercontent.com/112010596/186726259-5ee9e973-8f71-4add-bc2b-ee33a6fdaaf8.png)
d

**Comment by d3nchk** [comment]
I figured it out, apparently the coding was wrong. I created a new .txt file and the textures picked up.
However, unfortunately, the problem of long loading map did not go anywhere. 1 minute exactly, loaded the map.
While there are 10 textures involved (including normal map)
Something wrong with the renderer.

**Comment by hzqst** [comment]
Is the loading progress faster when you remove the `bloodstrike_detail.txt` or not?
Could you please provide the `bloodstrike_detail.txt` and the dds textures that being used?

**Comment by d3nchk** [comment]
Okay, the files are in the archive at the link
And I remind you, just in case, that the download time does not depend on the resolution. In this case, I sent 2048x4096,4096x4096+normal maps

https://drive.google.com/drive/folders/19zoah_PZI-pARts9DKs63ijIV-Y4nr-F?usp=sharing

**Comment by hzqst** [comment]
> Okay, the files are in the archive at the link And I remind you, just in case, that the loading time does not depend on the resolution. In this case, I sent 2048x4096,4096x4096+normal maps
> 
> https://drive.google.com/drive/folders/19zoah_PZI-pARts9DKs63ijIV-Y4nr-F?usp=sharing

It turns out that the legacy call [`glTexParameteri(GL_TEXTURE_2D, GL_GENERATE_MIPMAP, (mipmap) ? GL_TRUE : GL_FALSE);`](https://github.com/hzqst/MetaHookSv/blob/aae9d6d5e0b3781796f3a8abd91fb68d96007c72/Plugins/Renderer/gl_draw.cpp#L166)
which does the unwanted mipmap generation causes the loading time to be longer than expected.

Should have been fixed in the commit 0264b04d9ec1b6079d46251d93b28ae3341e9aea

**Comment by d3nchk** [comment]
> > Okay, the files are in the archive at the link And I remind you, just in case, that the loading time does not depend on the resolution. In this case, I sent 2048x4096,4096x4096+normal maps
> > https://drive.google.com/drive/folders/19zoah_PZI-pARts9DKs63ijIV-Y4nr-F?usp=sharing
> 
> It turns out that the legacy call [`glTexParameteri(GL_TEXTURE_2D, GL_GENERATE_MIPMAP, (mipmap) ? GL_TRUE : GL_FALSE);`](https://github.com/hzqst/MetaHookSv/blob/aae9d6d5e0b3781796f3a8abd91fb68d96007c72/Plugins/Renderer/gl_draw.cpp#L166) which does the unwanted mipmap generation causes the loading time to be longer than expected.
> 
> Should have been fixed in the commit [0264b04](https://github.com/hzqst/MetaHookSv/commit/0264b04d9ec1b6079d46251d93b28ae3341e9aea)
> 
> ![image](https://user-images.githubusercontent.com/12287588/187077103-62792e68-e65a-4fe9-abd1-7a9a7cc70b47.png)

It seems it went, I was already happy, because the loading speed maps lightning speed, however, it quickly became clear that half of the textures do not load, or some other bug, I enclose screenshots
![de_celtic0000](https://user-images.githubusercontent.com/112010596/187080944-40c724ae-7dd4-4206-9690-4139b40f50de.png)
![de_celtic0001](https://user-images.githubusercontent.com/112010596/187080946-a4c6e46d-cd5a-43d3-838e-53be160363f4.png)
.

**Comment by hzqst** [comment]
> > > Okay, the files are in the archive at the link And I remind you, just in case, that the loading time does not depend on the resolution. In this case, I sent 2048x4096,4096x4096+normal maps
> > > https://drive.google.com/drive/folders/19zoah_PZI-pARts9DKs63ijIV-Y4nr-F?usp=sharing
> > 
> > 
> > It turns out that the legacy call [`glTexParameteri(GL_TEXTURE_2D, GL_GENERATE_MIPMAP, (mipmap) ? GL_TRUE : GL_FALSE);`](https://github.com/hzqst/MetaHookSv/blob/aae9d6d5e0b3781796f3a8abd91fb68d96007c72/Plugins/Renderer/gl_draw.cpp#L166) which does the unwanted mipmap generation causes the loading time to be longer than expected.
> > Should have been fixed in the commit [0264b04](https://github.com/hzqst/MetaHookSv/commit/0264b04d9ec1b6079d46251d93b28ae3341e9aea)
> > ![image](https://user-images.githubusercontent.com/12287588/187077103-62792e68-e65a-4fe9-abd1-7a9a7cc70b47.png)
> 
> It seems it went, I was already happy, because the loading speed maps lightning speed, however, it quickly became clear that half of the textures do not load, or some other bug, I enclose screenshots ![de_celtic0000](https://user-images.githubusercontent.com/112010596/187080944-40c724ae-7dd4-4206-9690-4139b40f50de.png) ![de_celtic0001](https://user-images.githubusercontent.com/112010596/187080946-a4c6e46d-cd5a-43d3-838e-53be160363f4.png) .

Could you provide the corresponding map and textures?

**Comment by d3nchk** [comment]
Yes, of course.
https://drive.google.com/drive/folders/19zoah_PZI-pARts9DKs63ijIV-Y4nr-F?usp=sharing

**Comment by hzqst** [comment]
> Yes, of course. https://drive.google.com/drive/folders/19zoah_PZI-pARts9DKs63ijIV-Y4nr-F?usp=sharing
Should have been fixed in a57e17fdd77762cb3f496a4e355155981f2e7047

**Comment by d3nchk** [comment]
> > Yes, of course. https://drive.google.com/drive/folders/19zoah_PZI-pARts9DKs63ijIV-Y4nr-F?usp=sharing
> 
> Should have been fixed in [a57e17f](https://github.com/hzqst/MetaHookSv/commit/a57e17fdd77762cb3f496a4e355155981f2e7047)

Everything works now, thank you for your time!

I literally have a couple of small questions left:

1-How do I apply normal map and specular map to the models?
2-How do I replace the textures in decals.wad?

**Comment by hzqst** [comment]
> > > Yes, of course. https://drive.google.com/drive/folders/19zoah_PZI-pARts9DKs63ijIV-Y4nr-F?usp=sharing
> > 
> > 
> > Should have been fixed in [a57e17f](https://github.com/hzqst/MetaHookSv/commit/a57e17fdd77762cb3f496a4e355155981f2e7047)
> 
> Everything works now, thank you for your time!
> 
> I literally have a couple of small questions left:
> 
> 1-How do I apply normal map and specular map to the models? 2-How do I replace the textures in decals.wad?

1. You can't apply normal textures to models in current version of renderer since there is no tangent information in studiomodel format, we need both normal and tangent information in normal mapping calculation.

3. Decal texture replacer is not ready in current version of renderer but it will be there soon.

**Comment by d3nchk** [comment]
> * You can't apply normal textures to models in current version of renderer since there is no tangent information in studiomodel format, we need both normal and tangent information in normal mapping calculation.
> * As for decal texture replacer and studiomodel's specular texture , they are not ready in current version of renderer but will be there soon.

Ok, thank you.

**Comment by hzqst** [comment]
> > * You can't apply normal textures to models in current version of renderer since there is no tangent information in studiomodel format, we need both normal and tangent information in normal mapping calculation.
> > * As for decal texture replacer and studiomodel's specular texture , they are not ready in current version of renderer but will be there soon.
> 
> Ok, thank you.

Decal replacer has been added in the commit aa28480ff4c5dd18a2704ec997e3c7e79e68fca5, download from [Release](https://github.com/hzqst/MetaHookSv/releases/tag/v20220907)
