### ISSUE TITLE
[Renderer] Crash with bindless-mode on AMD card

### ISSUE THREAD

**Issue by hzqst** [hzqst/MetaHookSv#195]
https://community.amd.com/t5/opengl-vulkan/opengl-user-mode-driver-crash-got-instant-crash-inside/td-p/556169

**Comment by di57inct** [comment]
Adding -nobindless launch parameter should fix this?

**Comment by hzqst** [comment]
> Adding -nobindless launch parameter should fix this?

Maybe or maybe not, -nobindless worked for me until 3 weeks ago amd released another driver update which completely breaks everything. now even -nobindless don't for me.

**Comment by di57inct** [comment]
Latest version that seems to be working is 22.6.1(2022.06.29). Any newer version crashes the game(with or without -nobindless).

**Comment by SonThanhVN** [comment]
waiting for AMD to fix then

**Comment by di57inct** [comment]
Driver update 2023.02.14(23.2.1) seems to fix this issue. Waiting for confirmation.

**Comment by SonThanhVN** [comment]
> 

but it seem the fps still really low

**Comment by hzqst** [comment]
> Driver update 2023.02.14(23.2.1) seems to fix this issue. Waiting for confirmation.

Fix confirmed

**Comment by hzqst** [comment]
> 

Could you open a seperate issue about the performance issue? and also with your GPU information
