### ISSUE TITLE
I have some questions

### ISSUE THREAD

**Issue by d3nchk** [hzqst/MetaHookSv#197]
Once again, hello!

During the testing of this wonderful engine a number of questions have accumulated, I would like to ask you

1. Is it possible to replace only the textures of bullet holes in the decal-replacer, or can all decals be changed, which are contained in decal.wad?
If all, then at least I do not want to change the texture of opal from the explosion of a grenade, the file name {scorch1-3, {smscorch1-3.
2-Started noticing sudden, completely random crashes on the desktop, no reason, no errors, is there a variable to keep a full log of everything in real time? So that at least I can understand when I crash, or send you the bug report.
3-I have a bug, depends on the variable -nobindless, on the map de_dust, which I retextured, there is a gap old textures. On the old build, if you include the variable -nobindless , then there was a bug, while replaced on other maps of all the textures, if you turn off the parameter -nobindless on the map de_dust problem was not, but on other maps, not all the textures are replaced. On the new build, even stranger, the game behaves as if the parameter -nobindless forced, and if you enter this variable in the startup parameters, the game immediately crashed on the desktop.

![de_dust0001](https://user-images.githubusercontent.com/112010596/189171033-4e8a71cc-6d02-4a78-b09f-320321cc4995.png)

**Comment by hzqst** [comment]
1. You can replace any decal that exists in decals.wad by editing `SteamApps/Half-Life/(game_directory)/renderer/decal_textures.txt`, which basically works as how `_detail.txt` does.
2. You can get minidumps at `C:\Program Files (x86)\Steam\dumps\` if you had your Steam installed at default install location.
3. The crash has been fixed in the latest commit

**Comment by d3nchk** [comment]
In fact, I'm doing everything right.
I am attaching the screenshots
In 1-screen you can see the structure, paths and the original image
In 2 we see the stock texture, blurry and horrible
Something's not working right.
![1](https://user-images.githubusercontent.com/112010596/189176916-fdd26390-382d-402d-a529-ca8f74181fc9.png)
![cs_estate0004](https://user-images.githubusercontent.com/112010596/189177144-54cce264-03b7-48f9-b60c-bf87af1f873f.png)

**Comment by hzqst** [comment]
> In fact, I'm doing everything right. I am attaching the screenshots In 1-screen you can see the structure, paths and the original image In 2 we see the stock texture, blurry and horrible Something's not working right. ![1](https://user-images.githubusercontent.com/112010596/189176916-fdd26390-382d-402d-a529-ca8f74181fc9.png) ![cs_estate0004](https://user-images.githubusercontent.com/112010596/189177144-54cce264-03b7-48f9-b60c-bf87af1f873f.png)

filename is not supposed to be started with `{` or `}`

**Comment by d3nchk** [comment]
> > In fact, I'm doing everything right. I am attaching the screenshots In 1-screen you can see the structure, paths and the original image In 2 we see the stock texture, blurry and horrible Something's not working right. ![1](https://user-images.githubusercontent.com/112010596/189176916-fdd26390-382d-402d-a529-ca8f74181fc9.png) ![cs_estate0004](https://user-images.githubusercontent.com/112010596/189177144-54cce264-03b7-48f9-b60c-bf87af1f873f.png)
> 
> filename is not supposed to be started with `{` or `}`, delimiters like `{` `}` `"` will break the txt parsing procedure.

Removed these characters (although even with them, holes from the bullets worked correctly), nothing has changed, as it did not work, and does not work

**Comment by hzqst** [comment]
> > > In fact, I'm doing everything right. I am attaching the screenshots In 1-screen you can see the structure, paths and the original image In 2 we see the stock texture, blurry and horrible Something's not working right. ![1](https://user-images.githubusercontent.com/112010596/189176916-fdd26390-382d-402d-a529-ca8f74181fc9.png) ![cs_estate0004](https://user-images.githubusercontent.com/112010596/189177144-54cce264-03b7-48f9-b60c-bf87af1f873f.png)
> > 
> > 
> > filename is not supposed to be started with `{` or `}`, delimiters like `{` `}` `"` will break the txt parsing procedure.
> 
> Removed these characters (although even with them, holes from the bullets worked correctly), nothing has changed, as it did not work, and does not work

Try `}scorch1` instead of `{scorch1`. The internal name of gradient decal texture is forced to be started with `}` no matter what it was for the first character in WAD:
```
void Draw_MiptexTexture(cachewad_t *wad, byte *data)
{
...

	if (pal[765] == 0 && pal[766] == 0 && pal[767] == 255)
	{
		tex->name[0] = '{';
		tex->gl_texturenum = GL_LoadTexture(tex->name, GLT_DECAL, tex->width, tex->height, bitmap, true, TEX_TYPE_ALPHA, pal);
	}
	else
	{
		tex->name[0] = '}';

		if (gfCustomBuild)
			GL_UnloadTexture(tex->name);

		tex->gl_texturenum = GL_LoadTexture(tex->name, GLT_DECAL, tex->width, tex->height, bitmap, true, TEX_TYPE_ALPHA_GRADIENT, pal);
	}

...

```

**Comment by d3nchk** [comment]
> > > > In fact, I'm doing everything right. I am attaching the screenshots In 1-screen you can see the structure, paths and the original image In 2 we see the stock texture, blurry and horrible Something's not working right. ![1](https://user-images.githubusercontent.com/112010596/189176916-fdd26390-382d-402d-a529-ca8f74181fc9.png) ![cs_estate0004](https://user-images.githubusercontent.com/112010596/189177144-54cce264-03b7-48f9-b60c-bf87af1f873f.png)
> > > 
> > > 
> > > filename is not supposed to be started with `{` or `}`, delimiters like `{` `}` `"` will break the txt parsing procedure.
> > 
> > 
> > Removed these characters (although even with them, holes from the bullets worked correctly), nothing has changed, as it did not work, and does not work
> 
> Try `}scorch1` instead of `{scorch1`. The internal name of gradient decal texture is forced to be started with `}` no matter what it was for the first character in WAD:
> 
> ```
> void Draw_MiptexTexture(cachewad_t *wad, byte *data)
> {
> ...
> 
> 	if (pal[765] == 0 && pal[766] == 0 && pal[767] == 255)
> 	{
> 		tex->name[0] = '{';
> 		tex->gl_texturenum = GL_LoadTexture(tex->name, GLT_DECAL, tex->width, tex->height, bitmap, true, TEX_TYPE_ALPHA, pal);
> 	}
> 	else
> 	{
> 		tex->name[0] = '}';
> 
> 		if (gfCustomBuild)
> 			GL_UnloadTexture(tex->name);
> 
> 		tex->gl_texturenum = GL_LoadTexture(tex->name, GLT_DECAL, tex->width, tex->height, bitmap, true, TEX_TYPE_ALPHA_GRADIENT, pal);
> 	}
> 
> ...
> ```

Yes, that helped, thank you.

However, before I had time to rejoice, immediately identified a strange thing, when you turn on -nobindless mode in the latest build, stopped registering textures that I replaced (ie, when you load the map, they do not pick up at all), it is a bug or feature?

**Comment by hzqst** [comment]
> > > > > In fact, I'm doing everything right. I am attaching the screenshots In 1-screen you can see the structure, paths and the original image In 2 we see the stock texture, blurry and horrible Something's not working right. ![1](https://user-images.githubusercontent.com/112010596/189176916-fdd26390-382d-402d-a529-ca8f74181fc9.png) ![cs_estate0004](https://user-images.githubusercontent.com/112010596/189177144-54cce264-03b7-48f9-b60c-bf87af1f873f.png)
> > > > 
> > > > 
> > > > filename is not supposed to be started with `{` or `}`, delimiters like `{` `}` `"` will break the txt parsing procedure.
> > > 
> > > 
> > > Removed these characters (although even with them, holes from the bullets worked correctly), nothing has changed, as it did not work, and does not work
> > 
> > 
> > Try `}scorch1` instead of `{scorch1`. The internal name of gradient decal texture is forced to be started with `}` no matter what it was for the first character in WAD:
> > ```
> > void Draw_MiptexTexture(cachewad_t *wad, byte *data)
> > {
> > ...
> > 
> > 	if (pal[765] == 0 && pal[766] == 0 && pal[767] == 255)
> > 	{
> > 		tex->name[0] = '{';
> > 		tex->gl_texturenum = GL_LoadTexture(tex->name, GLT_DECAL, tex->width, tex->height, bitmap, true, TEX_TYPE_ALPHA, pal);
> > 	}
> > 	else
> > 	{
> > 		tex->name[0] = '}';
> > 
> > 		if (gfCustomBuild)
> > 			GL_UnloadTexture(tex->name);
> > 
> > 		tex->gl_texturenum = GL_LoadTexture(tex->name, GLT_DECAL, tex->width, tex->height, bitmap, true, TEX_TYPE_ALPHA_GRADIENT, pal);
> > 	}
> > 
> > ...
> > ```
> 
> Yes, that helped, thank you.
> 
> However, before I had time to rejoice, immediately identified a strange thing, when you turn on -nobindless mode in the latest build, stopped registering textures that I replaced (ie, when you load the map, they do not pick up at all), it is a bug or feature?

Fixed in [v20220909](https://github.com/hzqst/MetaHookSv/releases/tag/v20220909)

**Comment by d3nchk** [comment]
Good day!

A fresh batch of questions:
1-Can you implement from your side the possibility of:
a-remove the limit on the size of the sprites, which is currently a measly 512x512
or
b-Realize replacement like _detail textures?
2-I would ask you to look at the plugin metadrawer, it is specified that he works just through the metahook, but when I put it on startup game silently quits, and no errors do not show. This plugin solves one sore point, namely, makes instead of frankly ugly radar, which in addition is not scaled at high resolutions - mini-map! I would very much like to make this damn plugin work!
Link to the plugin with a description: https://gamebanana.com/mods/39420

Translated with www.DeepL.com/Translator (free version)
