### ISSUE TITLE
会不会考虑增加在第一人称看到自己的影子

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#20]
影子很酷 但会不会考虑在第一人称看到自己的影子 我想这对配置要求可能不会很高？

**Comment by hzqst** [comment]
第一人称时不会渲染自己模型，因此无法投射阴影。就算强制渲染一遍自己模型也会出现v模跟地上影子不同步的情况，而且白白浪费性能。

**Comment by q52888940** [comment]
那么会不会考虑加入每个地图的HDR或影子配置文件，这样我可以调整每张地图不同的HDR配置与影子角度

**Comment by hzqst** [comment]
下次更新时会加入

**Comment by hzqst** [comment]
最新版本已经加入，参考https://github.com/hzqst/MetaHookSv/blob/main/Renderer.md文档里的用法
