### ISSUE TITLE
[Renderer] Pixelated shadows

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#201]
![fy_snow0000](https://user-images.githubusercontent.com/3608544/189480904-1a7194ab-6a75-48df-a76b-2ebf9df3205c.jpg)

**Comment by hzqst** [comment]
> I noticed this is based on the resolution of the texture it's projected on so it's not an issue. Where did you say you could increase the density of the shadow itself @hzqst ? If you think it would be worth making it a bit denser by default in the next release, please do so. Closing this but waiting for your reply.

https://github.com/hzqst/MetaHookSv/blob/main/docs/Renderer.md#console-vars-2

`r_shadow_color`

**Comment by di57inct** [comment]
By denser i meant less pixelated
