### ISSUE TITLE
Two errors, likely due to user error

### ISSUE THREAD

**Issue by Gillum-Andrew** [hzqst/MetaHookSv#202]
Hello wonderful person, this is Andrew. I have installed MetaHookSv for Sven Co-op, and unfortunately am beset with two errors. I am not within a high caliber of technological literacy, so I am hoping you may be able to shed some light on these issues.

  So, I downloaded the most recent stable release of MetaHookSv from the git releases page. I followed the instructions, to my knowledge, and put the captionmod, metahook and renderer folders into the svencoop directory, as well as the gfx, maps, models and sound folders into the svencoop_addon directory. I also renamed the plugins_svencoop.lst to plugins.lst. I then placed FreeImage.dll, SDL2.dll and svencoop.exe into the main directory. After this, I ran the game through your executable and was met with the following errors: MH_LoadPlugin: Could not load SCModelDownloader.dll, lasterror = 126 and Fatal Error: 16bit mode is not supported.

  I did notice I could not find any files related to the SCModelDownloader plugin, save for it being referenced in the .lst, and that even cloning the repository and building it myself did not yield the .bat to build the plugin, though I still assume this is all some error on my end. I very much wish to use both MetaHookSv in general as well as this plugin, so your time would be greatly appreciated. Finally, thank you for undertaking this project, it seems very useful and interesting.

**Comment by hzqst** [comment]
Oh I forgot to add SCModelDownloader into the Github Action yml, which should have been fixed in the latest commit
as for "Fatal Error: 16bit mode is not supported.", try -32bpp in the launch parameter

**Comment by Gillum-Andrew** [comment]
Hello again wonderful person and thank you; I grabbed the .dll and used the -32bpp parameter and the two errors are gone, the game launched. That said, now I've run into a new error, and am hoping once more that you will assist me. Upon loading a map, in this case c11_a1, this appears in the console.

setmaster unavailable, start a server first.
No detail texture mapping file: maps/hl_c11_a1_detail.txt
LoadBaseDictionary: 820 lines are loaded.
LoadCustomDictionary: too few lines in the dictionary file.
LoadDDS: Could not open gfx/shot1.dds.
R_LoadTextureEx: Cannot load texture gfx/shot1.dds.
LoadDDS: Could not open gfx/shot_parallax.dds.
R_LoadTextureEx: Cannot load texture gfx/shot_parallax.dds.
LoadDDS: Could not open gfx/shot_normal.dds.
R_LoadTextureEx: Cannot load texture gfx/shot_normal.dds.
LoadDDS: Could not open gfx/shot2.dds.
R_LoadTextureEx: Cannot load texture gfx/shot2.dds.
LoadDDS: Could not open gfx/shot_parallax.dds.
R_LoadTextureEx: Cannot load texture gfx/shot_parallax.dds.
LoadDDS: Could not open gfx/shot_normal.dds.
R_LoadTextureEx: Cannot load texture gfx/shot_normal.dds.
LoadDDS: Could not open gfx/shot3.dds.
R_LoadTextureEx: Cannot load texture gfx/shot3.dds.
LoadDDS: Could not open gfx/shot_parallax.dds.
R_LoadTextureEx: Cannot load texture gfx/shot_parallax.dds.
LoadDDS: Could not open gfx/shot_normal.dds.
R_LoadTextureEx: Cannot load texture gfx/shot_normal.dds.
LoadDDS: Could not open gfx/shot4.dds.
R_LoadTextureEx: Cannot load texture gfx/shot4.dds.
LoadDDS: Could not open gfx/shot_parallax.dds.
R_LoadTextureEx: Cannot load texture gfx/shot_parallax.dds.
LoadDDS: Could not open gfx/shot_normal.dds.
R_LoadTextureEx: Cannot load texture gfx/shot_normal.dds.
LoadDDS: Could not open gfx/shot5.dds.
R_LoadTextureEx: Cannot load texture gfx/shot5.dds.
LoadDDS: Could not open gfx/shot_parallax.dds.
R_LoadTextureEx: Cannot load texture gfx/shot_parallax.dds.
LoadDDS: Could not open gfx/shot_normal.dds.
R_LoadTextureEx: Cannot load texture gfx/shot_normal.dds.

In tandem with this, it would seem the world or parts of the world become completely black, rendering things to a point of unplayability. It also seems to cause much frame lag. Is there something I need to do to correct this? I look forward to seeing your response, and thank you again for the earlier reply; had I known you would be so fast, I would have stood by.

**Comment by hzqst** [comment]
> Hello again wonderful person and thank you; I grabbed the .dll and used the -32bpp parameter and the two errors are gone, the game launched. That said, now I've run into a new error, and am hoping once more that you will assist me. Upon loading a map, in this case c11_a1, this appears in the console.
> 
> setmaster unavailable, start a server first. No detail texture mapping file: maps/hl_c11_a1_detail.txt LoadBaseDictionary: 820 lines are loaded. LoadCustomDictionary: too few lines in the dictionary file. LoadDDS: Could not open gfx/shot1.dds. R_LoadTextureEx: Cannot load texture gfx/shot1.dds. LoadDDS: Could not open gfx/shot_parallax.dds. R_LoadTextureEx: Cannot load texture gfx/shot_parallax.dds. LoadDDS: Could not open gfx/shot_normal.dds. R_LoadTextureEx: Cannot load texture gfx/shot_normal.dds. LoadDDS: Could not open gfx/shot2.dds. R_LoadTextureEx: Cannot load texture gfx/shot2.dds. LoadDDS: Could not open gfx/shot_parallax.dds. R_LoadTextureEx: Cannot load texture gfx/shot_parallax.dds. LoadDDS: Could not open gfx/shot_normal.dds. R_LoadTextureEx: Cannot load texture gfx/shot_normal.dds. LoadDDS: Could not open gfx/shot3.dds. R_LoadTextureEx: Cannot load texture gfx/shot3.dds. LoadDDS: Could not open gfx/shot_parallax.dds. R_LoadTextureEx: Cannot load texture gfx/shot_parallax.dds. LoadDDS: Could not open gfx/shot_normal.dds. R_LoadTextureEx: Cannot load texture gfx/shot_normal.dds. LoadDDS: Could not open gfx/shot4.dds. R_LoadTextureEx: Cannot load texture gfx/shot4.dds. LoadDDS: Could not open gfx/shot_parallax.dds. R_LoadTextureEx: Cannot load texture gfx/shot_parallax.dds. LoadDDS: Could not open gfx/shot_normal.dds. R_LoadTextureEx: Cannot load texture gfx/shot_normal.dds. LoadDDS: Could not open gfx/shot5.dds. R_LoadTextureEx: Cannot load texture gfx/shot5.dds. LoadDDS: Could not open gfx/shot_parallax.dds. R_LoadTextureEx: Cannot load texture gfx/shot_parallax.dds. LoadDDS: Could not open gfx/shot_normal.dds. R_LoadTextureEx: Cannot load texture gfx/shot_normal.dds.
> 
> In tandem with this, it would seem the world or parts of the world become completely black, rendering things to a point of unplayability. It also seems to cause much frame lag. Is there something I need to do to correct this? I look forward to seeing your response, and thank you again for the earlier reply; had I known you would be so fast, I would have stood by.

What is your graphic card?

**Comment by Gillum-Andrew** [comment]
Well, unfortunately I am temporarily bound to my laptop as my desktop's HDD recently died, so I'm using a fairly unimpressive Intel R HD 620. Do you think this is the primary issue?

**Comment by hzqst** [comment]
> Well, unfortunately I am temporarily bound to my laptop as my desktop's HDD recently died, so I'm using a fairly unimpressive Intel R HD 620. Do you think this is the primary issue?

Same issue as #177, should be no problem with Nvidia or AMD card.

**Comment by Gillum-Andrew** [comment]
Sure enough, I seem to be hamstrung by the historically pitiful integrated graphics card of the laptop; I was doing some testing and, even in the base game it doesn't get a consistent 200 fps. I will have to try MetaHookSv on my proper computer when possible, and hopefully all will run smoothly. That said, what of the console errors? The textures seemed to load sometimes in spite of what the console said, while other times they rendered as black boxes and gave off solid black particle clouds.

After this last question is answered, I will probably close the issue. Thank you for being of great assistance, I appreciate it.

**Comment by hzqst** [comment]
> Sure enough, I seem to be hamstrung by the historically pitiful integrated graphics card of the laptop; I was doing some testing and, even in the base game it doesn't get a consistent 200 fps. I will have to try MetaHookSv on my proper computer when possible, and hopefully all will run smoothly. That said, what of the console errors? The textures seemed to load sometimes in spite of what the console said, while other times they rendered as black boxes and gave off solid black particle clouds.
> 
> After this last question is answered, I will probably close the issue. Thank you for being of great assistance, I appreciate it.

Those console errors have nothing to do with your problem. They can be ignored.

**Comment by Gillum-Andrew** [comment]
I see. In that case, noted.

Goodbye wonderful person, and thanks for the help. I apologize for my long delay responding as well. Should I encounter any issues during eventual use on the computer, I will see you again. Have a nice month, fortune be upon you.
