### ISSUE TITLE
Flashlight is drawing stuff when its off

### ISSUE THREAD

**Issue by eFeTRn** [hzqst/MetaHookSv#203]
Flashlight still draws things when it's off.

**Comment by hzqst** [comment]
I don't get it, what do you mean "Flashlight is drawing stuff" ?

**Comment by di57inct** [comment]
He probably means the shadow maps

**Comment by eFeTRn** [comment]
> I don't get it, what do you mean "Flashlight is drawing stuff" ?

I mean, when the when flashlight is turned off, it still draws the world. You can check it by r_light_debug 1.

**Comment by hzqst** [comment]
If you mean the scene painted into s_GBufferFBO.s_hBackBufferTex, this is by-design.

**Comment by eFeTRn** [comment]
Oh, i was thinking that it was a bug. Because when i turn off the flashlight effect using console (r_light_dynamic 0), fps suddenly goes up.
