### ISSUE TITLE
[Renderer] Ragdoll studio models are not rendered after cl_corpse message

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#204]
https://user-images.githubusercontent.com/3608544/193424359-eb47b06c-c611-4934-ba5e-79c366288525.mp4

**Comment by di57inct** [comment]
https://user-images.githubusercontent.com/3608544/193623821-3c23eb28-32e2-4cc1-b577-15bb9ab6c2b7.mp4

**Comment by di57inct** [comment]
https://user-images.githubusercontent.com/3608544/194723497-41ed3c99-68a4-47e4-a316-aec51403beeb.mp4

**Comment by hzqst** [comment]
How to repro the bug?

**Comment by di57inct** [comment]
It seems it only happens on dedicated servers and not always.

**Comment by di57inct** [comment]
Tested. Apparently it happens on older server versions. You can test on cs.evogames.ro and cs.oldgods.ro

**Comment by di57inct** [comment]
Ignore the last 2 replies. Further testing concluded that it's a map based problem. It can be reproduced on fy_snow for example and on both listen and dedicated servers.

**Comment by di57inct** [comment]
Disabling renderer plugin fixes this problem.

**Comment by di57inct** [comment]
Update: neither decals or sprites are drawn too. It seems it's a map zone based problem(probably related to https://github.com/hzqst/MetaHookSv/issues/172 / https://github.com/hzqst/MetaHookSv/commit/4b8c9c27f3edb6773e018d761cbc9ee6f8d6284e fix?). If you go in certain zones, issue is not present. Example:

https://user-images.githubusercontent.com/3608544/217622671-7a574143-946a-4629-b0c1-d5437c5cfc76.mp4

**Comment by hzqst** [comment]
> Update: neither decals or sprites are drawn too. It seems it's a map zone based problem(probably related to #172 / [4b8c9c2](https://github.com/hzqst/MetaHookSv/commit/4b8c9c27f3edb6773e018d761cbc9ee6f8d6284e) fix?). If you go in certain zones, issue is not present. Example:
> 
>  unknown_2023.02.08-20.30_1.mp4

Have you tried latest build?

**Comment by di57inct** [comment]
Yup

https://user-images.githubusercontent.com/3608544/217811314-ac3e7b2b-84cb-4de5-95d5-6eaaa44b1690.mp4

**Comment by di57inct** [comment]
Confirming fix and closing issue.
