### ISSUE TITLE
[BP] Models are converted into ragdolls on wrong frame

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#208]
```
[DeathAnim]
101 14
102 14
103 30
104 5
105 30
106 36
107 5
108 36
109 5
110 5
```

https://user-images.githubusercontent.com/3608544/196475635-0a5219d5-5dd9-418e-a0bf-3d0dd0e2365c.mp4

**Comment by hzqst** [comment]
Can't repro with `GFL_M14-c2_ragdoll.txt`
```
[DeathAnim]
12 128
13 128
14 128
15 128
16 128
17 128
18 128
```

**Comment by di57inct** [comment]
Will try setting bigger frame number and come back after tests.

**Comment by di57inct** [comment]
Works fine with bigger frame number, but the set frame still doesn't match when the ragdoll kicks in. Using latest everything.

https://user-images.githubusercontent.com/3608544/197360425-7dc644d9-5516-48ac-a33d-ab0f35804142.mp4

**Comment by hzqst** [comment]
> 

the frame in _ragdoll.txt is 255-based, you need to convert the frame number into (framenumber * 255 / maxframenumber)

**Comment by di57inct** [comment]
Is there any way you can make it be just a plain number?

**Comment by hzqst** [comment]
> Is there any way you can make it be just a plain number?

frame stores as 255-based floating number in engine. no worth keeping an additional floating convertion at runtime or making a breaking change to _ragdoll.txt.

**Comment by di57inct** [comment]
So specifying frame number and max frame number in the txt file and making the script do the calculation wouldn't be a good idea either?

**Comment by hzqst** [comment]
> So specifying frame number and max frame number in the txt file and making the script do the calculation wouldn't be a good idea either?

That would be a breaking change unless using new section name for example [DeathAnimEx] or [DeathAnim2]

**Comment by di57inct** [comment]
Okay, please close the issue if you think it's not worth changing anything.
