### ISSUE TITLE
视差贴图格式

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#21]
原版
![#youxiceshi0003](https://user-images.githubusercontent.com/68973128/126475367-38d50dab-519f-4c02-825d-b82fb3d3095c.jpg)
视差+法线
![#youxiceshi0002](https://user-images.githubusercontent.com/68973128/126475378-3f05aea8-c88e-4e1b-a954-ad2416ef8f91.jpg)

我刚测试了视差贴图以及法线贴图，法线贴图效果不是很明显，但视差贴图简直太棒了，我想请问都支持什么样的类型图片，我尝试使用了TGA,JPG,不知道是否支持DDS文件？
另外视差贴图是否是后缀为DIFF的贴图？ 你可以告诉我怎么制作他们吗

**Comment by q52888940** [comment]
在某些情况 当我走近某处时 视差纹理好像在蠕动 这正常吗

**Comment by hzqst** [comment]
法线贴图需要动态光源（如手电筒）才能有明显的效果

支持的图片格式包括tga bmp png jpg dds等

视差贴图本身就是欺骗视觉的trick，没让你用放大镜贴着看啊，离太近肯定会露馅的

**Comment by q52888940** [comment]
视差贴图的后缀一般为DIFF吗，我在CSGO里找到了一些
最后衷心希望您能加入置换贴图功能，因为CS贴图限制让我在使用这些视差法线贴图时有些不满足的感觉，或者多加一个插件，希望你能考虑
再次感谢你所做的一切 太令人兴奋

**Comment by hzqst** [comment]
置换贴图需要曲面细分，对硬件和性能要求有点高的

**Comment by q52888940** [comment]
那么我是否能使用VTF贴图


我是说像老版本一样把原帖图更换为更大的贴图，更换模型，天空，纹理,CS最大只有512，这太让我难受了，我想在金源制造更好的效果，甚至想疯狂的给所有官方地图加入法线以及视差贴图

**Comment by hzqst** [comment]
VTF用工具转换成DDS或者其他格式就行了吧

我之前说过了，

> Meta Renderer for Sven-Coop 不再支持一切破解引擎硬编码限制的功能（因为SvEngine本来就会提升这些最大限制），如：允许加载的最大纹理尺寸、最大动态光源数量、最大可见实体数量、lightmap大小限制，以及任何Sven-Coop本身支持的功能，如：3d skybox、镜子等。

**Comment by q52888940** [comment]
好的 问题已解决
另外我是想说 如果可以请您考虑恢复这些功能 当然 只是建议

> 那我是否能使用VTF贴图
> 
> 我是说像老版本一样的把原帖图更换为更好的贴图，更换模型，天空，纹理，CS最大只有512，太让我难受了，我想在金源制造更好的效果，甚至想疯狂的给所有官方地图加入法线以及视差贴图
