### ISSUE TITLE
[Crash] Error when opening metahook

### ISSUE THREAD

**Issue by ollerjoaco** [hzqst/MetaHookSv#210]
Failed to load captionmod/dictionary_%language%.txt

File is there and also not listed in plugins.lst but seems like it tries to load it anyways.

**Comment by hzqst** [comment]
https://github.com/hzqst/MetaHookSv#load-order

**Comment by ollerjoaco** [comment]
Yes, I already saw that and I had only 1 file without Captionmod in it, to be sure I also then created all files that you mentioned there and had no Captionmod in any of these.
By the way I'm using a the newest C's 1.6 versión I think, idk if that can change something.

**Comment by hzqst** [comment]
> Yes, I already saw that and I had only 1 file without Captionmod in it, to be sure I also then created all files that you mentioned there and had no Captionmod in any of these. By the way I'm using a the newest C's 1.6 versión I think, idk if that can change something.

Make sure your `plugin.lst` is right at `\steamapps\common\Half-Life\cstrike\metahook\configs\` not somewhere else and launch game via `cstrike.exe` renamed from `metahook.exe` or `metahook.exe -game cstrike`

**Comment by ollerjoaco** [comment]
My plugins.lst is there but metahook.exe wasn't renamed to cstrike.exe but I used the shortcut you provide that opens metshook.exe -game cstrike. The metahooj.exe I tried to open was the svencoop.exe you had there. Idk if I should have my own metahook.exe from somewhere else or if that's correct.

**Comment by hzqst** [comment]
> My plugins.lst is there but metahook.exe wasn't renamed to cstrike.exe but I used the shortcut you provide that opens metshook.exe -game cstrike. The metahooj.exe I tried to open was the svencoop.exe you had there. Idk if I should have my own metahook.exe from somewhere else or if that's correct.

`metahook.exe -game cstrike` is okay there. you probably went wrong game folder while editing `\metahook\configs\plugins.lst` ?

**Comment by ollerjoaco** [comment]
I didn't understand you well but I have my plugins.lst there in game/cstrike/metahook/configs/plugins.lst 
Plugins are located in game/cstrike/metahook/plugins
I edited almost nothing just deleted the plugins listed in plugins.lst to try not getting this error

**Comment by hzqst** [comment]
> I didn't understand you well but I have my plugins.lst there in game/cstrike/metahook/configs/plugins.lst Plugins are located in game/cstrike/metahook/plugins I edited almost nothing just deleted the plugins listed in plugins.lst to try not getting this error

Do you have multiple instances of cstrike installed on your rig?

**Comment by ollerjoaco** [comment]
I don't know what you mean with rig but I have multiple clients of C's 1.6 in my disk and inside the client I was trying to install it I have cstrike, cstrike_addon, cstrike_hd

**Comment by hzqst** [comment]
> I don't know what do you mean with rig, but I have multiple clients of C's 1.6 in my disk and inside the client I was trying to install it I have cstrike, cstrike_addon, cstrike_hd

I mean you probably open one cstrike client for playing and open another cstrike client for editing metahook configs

**Comment by ollerjoaco** [comment]
Oh no, I only had one instance of the game running at the time . I tried with steam version.
