### ISSUE TITLE
Game crashes when trying to open console

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#211]
The game crashed instantly when I pressed the console button. It seems to happen when having some of the options VGUI drawn.

https://user-images.githubusercontent.com/3608544/197357432-abd6341a-3b87-410d-a13f-a622f8364c43.mp4

**Comment by di57inct** [comment]
Steps to replicate: options -> audio -> subtitles -> open console -> close console(subtitle panel closes) -> open console(or any other vgui item i think)

**Comment by hzqst** [comment]
Should have been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20230102d

**Comment by di57inct** [comment]
Confirming fix for now. Will re-open if necessary. Thank you.
