### ISSUE TITLE
[CM] Subtitle VGUI pannel settings do not save

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#212]
Tried both with hitting apply/ok on main audio VGUI menu and without. All of the options fail to save.

https://user-images.githubusercontent.com/3608544/197357685-424a8c62-dcd2-412a-9d57-be3702758331.mp4

**Comment by qabRieL99** [comment]
Yes, this is true.
Also, there are many more options that could be added to the options page that would ease the process. An option for enabling/disabling the subtitles, linespace, panel color or transparency, text alignment, etc.

**Comment by hzqst** [comment]
This should have been done in https://github.com/hzqst/MetaHookSv/releases/tag/v20240131b

Though I don't have much time to add those cvars into docs.
https://github.com/hzqst/MetaHookSv/blob/48000d09707a7f795a18dae04089c3c3fc35d61e/Plugins/CaptionMod/exportfuncs.cpp#L38
