### ISSUE TITLE
[Renderer] Weird studio model glitch

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#213]
Problem wasn't present on previous version.
Latest update also made the colors brighter(i don't mind that, just reporting).

https://user-images.githubusercontent.com/3608544/198008517-47b89bbf-c468-47d6-aa49-254662dadc76.mp4

**Comment by hzqst** [comment]
try disable r_studio_bone_caches

**Comment by di57inct** [comment]
Seems like it fixes it. So it's a feature glitch?
![Captură de ecran 2022-10-26 142558](https://user-images.githubusercontent.com/3608544/198014485-4ed7fb9a-ae8a-4add-8957-8afd8424c181.png)

**Comment by hzqst** [comment]
Should have been fixed in the latest build, but not tested yet

**Comment by di57inct** [comment]
Confirming fix :)
