### ISSUE TITLE
[Renderer] Some water entities are not hooked

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#215]
For example on fy_pool_day. Video example and screenshots with entity properties from this map and default de_aztec map below.

https://user-images.githubusercontent.com/3608544/198339876-a0636f66-7117-420d-9bdf-2c5e96709d74.mp4

![image](https://user-images.githubusercontent.com/3608544/198340897-4e2a34b6-d9e1-45ed-89eb-dfaa40872fcc.png)
![image](https://user-images.githubusercontent.com/3608544/198340937-acb50e99-9c02-44a8-9d0e-c83ab6fd84b7.png)

**Comment by hzqst** [comment]
Those textures are not started with "!" thus not rendered as water but ordinary transparent surfaces. (client don't know wtf the surface or texture is unless jumps into it)

**Comment by di57inct** [comment]
The water from de_aztec works, the one from fy_pool_day doesn't.
