### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by d3nchk** [hzqst/MetaHookSv#216]
Good afternoon!

For a long time engaged in porting models from cod2019, now finished, and actually all tested and a number of questions arose:

1-All the same is there any approximate time frame for the implementation of normal maps and reflection maps on the models?
1.1-Same question, is it realistic to implement any phong reflections, as in CS Source? There are guns that are ground for chrome, the local implementation of gold src in the form of stretching texture as snot, it is not clear how, and at what angle, looks in 2022 clearly not the best way. As an example, a revolver from hl1, or mp5 from the same, you can clearly assess all the damage.

Next: A whole bunch of performance issues
2 - At least when you apply height maps VERY significantly drops the performance, and enough just use one plane, and add there parralax, and the drop is more than 50%, it's clearly not what I would like to see on a graphics card RX480 class.
With reflection maps, the situation is exactly the same, when you overlay, VERY bad drop in performance. And even reducing reflection map intensity to almost zero doesn't help.
All this has to do with the above techniques PBR, to implement on models in the future, so it is worth polishing these points.
2.1 - Some crazy crap with performance on a number of maps, for example
de_dust2_2020, the map has a fountain, go to him and get -50% to the performance, easily! Need to solve this problem!
On the map de_bank_fix (as optimized map, according to the release), there is a tremendous drop in productivity with 32 players. There are other maps with this problem, there are maps that do not suffer from this ailment. I understand everything, but I'll never understand why I'm lagging in this case, on my set-up. It's not cutting edge, but more than enough for such an ancient game.
Just somehow the default settings for the number of decals, and other things, with 32 players drops performance, the default is 300 units, I had to put 50 to avoid falling performance. I am talking about commands: mp_decals, max_shells, r_decals, cl_corpsestay, max_smokepuffs.
3-The game constantly crashes, randomly, silently, all clear in the logs. I can not figure out what the problem is, but I have already checked everything I could, the only question left is to metahook. I play on NoSteam version, with Goldberg Lan Steam Emu tablet. Online I'm not going to get into, I care about the account. Plus the build is made exclusively for offline play, without any steams and other garbage. Run it and play. In this case, I would like to ask the implementation of any debug mode, with full logging, so you can understand why the game crashes.

The operating system is clean, no hardware problems, fresh drivers. This is to immediately exclude these questions.

Sorry for the rambling narrative, I can do better, but the language barrier, and the use of a translator divides all efforts for naught.

Translated with www.DeepL.com/Translator (free version)

**Comment by hzqst** [comment]
> 1-All the same is there any approximate time frame for the implementation of normal maps and reflection maps on the models?

Maybe when I solve the promance issue?

> 1.1-Same question, is it realistic to implement any phong reflections, as in CS Source? There are guns that are ground for chrome, the local implementation of gold src in the form of stretching texture as snot, it is not clear how, and at what angle, looks in 2022 clearly not the best way. As an example, a revolver from hl1, or mp5 from the same, you can clearly assess all the damage.

Sure, I was planning to replace chrome texture with specular texture with reflection years ago. (however reflection requires additional cubemaps)

> 2 - At least when you apply height maps VERY significantly drops the performance, and enough just use one plane, and add there parralax, and the drop is more than 50%, it's clearly not what I would like to see on a graphics card RX480 class.With reflection maps, the situation is exactly the same, when you overlay, VERY bad drop in performance. And even reducing reflection map intensity to almost zero doesn't help.

Could you please provide the corresponding maps with parralax textures and other resources so I can reproduce the frame drop on my GTX970 rig ?

> 3-The game constantly crashes, randomly, silently, all clear in the logs. I can not figure out what the problem is, but I have already checked everything I could, the only question left is to metahook. I play on NoSteam version, with Goldberg Lan Steam Emu tablet. Online I'm not going to get into, I care about the account. Plus the build is made exclusively for offline play, without any steams and other garbage. Run it and play. In this case, I would like to ask the implementation of any debug mode, with full logging, so you can understand why the game crashes.

I heared from @di57inct that Goldberg Steam Emu sometimes conflicts with metahook but not confirmed.

[Install Visual Studio 2017 or later with msvc toolset](https://github.com/hzqst/MetaHookSv#build-requirements) and [launch game from Visual Studio Debugger](https://github.com/hzqst/MetaHookSv#debugging) to see what cause the crash if you want to dig deeper into it.

**Comment by di57inct** [comment]
Works fine on Goldberg emu, crashes mentioned in private happen on legit Steam version too. It wasn't the emulator's fault.

**Comment by d3nchk** [comment]
> >

Let's take it in order, then.
I will throw in gradually, as now free time is not enough, so do not unsubscribe from the thread, if possible in the near future.

So, the map de_dust2_2020
Map I will attach

I made 2 screenshots 
On the one we can see an example of 150 fps , this is with 32 players and highly polygonal models with textures, is a satisfactory fps, quite, for qhd

But then we come to the very unfortunate fountain
And we see the drop, up to 80-60 fps, the frequency changes rapidly, it is difficult to trace the weighted average fps, but the drop is clearly visible

This is so far the easiest thing to prove
With the rest will take time, later I will try to throw up, I need to understand how to present the result with the imposition of textures

[https://gamebanana.com/dl/546696](url)

**Comment by d3nchk** [comment]
> > 1-All the same is there any approximate time frame for the implementation of normal maps and reflection maps on the models?
> 
> Maybe when I solve the performance issue?
> 
> > 1.1-Same question, is it realistic to implement any phong reflections, as in CS Source? There are guns that are ground for chrome, the local implementation of gold src in the form of stretching texture as snot, it is not clear how, and at what angle, looks in 2022 clearly not the best way. As an example, a revolver from hl1, or mp5 from the same, you can clearly assess all the damage.
> 
> Sure, I was planning to replace chrome texture with specular texture with reflection years ago. (however reflection requires additional cubemaps)
> 
> > 2 - At least when you apply height maps VERY significantly drops the performance, and enough just use one plane, and add there parralax, and the drop is more than 50%, it's clearly not what I would like to see on a graphics card RX480 class.With reflection maps, the situation is exactly the same, when you overlay, VERY bad drop in performance. And even reducing reflection map intensity to almost zero doesn't help.
> 
> Could you please provide the corresponding maps with parralax textures and other resources so I can reproduce the frame drop on my GTX970 rig ?
> 
> > 3-The game constantly crashes, randomly, silently, all clear in the logs. I can not figure out what the problem is, but I have already checked everything I could, the only question left is to metahook. I play on NoSteam version, with Goldberg Lan Steam Emu tablet. Online I'm not going to get into, I care about the account. Plus the build is made exclusively for offline play, without any steams and other garbage. Run it and play. In this case, I would like to ask the implementation of any debug mode, with full logging, so you can understand why the game crashes.
> 
> I heared from @di57inct that Goldberg Steam Emu sometimes conflicts with metahook but not confirmed.
> 
> [Install Visual Studio 2017 or later with msvc toolset](https://github.com/hzqst/MetaHookSv#build-requirements) and [launch game from Visual Studio Debugger](https://github.com/hzqst/MetaHookSv#debugging) to see what cause the crash if you want to dig deeper into it.

Let's take it in order, then.
I will throw in gradually, as now free time is not enough, so do not unsubscribe from the thread, if possible in the near future.

So, the map de_dust2_2020
Map I will attach

I made 2 screenshots
On the one we can see an example of 150 fps , this is with 32 players and highly polygonal models with textures, is a satisfactory fps, quite, for qhd

But then we come to the very unfortunate fountain
And we see the drop, up to 80-60 fps, the frequency changes rapidly, it is difficult to trace the weighted average fps, but the drop is clearly visible

This is so far the easiest thing to prove
With the rest will take time, later I will try to throw up, I need to understand how to present the result with the imposition of textures
[[https://gamebanana.com/dl/546696](https://github.com/hzqst/MetaHookSv/issues/url)](url)
![204267924-b8762c2e-e05f-40da-acca-a0efccd300fe](https://user-images.githubusercontent.com/112010596/204860561-bac776e9-6f1e-40d6-a043-fef1d1ae388c.png)
![204267931-ae4b45f6-53fb-4a24-af6c-d400e2bc5816](https://user-images.githubusercontent.com/112010596/204860568-e9bd20b2-fb2a-4c53-ad2d-dc5f7a2ea26d.png)
