### ISSUE TITLE
Falls out on the desktop on Windows 11

### ISSUE THREAD

**Issue by d3nchk** [hzqst/MetaHookSv#217]
The other day I decided to install the latest version of Windows 11 22h2
I decided here to play, at first the game did not start at all, I updated the build, it was in CaptionMod, most likely.
Then the game at least started, I see the main menu, do the necessary settings, select the map, press load, and at the very end of the game crashes.
I tried to completely remove everything except the game itself and metahook-sv, even removed all of the plugins list, the game seemed to be fully loaded, but ran just a minute, flies out on the desktop.
I'm not entirely sure what it is, maybe amd morons once again broke OpenGL, and maybe the problem is really not working under Windows 11.
Before that I played on Windows Server 2012r2 and everything was ok, well except for occasional random crashes to desktop once per hour, once every 30 minutes. I wrote about it.
Please check what's wrong with it.

**Comment by hzqst** [comment]
it's amd graphic driver that ruined everything.

**Comment by d3nchk** [comment]
> it's amd graphic driver that ruined everything. my Nvidia Geforce 970 works fine so far while Radeon RX 6800 keeps crashing
> 
> please check https://community.amd.com/t5/opengl-vulkan/opengl-user-mode-driver-crash-got-instant-crash-inside/td-p/556169

Yes, the crashes do happen when the -nobindless variable is turned off.
Fuck, AMD management should be executed, how much they can mock the users. They don't do anything. That's decades of complaining about their shitty drivers.

And nvidia are fucking bastards for their pricing policy. I was thinking about getting a brand new graphics card for the New Year, but when I looked at the price of 4080-4090 I nearly died. The mining boom is long behind us, but the prices were inadequate and still are.
My ass is on fire from all this crap.
