### ISSUE TITLE
MSAA无效果

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#22]
当我开启FXAA效果显著，但我把MSAA开到16时我的图像锯齿依然很明显，请检查一下

**Comment by hzqst** [comment]
![image](https://user-images.githubusercontent.com/12287588/126615971-85b07c12-e671-4163-b34c-be146c63aa63.png)

延迟光照即“r_light_dynamic 1”开启时MSAA无法对不透明物体进行抗锯齿操作，这是原理决定的。
