### ISSUE TITLE
Missing model made game crashed

### ISSUE THREAD

**Issue by SonThanhVN** [hzqst/MetaHookSv#220]
when the model is missing and not on any database the game will showing a missing model with red and black flickering repeating made the GPU out of VRAM and crashed

**Comment by hzqst** [comment]
Sorry I don't get it, what do you mean missing model? Is this what you were talking about?
![image](https://user-images.githubusercontent.com/12287588/210199202-b5666fb9-ad2b-407e-8433-36c4b55819c4.png)

**Comment by SonThanhVN** [comment]
it look like this
https://streamable.com/zij9we

**Comment by hzqst** [comment]
> it look like this https://streamable.com/zij9we

It seems to be a model with "[modelname]T.mdl" (aka. external studio texture) missing. the SCModelDownloader failed to fetch "[modelname]T.mdl" from scmodel database due to filename case sensitive problem or what.

**Comment by hzqst** [comment]
I made a quick patch to the model texture loading procedure: https://github.com/hzqst/MetaHookSv/releases/tag/v20230102
Should be okay with ioaf_longcyber.mdl
