### ISSUE TITLE
Crash with latest version of AMD drivers (22.11.2)

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#223]
Game sometimes crashes on launch and always when joining/creating a server.
Disabling renderer fixes the last part.
EDIT: happens the same on previous versions too(tested with 03.12.2022)

**Comment by hzqst** [comment]
Probably same issue as https://github.com/hzqst/MetaHookSv/issues/195, AMD has not released the fix on the latest driver update yet.

**Comment by di57inct** [comment]
Closing as duplicate.
