### ISSUE TITLE
Raw Mouse Input to the right is capped

### ISSUE THREAD

**Issue by Zaphero1** [hzqst/MetaHookSv#225]
For whatever reason the raw mouse input seems to have a cap because after some amount of mouse movement to the right, it will just hard stop and all you can do is spin the other way. This does not seem to be an issue with Raw Mouse Input off. Found it in Half-Life base campaign.

**Comment by hzqst** [comment]
sorry but I can't repro your issue, could you try disabling all plugins in `(GameDirectory)\metahook\configs\plugins_goldsrc.lst` and see if the issue is mitigated?

**Comment by Zaphero1** [comment]
You might need to correct me on how you disable them, but I've deleted and saved the contents of both those files and the issue remains.

**Comment by hzqst** [comment]
> You might need to correct me on how you disable them, but I've deleted and saved the contents of both those files and the issue remains.

You can disable plugins by removing lines from .lst file but it seems it's not working for you. could you please give it a try that rename `metahook.exe` to `hl.exe` (don't forget to backup the original one) and run game from the renamed one?

**Comment by Zaphero1** [comment]
Ahhh that did fix it, but revealed the conundrum. It works if I don't apply DPI compatibility scaling, but if I don't do that then the menus are just broken from the font scaling. Overriding high DPI scaling behavior performed by Application does nothing and System (Enhanced) makes the game not display at all, but just System fixes the scaling problem... and introduces raw mouse input to the right getting capped.
![image](https://user-images.githubusercontent.com/19298996/211471720-434be7c8-8934-43ac-8fec-cdabf36770fb.png)

**Comment by hzqst** [comment]
try https://github.com/hzqst/MetaHookSv/releases/tag/v20230110b

**Comment by Zaphero1** [comment]
Yeah that fixes the Menu UI scaling for me to be just like vanilla Half-Life 1 and Opposing Force, so I don't need to apply the compatibility option and I can move my mouse freely! I don't know how that will affect the UI on other monitors, but thank you very much!
