### ISSUE TITLE
[Request] Half-Life - Full Audio Remaster Support

### ISSUE THREAD

**Issue by Zaphero1** [hzqst/MetaHookSv#228]
The mod for higher quality audio uses Sven-Coop to work (or optionally Xash3D), and is set up to be launched as an add on from there. Can this audio be dropped into MetaHookSv? If so, could you make a guide on how to add it in?
https://www.moddb.com/addons/half-life-full-audio-remaster

**Comment by hzqst** [comment]
Are you looking for this : https://github.com/LAGonauta/MetaAudio ?

**Comment by Zaphero1** [comment]
> Are you looking for this : https://github.com/LAGonauta/MetaAudio ?

Oh no that's different; the Full Audio Remaster replaces the original audio files with higher quality ones rather than changing the sound engine.
https://www.youtube.com/watch?v=5Vh1UkCPXLA
