### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#229]
又是一年没来 没想到更新那么多
1.在cs中 当打击地面时"GUNSMOKE"没了 就是在CS中打地面会冒烟 枪管也会冒烟
2.现在可以在CS中替换地图纹理了吗？ 我看弹孔的印花被替换了
3.我的cs因为修改了玩家的视角高度 随之模型也被增大了1.2倍 所以在布娃娃时会有一些bug 请问布娃娃该怎么写 我实在时没搞懂 因为我服务器中的人物模型为csol的。。

**Comment by q52888940** [comment]
另外印花是可以替换为有法线贴图的吗？

**Comment by q52888940** [comment]
视频中的高级设置选项没有了在CS中 不知道这是不是新改动？

**Comment by q52888940** [comment]
最重要的问题是我基本上看不到雪的天气效果了，如果在地图里加入了env_SNOW正常来说应该可以看到雪的 但现在无法看到下雪的spr了

**Comment by hzqst** [comment]
> 1.在cs中 当打击地面时"GUNSMOKE"没了 就是在CS中打地面会冒烟 枪管也会冒烟

> 最重要的问题是我基本上看不到雪的天气效果了，如果在地图里加入了env_SNOW正常来说应该可以看到雪的 但现在无法看到下雪的spr了

试试https://github.com/hzqst/MetaHookSv/releases/tag/v20230117a

> 视频中的高级设置选项没有了在CS中 不知道这是不是新改动？

![image](https://user-images.githubusercontent.com/12287588/212806953-1acef8f4-b639-4151-9508-676541b984e7.png)

↑这个不是？

> 另外印花是可以替换为有法线贴图的吗？

参考/`mod_directory`/renderer/decal_textures.txt，格式跟细节纹理也就是https://github.com/hzqst/MetaHookSv/blob/main/RendererCN.md#%E7%BB%86%E8%8A%82%E8%B4%B4%E5%9B%BE中描述的一样

> 3.我的cs因为修改了玩家的视角高度 随之模型也被增大了1.2倍 所以在布娃娃时会有一些bug 请问布娃娃该怎么写 我实在时没搞懂 因为我服务器中的人物模型为csol的。。

CS1.6还支持在不修改mdl文件的情况下对模型进行缩放？

**Comment by q52888940** [comment]
新年好新年好
关于布娃娃的我有点解释错误不要在意，主要是想问您能否有空闲为csol女角色骨骼写一个布娃娃文件？
另外我用的cs零点行动测试 依然看不到高级选项...

现在除了可以替换贴花 还可以替换其他的吗？ 如地图纹理模型纹理这些支持吗

**Comment by hzqst** [comment]
> 新年好新年好 关于布娃娃的我有点解释错误不要在意，主要是想问您能否有空闲为csol女角色骨骼写一个布娃娃文件？ 另外我用的cs零点行动测试 依然看不到高级选项...


零点行动：
![image](https://user-images.githubusercontent.com/12287588/212835010-11c01c82-0a54-46fd-ae9d-e73113265b4e.png)

（`\Build\valve\resource\OptionsSubAudio.res`覆盖到`Half-Life\czero\resource\OptionsSubAudio.res`，`\Build\valve\resource\OptionsSubVideo.res`覆盖到`Half-Life\czero\resource\OptionsSubVideo.res`才能生效，具体可以参考`install-to-ConditionZero.bat`等批处理安装方式）

> 现在除了可以替换贴花 还可以替换其他的吗？ 如地图纹理模型纹理这些支持吗

替换模型纹理参考https://github.com/hzqst/MetaHookSv/blob/main/Renderer.md#studiomodel-texture-replacer 和 https://github.com/hzqst/MetaHookSv/issues/81
替换地图纹理参考https://github.com/hzqst/MetaHookSv/blob/main/Renderer.md#brush-texture-replacer 和

**Comment by hzqst** [comment]
gunsmoke的问题试试https://github.com/hzqst/MetaHookSv/releases/tag/v20230118c
