### ISSUE TITLE
Enabling MetaAudio.dll breaks CaptionMod

### ISSUE THREAD

**Issue by Zaphero1** [hzqst/MetaHookSv#230]
Whenever I enable metaaudio.dll, CaptionMod breaks so that no subtitles are displayed at all. Without a fix or setting it seems like there's not a way to play with the Full Audio Remaster and subtitles.

https://github.com/LAGonauta/MetaAudio/issues/50

**Comment by hzqst** [comment]
DO NOT replace `metahook.exe` if you have installed MetaHookSv launcher before. 
or MAKE SURE MetaHookSv is installed after MetaAudio if MetaAudio was installed from `.bat`. 
and MAKE SURE `[mod_directory]/metahook/configs/plugins.lst` loads all the plugins you want.

**Comment by Zaphero1** [comment]
Oh yeah I figured that. I made sure to just take out the dlls, put them where they should be; OpenAL, libsndfile-1, and alure2 are in the base game folder while MetaAudio.dll is in valve/metahook/plugins and gearbox/metahook/plugins, and added metaaudio.dll to plugins.lst and plugins_goldsrc.lst and tried removing it from plugins_goldsrc.lst. The Remastered audio is playing when I add it in, but the subtitles don't show up unless i delete metaaudio.dll from plugins.lst
![image](https://user-images.githubusercontent.com/19298996/212867628-7737ff20-abbb-45fc-a2bb-f1e94f144d18.png)

**Comment by hzqst** [comment]
try adjust the load order :
![image](https://user-images.githubusercontent.com/12287588/212909846-992050be-8f5f-4ee9-a672-b4cc93386376.png)

**Comment by Zaphero1** [comment]
Unfortunately it's still broken when I put it first in the load order in `plugins.lst` or both `plugins.lst` and `plugins_goldsrc.lst`. The subtitles do play when I only put it first in `plugins_goldsrc.lst`, but that's because MetaAudio isn't working.
![20230117125930_1](https://user-images.githubusercontent.com/19298996/212988893-b2da388b-10c6-4fcb-bc57-a2ee598e647c.jpg)
![image](https://user-images.githubusercontent.com/19298996/212987067-afc4ebe5-cd16-4c4d-9f54-ac1a40c9687d.png)
![20230117125736_1](https://user-images.githubusercontent.com/19298996/212988967-75d7115b-0e01-4803-95f0-8e61021a8d3f.jpg)

**Comment by hzqst** [comment]
This should fix the issue : [v20230118b](https://github.com/hzqst/MetaHookSv/releases/tag/v20230118b)

**Comment by Zaphero1** [comment]
WOO! Looks like it did! Thank you very much.
![image](https://user-images.githubusercontent.com/19298996/213085959-5935ee1e-9ec0-4eee-ad59-178c438ef984.png)
