### ISSUE TITLE
model贴图替换问题

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#231]
![9DJJ8@J`4ZO 45 SP$6MHXI](https://user-images.githubusercontent.com/68973128/212932969-60aa3a64-9c93-4e67-bec8-428ac08477d0.png)

**Comment by q52888940** [comment]
另外gunsmoke对比原版很不明显 可以说还是基本看不到。。

**Comment by hzqst** [comment]
> Uploading weapon.zip… 无论我怎么调整比例替换后贴图都是脏乱的
> 
> 原模型 ![%EDMT@C(@RB5{BOFDT)5T{U](https://user-images.githubusercontent.com/68973128/212933386-a6edc677-d5a3-4573-9d68-e905f2e5c53c.png)

文件没传上来

**Comment by q52888940** [comment]
[weapon.zip](https://github.com/hzqst/MetaHookSv/files/10437475/weapon.zip)

**Comment by hzqst** [comment]
scale填0.5

**Comment by q52888940** [comment]
你这个写法我尝试过 依然是乱码 刚才又试了一遍 还是乱的。。

**Comment by hzqst** [comment]
> 你这个写法我尝试过 依然是乱码 刚才又试了一遍 还是乱的。。

不行就去试试https://github.com/hzqst/MetaHookSv/releases/tag/v20230118d，不要加replacescale那行

**Comment by q52888940** [comment]
成功 已解决
