### ISSUE TITLE
目前是否可以更换天空盒？

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#233]
注意到现在有了模型贴图置换功能，那么在cs中是否像以前一样可以置换天空图片以及像从前的3d天空盒子功能等

顺便一提，你是否会为csol女角色骨骼编写一份布娃娃文件（这只是个人请求 可以忽略）

**Comment by hzqst** [comment]
Solved in 
https://github.com/hzqst/MetaHookSv/blob/main/docs/Renderer.md#detail-sky-textures
https://github.com/hzqst/MetaHookSv/blob/main/docs/RendererCN.md#%E9%AB%98%E6%B8%85%E5%A4%A9%E7%A9%BA%E8%B4%B4%E5%9B%BE
