### ISSUE TITLE
 r_shadow_distfade

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#234]
] r_shadow_distfade 64 128
R_CvarSetMapCvar: Failed to parse map cvar for r_shadow_distfade

**Comment by hzqst** [comment]
参数包含空格时应使用引号将参数括起来
r_shadow_distfade "64 128"

**Comment by q52888940** [comment]
r_shadow_distfade这个参数不能设置最大阴影距离吗？
r_shadow_distfade "9999999 99999999"
阴影依然在一定距离淡出
