### ISSUE TITLE
[Renderer] Opposing Force Window too Opaque to see GMan with the bomb

### ISSUE THREAD

**Issue by Zaphero1** [hzqst/MetaHookSv#236]
In the the chapter The Package this might just be a natural consequence of this window having a light shining on it from above right outside or the interior being more lit than the exterior. Whatever the case, if you turn on MetaRenderer you can't see through this window delivering a pretty important story detail, and there doesn't seem to be a way to tweak it. I hope this is something that doesn't take editing the map to fix.
Default Renderer:
![20230123050927_1](https://user-images.githubusercontent.com/19298996/214026504-8e1550f2-1505-4734-8036-2635e4cc5e3b.jpg)

MetaRenderer
![20230123050842_1](https://user-images.githubusercontent.com/19298996/214026537-1edbb469-27a8-43a0-94d4-860fd1ae89cf.jpg)

**Comment by hzqst** [comment]
Solved with r_gamma_blend 1.
