### ISSUE TITLE
[Bug]近期的新版本文件有问题

### ISSUE THREAD

**Issue by 7UMENGL1aNG** [hzqst/MetaHookSv#239]
![image](https://user-images.githubusercontent.com/97338615/216757459-b1acf00d-0213-4eeb-a145-a897f0dd79eb.png)
### 一是汉化失效
![image](https://user-images.githubusercontent.com/97338615/216757469-088d622b-f6b6-40fe-af8a-576dd6097aac.png)
### 二是图像选项失效

---

再是进游戏之后确实是全部失效了。

安装方式：同以前一样，把Build文件夹覆盖进Svencoop。
在之前的版本能成功，近期的版本确认该方式无效。

**Comment by 7UMENGL1aNG** [comment]
使用install-to-SvenCoop.bat安装。
成功。
![image](https://user-images.githubusercontent.com/97338615/216757846-eea2e8d9-bb88-4ef9-a92b-ee936f02958e.png)
推测：
Build中SvenCoop.exe文件放错了

**Comment by hzqst** [comment]
文档已更新：https://github.com/hzqst/MetaHookSv/blob/main/READMECN.md#%E6%89%8B%E5%8A%A8%E5%AE%89%E8%A3%85%E6%96%B9%E5%BC%8F

**Comment by 7UMENGL1aNG** [comment]
> 

提醒一下：
```
SDL2.dll文件是用来修复原版SDL使用中文输入法进行游戏时可能发生的内存越界写入导致游戏崩溃的问题。如果你全程都关闭中文输入法的话也可以选择不替换SDL2.dll。
当然，你也可以从Steam根目录（默认位置C:\Program Files (x86)\Steam）复制SDL2.dll，效果是完全一样的。
```
我现在STEAM文件中已经没有SDL2了，是SDL3。
