### ISSUE TITLE
[Renderer] calc lightstyle sampled color in shader

### ISSUE THREAD

**Issue by hzqst** [hzqst/MetaHookSv#243]

**Comment by di57inct** [comment]
Related? Or should I create a separate issue?

https://user-images.githubusercontent.com/3608544/217814580-f3523b0c-e767-4a86-a54f-7d61ca1097fa.mp4

**Comment by di57inct** [comment]
Nevermind, seems it also happens in vanilla version. Please ignore :d

**Comment by hzqst** [comment]
Closed as finished
