### ISSUE TITLE
[Renderer] collect waters at map init

### ISSUE THREAD

**Issue by hzqst** [hzqst/MetaHookSv#244]

**Comment by di57inct** [comment]
Does this fix https://github.com/hzqst/MetaHookSv/issues/215 by any chance?

**Comment by hzqst** [comment]
> Does this fix #215 by any chance?

Nah, the "water" in fy_pool_day is literally counted as ordinalry transparent brush instead of water in engine.

**Comment by di57inct** [comment]
No workaround possible?
