### ISSUE TITLE
g_iVisibleMouse crash

### ISSUE THREAD

**Issue by NukeThief** [hzqst/MetaHookSv#247]
![image](https://user-images.githubusercontent.com/81801547/218158568-d9b25f63-21d3-447f-8161-643bd4003eb8.png)
idk what the heck should i do

**Comment by eFeTRn** [comment]
Try -bindless in launch options

**Comment by hzqst** [comment]
Which mod are you running?

**Comment by NukeThief** [comment]
> Which mod are you running?

Only metaaudio.

**Comment by hzqst** [comment]
> > Which mod are you running?
> 
> Only metaaudio.

I mean "valve", "gearbox", "cstrike", "bshift", or what.

**Comment by NukeThief** [comment]
> > > Which mod are you running?
> 
> > 
> 
> > Only metaaudio.
> 
> 
> 
> I mean "valve" (Half-Life), "gearbox" (opfor), "cstrike" (Counter Strike), "bshift" (Blue Shift), or what.

then it's valve.

**Comment by hzqst** [comment]
> > > > Which mod are you running?
> > 
> > 
> > > 
> > 
> > 
> > > Only metaaudio.
> > 
> > 
> > I mean "valve" (Half-Life), "gearbox" (opfor), "cstrike" (Counter Strike), "bshift" (Blue Shift), or what.
> 
> then it's valve.

Did you replace vanilla Half-Life's client dll (\valve\cl_dlls\client.dll) with other third-party one such as AG or HLBugFix or what?

**Comment by NukeThief** [comment]
oh yea, i did with a beta hl2 hud mod client.dll, it's in valve_addons, so deleting it wouldn't be a problem.

**Comment by hzqst** [comment]
> > > > > > Which mod are you running?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > Only metaaudio.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I mean "valve" (Half-Life), "gearbox" (opfor), "cstrike" (Counter Strike), "bshift" (Blue Shift), or what.
> > 
> > 
> > > 
> > 
> > 
> > > then it's valve.
> > 
> > 
> > Did you replace vanilla Half-Life's client dll (\valve\cl_dlls\client.dll) with other third-party one such as AG or HLBugFix or what?
> 
> oh yea, i did with a beta hl2 hud mod client.dll, it's in valve_addons, so deleting it wouldn't be a problem.

So there's a confliction between `CaptionMod.dll` and `client.dll` from "beta hl2 hud". You can either remove `CaptionMod.dll` or   "beta hl2 hud" to mitigate the problem.

**Comment by NukeThief** [comment]
> > > > > > > Which mod are you running?
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > Only metaaudio.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > I mean "valve" (Half-Life), "gearbox" (opfor), "cstrike" (Counter Strike), "bshift" (Blue Shift), or what.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > then it's valve.
> 
> > > 
> 
> > > 
> 
> > > Did you replace vanilla Half-Life's client dll (\valve\cl_dlls\client.dll) with other third-party one such as AG or HLBugFix or what?
> 
> > 
> 
> > oh yea, i did with a beta hl2 hud mod client.dll, it's in valve_addons, so deleting it wouldn't be a problem.
> 
> 
> 
> So there's a confliction between `CaptionMod.dll` and `client.dll` from "beta hl2 hud". You can either remove `CaptionMod.dll` or   "beta hl2 hud" to mitigate the problem.

hang on let me check if that is the case.

**Comment by NukeThief** [comment]
> > > > > > > Which mod are you running?
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > Only metaaudio.
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > I mean "valve" (Half-Life), "gearbox" (opfor), "cstrike" (Counter Strike), "bshift" (Blue Shift), or what.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > then it's valve.
> > > 
> > > 
> > > Did you replace vanilla Half-Life's client dll (\valve\cl_dlls\client.dll) with other third-party one such as AG or HLBugFix or what?
> > 
> > 
> > oh yea, i did with a beta hl2 hud mod client.dll, it's in valve_addons, so deleting it wouldn't be a problem.
> 
> So there's a confliction between `CaptionMod.dll` and `client.dll` from "beta hl2 hud". You can either remove `CaptionMod.dll` or "beta hl2 hud" to mitigate the problem.

after removing caption mod, i'm having this crash:
![image](https://user-images.githubusercontent.com/81801547/218299941-18971fe4-fde0-433b-8d66-15db4eb6634f.png)

**Comment by hzqst** [comment]
> > > > > > > > Which mod are you running?
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > > Only metaaudio.
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > I mean "valve" (Half-Life), "gearbox" (opfor), "cstrike" (Counter Strike), "bshift" (Blue Shift), or what.
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > then it's valve.
> > > > 
> > > > 
> > > > Did you replace vanilla Half-Life's client dll (\valve\cl_dlls\client.dll) with other third-party one such as AG or HLBugFix or what?
> > > 
> > > 
> > > oh yea, i did with a beta hl2 hud mod client.dll, it's in valve_addons, so deleting it wouldn't be a problem.
> > 
> > 
> > So there's a confliction between `CaptionMod.dll` and `client.dll` from "beta hl2 hud". You can either remove `CaptionMod.dll` or "beta hl2 hud" to mitigate the problem.
> 
> after removing caption mod, i'm having this crash: ![image](https://user-images.githubusercontent.com/81801547/218299941-18971fe4-fde0-433b-8d66-15db4eb6634f.png)

okay so you have to remove beta hl2 hud as it conflicts with more than one plugin.

**Comment by NukeThief** [comment]
> > > > > > > > > Which mod are you running?
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > > Only metaaudio.
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > I mean "valve" (Half-Life), "gearbox" (opfor), "cstrike" (Counter Strike), "bshift" (Blue Shift), or what.
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > 
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > then it's valve.
> 
> > > > > 
> 
> > > > > 
> 
> > > > > Did you replace vanilla Half-Life's client dll (\valve\cl_dlls\client.dll) with other third-party one such as AG or HLBugFix or what?
> 
> > > > 
> 
> > > > 
> 
> > > > oh yea, i did with a beta hl2 hud mod client.dll, it's in valve_addons, so deleting it wouldn't be a problem.
> 
> > > 
> 
> > > 
> 
> > > So there's a confliction between `CaptionMod.dll` and `client.dll` from "beta hl2 hud". You can either remove `CaptionMod.dll` or "beta hl2 hud" to mitigate the problem.
> 
> > 
> 
> > after removing caption mod, i'm having this crash: ![image](https://user-images.githubusercontent.com/81801547/218299941-18971fe4-fde0-433b-8d66-15db4eb6634f.png)
> 
> 
> 
> okay so you have to remove beta hl2 hud as it conflicts with more than one plugin.

now it's working! maybe i have to make a custom dll for this hud that supports the hud but keeps the dll like steam hl1? ill have to try someday.

**Comment by NukeThief** [comment]
on a side note? why does my game blink after a loading screen?

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/issues/280
