### ISSUE TITLE
[Renderer] WATER_LEVEL_LEGACY_RIPPLE breaks the water rendering

### ISSUE THREAD

**Issue by Zaphero1** [hzqst/MetaHookSv#251]
Anytime I set level to "WATER_LEVEL_LEGACY_RIPPLE", the water renders as a black void instead.

![20230222125119_1](https://user-images.githubusercontent.com/19298996/220730919-64fa1bad-ccc5-48df-bb8e-9033a52ce84d.jpg)
![20230222125117_1](https://user-images.githubusercontent.com/19298996/220730928-b7fa6fda-99df-48d0-b3bf-4b0c8886dc20.jpg)

![image](https://user-images.githubusercontent.com/19298996/220731602-39916793-b43a-4cd0-ae15-583dd543740b.png)

[default_entity.txt](https://github.com/hzqst/MetaHookSv/files/10807347/default_entity.txt)
[Save at water.zip](https://github.com/hzqst/MetaHookSv/files/10807383/Save.at.water.zip)

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20230918c

Used parameters:
```
{
"classname" "env_water_control"
"basetexture" "*"
"speedrate" "1000.0"
"level" "WATER_LEVEL_LEGACY_RIPPLE"
}
```

https://github.com/hzqst/MetaHookSv/assets/12287588/97a77788-e75a-49bb-9cd0-44106196532f
