### ISSUE TITLE
[Issue] Medic!, Take Cover, Gibs don't are invisible in latest version

### ISSUE THREAD

**Issue by ClifffordW** [hzqst/MetaHookSv#253]
The popups that appear above your head like Medic and Take cover are no longer visible and gibs either nor any other particles from player,

**Comment by hzqst** [comment]
Can't repro the issue with latest build.

What's your `Renderer.dll` version ? check with console command `mh_pluginlist`

**Comment by ClifffordW** [comment]
i rolled back to older version which works 
2023-02-07 T13:01:06

**Comment by hzqst** [comment]
This happened only after first level change

Should have been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20230226d
