### ISSUE TITLE
[BP] Ragdolls don't collide with func_breakable interior and invisible func_wall/func_illusionary

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#256]
Probably related to https://github.com/hzqst/MetaHookSv/issues/160 / https://github.com/hzqst/MetaHookSv/commit/257a788f03b8d363b85903434ba33f117fbc299f

https://user-images.githubusercontent.com/3608544/221588689-f993e76d-1edd-416e-85ce-fbdda60bd5ca.mp4

EDIT: notice in the following clips that it collides with the walls of the func_breakable but not the interior too(which is all solid)

https://user-images.githubusercontent.com/3608544/221597204-6c9725e4-2b84-4537-b57b-2687a848789c.mp4

https://user-images.githubusercontent.com/3608544/221597245-016a5f57-6e04-4de2-aa6a-804c7eb31966.mp4

**Comment by di57inct** [comment]
Got it. If it's possible to make ragdolls collide with invisible/non-textured meshes please do it. Since alive players collide with them(like the example shown in the fy_snow map clip), it would make sense for ragdolls to do the same. Thanks.

**Comment by hzqst** [comment]
Impossible to fix due to BSP's node-based collision mechanism.
