### ISSUE TITLE
[CM] Dictionary Case Sensitivity causing some subtitles to not play

### ISSUE THREAD

**Issue by Zaphero1** [hzqst/MetaHookSv#259]
I've been subtitling/captioning Half-Life Echoes and I ran into a problem where a line's subtitle would not play ingame despite a line for it being in the dictionary.csv spreadsheet with a subtitle in dictionaryenglish.txt. I couldn't figure out what was going on until I checked the mod's sentences.txt and found that the filename's first letter was capitalized.
![image](https://user-images.githubusercontent.com/19298996/223659374-efe9a8a8-d2e2-4ff1-ab77-2acf8beefe74.png)
Once I changed the filename in the database to match its case it worked.
![image](https://user-images.githubusercontent.com/19298996/223659834-2b1e7797-cd98-40c5-a899-e59b8e6c93f4.png)

So CaptionMod's filename case sensitivity doesn't seem to match Goldsrc, and it currently takes a workaround to fix it.

**Comment by hzqst** [comment]
This is by design.

The "filename" in `directory.csv` is literally a symbol name to identifty a unique subtitle instead of the real filename in the underlying OS filesystem, 
 and the case-insensitivity of the filename is provided by Windows NTFS thus you can even disable the case-insensitivity (or called enable the case-sensitivity) in Windows 11 (tho ofc it's disabled by default)

**Comment by Zaphero1** [comment]
If I understand this correctly, it doesn't seem to be matching the case sensitivity of Windows. Neither the folder of the file nor the folder of the dictionary are set to be case sensitive according to powershell, but the filename in dictionary.csv has to match the case of the sound effect as listed in sentences.txt to play.
![image](https://user-images.githubusercontent.com/19298996/223672512-1bc79a01-f6c4-402a-9ab1-f828d1293864.png)
Like here's an example of the error ingame:
![image](https://user-images.githubusercontent.com/19298996/223673030-7ad4b604-7672-49a5-8eeb-5b714eb9521e.png)
![image](https://user-images.githubusercontent.com/19298996/223673652-511020f2-8715-4ad5-90f1-6f7b39aa0c31.png)

**Comment by hzqst** [comment]
> If I understand this correctly, it doesn't seem to be matching the case sensitivity of Windows. Neither the folder of the file nor the folder of the dictionary are set to be case sensitive according to powershell, but the filename in dictionary.csv has to match the case of the sound effect as listed in sentences.txt to play. ![image](https://user-images.githubusercontent.com/19298996/223672512-1bc79a01-f6c4-402a-9ab1-f828d1293864.png) Like here's an example of the error ingame: ![image](https://user-images.githubusercontent.com/19298996/223673030-7ad4b604-7672-49a5-8eeb-5b714eb9521e.png) ![image](https://user-images.githubusercontent.com/19298996/223673652-511020f2-8715-4ad5-90f1-6f7b39aa0c31.png)

The "filename" in `sentences.txt` is a case-sensitive symbol name too just like what it was in `dictionary.csv`.

**Comment by Zaphero1** [comment]
That fixed it! Thank you very much!
![image](https://user-images.githubusercontent.com/19298996/224856535-e7cbca15-da5f-40cc-927e-eb0d9c0da85c.png)
![image](https://user-images.githubusercontent.com/19298996/224856684-ce3728fb-0067-498f-8808-8baa25f09bb3.png)
![image](https://user-images.githubusercontent.com/19298996/224856857-84ca4314-6476-4e80-8535-d56562522629.png)
