### ISSUE TITLE
无线电字幕不支持中文

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#26]
![E1ZJ4I_FU0D0VVFNFF2 @NH](https://user-images.githubusercontent.com/68973128/126708798-4ecc266f-ca1d-4c04-aeb0-2d8035fed348.png)
在玩家名称为中文时变为乱码

**Comment by hzqst** [comment]
![image](https://user-images.githubusercontent.com/12287588/126735351-1c4c2ebb-1575-4e73-93f1-f9e370a75c01.png)
![image](https://user-images.githubusercontent.com/12287588/126735360-87635d1c-6f87-48f8-bdb4-265d920df3d2.png)
