### ISSUE TITLE
[ QN ] Does it change to compile an old Metahook plugin in this new version? 

### ISSUE THREAD

**Issue by ollerjoaco** [hzqst/MetaHookSv#260]
Hi, I wanted to know if there is any difference in compiling an old MetaHook nagist plugin with MetaHookSv, does this enhance in some way the plugin? I have Trinity Engine for Metahook but when trying to compile it with MetaHookSv files instead of nagist one some errors shows up. In the case it changes nothing I´m not going to loose my time hahaha but I understand the plugins I have are with api v2 and MetahookSv has api v4 probably with some major changes to the plugin loading? Let me know and thanks in advance.

**Comment by hzqst** [comment]
So, where are the errors?

**Comment by ollerjoaco** [comment]
But does it change in some way the plugin? Is it worth to compile it with MetaHookSv files instead of old nagist metahook ones?
Thats my question.

**Comment by hzqst** [comment]
> But does it change in some way the plugin? Is it worth to compile it with MetaHookSv files instead of old nagist metahook ones? Thats my question.

No worth if you don't need those new api sets e.g DisasmRanges or ReverseSearchFunction

**Comment by ollerjoaco** [comment]
Okey thanks
