### ISSUE TITLE
在加载了RegameDLL的情况下游玩CZ会闪退和出现模型错误

### ISSUE THREAD

**Issue by cassualter226** [hzqst/MetaHookSv#262]
打bot，从800块的手枪局开始打，等到游戏的第3或第4局开局买枪阶段时，只要选择M4A1就会闪退。如果第一、第二回合就得到了M4A1，V模就会出现模型错误，主要就是缺面和贴图错乱。V模是游戏本体默认的，没有替换。游戏本体为steam正版，挂载SSE运行，开启了布娃娃特效和其他的渲染特效。
盲猜可能是现阶段MetaHookSv对RegameDLL不兼容的原因，不过如果有暂时的解决方案的话，可以试试看。
![de_dust20000](https://user-images.githubusercontent.com/106251070/224534050-1393f78e-b076-4642-b90d-c3fc90c9e149.jpg)
![de_dust200080](https://user-images.githubusercontent.com/106251070/224559692-c6e97a13-7ff0-46ed-8a5b-ae7147054158.jpg)

**Comment by hzqst** [comment]
试下禁用r_studio_bone_caches

`r_studio_bone_caches 0`

**Comment by cassualter226** [comment]
> 试下禁用r_studio_bone_caches
> 
> `r_studio_bone_caches 0`
> 
> (但是[regamedll](https://github.com/s1lentq/ReGameDLL_CS)不是只替换服务端mp.dll么？只进别人的服务器应该根本不加载服务端吧，怎么可能出问题呢)

刚才试过了，steam正版输入了这个命令，获取到M4时会闪退......
其实你也可以试一下，如果你那边没有什么问题，可能是我电脑的运行库什么的有问题也说不定呢？
emmmmm......这个问题修复之前还是用回原版的mp.dll吧，其实用regamedll也只是为了几个错误修复和512限定解除，错误修复可以用amxx插件应付一下，512限制的话。。。这个版本的mh应该也有绕过限制的功能吧？

**Comment by hzqst** [comment]
> > 试下禁用r_studio_bone_caches
> > `r_studio_bone_caches 0`
> > (但是[regamedll](https://github.com/s1lentq/ReGameDLL_CS)不是只替换服务端mp.dll么？只进别人的服务器应该根本不加载服务端吧，怎么可能出问题呢)
> 
> 刚才试过了，steam正版输入了这个命令，获取到M4时会闪退，挂载SmartSteamEmulator的版本亦然...... 其实你也可以试一下，如果你那边没有什么问题，可能是我电脑的运行库什么的有问题也说不定呢？ emmmmm......这个问题修复之前还是用回原版的mp.dll吧，其实用regamedll也只是为了几个错误修复和512限定解除，错误修复可以用amxx插件应付一下，512限制的话。。。这个版本的mh应该也有绕过限制的功能吧？

1.precache limit由引擎决定，引擎是hw.dll和swds.dll，跟mp.dll有什么关系？regamedll也就是mp.dll只负责处理服务端的游戏逻辑，跟什么512完全没有关系，另外你说的mh绕过512限制我不知道你说的是precache限制还是可见实体限制(visedicts)，如果是前者那么不如直接换svengine，SCTEAM那帮人把所有limit全部改大了，基本不存在不够用的情况，理论上可以兼容所有goldsrc能跑的mod。如果说的是visedicts，那么光用mh破解掉客户端的限制没有任何意义，因为服务端发包最多也只能发512个实体的信息，超出的部分连发都不会发谈何显示呢

**Comment by hzqst** [comment]
顺便你说的这些问题我用正版的cz一个也没有复现出来，我有理由怀疑你说的regamedll其实是是逆向版本的客户端dll或者引擎dll(rehlds或者别的什么玩意)，不是服务端。因为光改服务端的dll根本不可能出现这些专属于客户端的奇奇怪怪的问题。
