### ISSUE TITLE
[CM] Request to be able to mark specific subtitles to play regardless of distance

### ISSUE THREAD

**Issue by Zaphero1** [hzqst/MetaHookSv#267]
I've made complete subtitles for Echoes but I'm running into issues getting subtitles to play for certain lines at all, even in cutscenes. I had to increase cap_max_distance to 5000 to have G-Mans' lines in the flashforward actually have subtitles, and setting it that high results in a lot of idle dialog filling up even during the final battle. It needs a way to mark the lines that the player should hear no matter where they are to always play their subtitles.

**Comment by hzqst** [comment]
So you would like to have a flag to indicate that the distance limit should be ignored for certain subtitles?

**Comment by hzqst** [comment]
try https://github.com/hzqst/MetaHookSv/releases/tag/v20230331a

![image](https://user-images.githubusercontent.com/12287588/229025723-41312bf9-1377-454e-896a-5b3bb9f9d04e.png)

Add "IGNORE_DISTANCE_LIMIT" in the column "Style" to mark this subtitle as "ignoring the cap_max_distance"

Multiple styles are seperated with SPACE,

"C", "R", "L" is for text alignment (center, right, left align)

**Comment by Zaphero1** [comment]
It seems like some of the sound and the alignment is broken on that build and tagged lines aren't playing. 
Is there any data I can get to help troubleshoot?

**Comment by Zaphero1** [comment]
Alignment's working now but the tag still doesn't seem to be doing the job because I still need to set that max distance high to get a line to play:
![image](https://user-images.githubusercontent.com/19298996/229218177-1d196145-720c-4f69-873a-1753011de486.png)

with cap_max_distance = 1000
![20230331145734_1](https://user-images.githubusercontent.com/19298996/229218579-7559d402-7737-4b60-b595-65f3577aefd9.jpg)

with cap_max_distance = 3000
![20230331145454_1](https://user-images.githubusercontent.com/19298996/229218660-8066fe61-17be-4d83-a746-13c8a0f0f727.jpg)

**Comment by hzqst** [comment]
https://github.com/hzqst/MetaHookSv/releases/tag/v20230401a should be working

**Comment by Zaphero1** [comment]
Looks like it is now! Thank you very much.

**Comment by Zaphero1** [comment]
Ah looks like a tag for an even smaller distance limit might be helpful for the HECU, they won't even shut up during cutscenes so I guess they rely on having that sound drop off unusually hard compared to others in the game.

**Comment by hzqst** [comment]
> Ah in addition it looks like a tag for an even smaller distance limit might be helpful for the HECU, turns out they won't even shut up during cutscenes so I guess they rely on having that sound drop off unusually hard compared to others in the game.

What about checking actual volume of sound instead of distance before playing subtitles?

**Comment by Zaphero1** [comment]
Oh if possible that would be fantastic; I hope that can work with MetaAudio too.

**Comment by hzqst** [comment]
try https://github.com/hzqst/MetaHookSv/releases/tag/v20230403a

Cvar "cap_min_avol" is there to check the actual volume of sound before playing subtitles,

Cvar "cap_debug" now displays distance and actual volume to the sound source.

**Comment by hzqst** [comment]
> Ah it doesn't look like sentences are getting checked so most of the soldier dialog still always gets played ![image](https://user-images.githubusercontent.com/19298996/229558458-941c51c0-b6b2-4d82-8203-462a0ab9fa25.png) ![20230403103233_1](https://user-images.githubusercontent.com/19298996/229558748-9cbd9f72-a928-46ea-8a78-ec6716d9d8b4.jpg)

try https://github.com/hzqst/MetaHookSv/releases/tag/v20230403b

**Comment by Zaphero1** [comment]
Got it, looks like the check is being done but it's not being used.
![image](https://user-images.githubusercontent.com/19298996/229571500-0c78c53b-9191-455d-a289-e386b40f8234.png)
![20230403113012_1](https://user-images.githubusercontent.com/19298996/229571636-04115c43-3810-414a-941d-f1bdb59332aa.jpg)

**Comment by hzqst** [comment]
> 

the check has been added in https://github.com/hzqst/MetaHookSv/releases/tag/v20230404a

**Comment by Zaphero1** [comment]
Oh yeah! Looks like it's working great now! It is strange though that those same gman lines had to get that IGNORE_VOLUME_LIMIT tag because the game thinks they're playing at 0 volume even if you definitely can hear them. I'll def need to do another playthrough and and apply that tags to cutscene character lines to be safe.

**Comment by hzqst** [comment]
> Oh yeah! Looks like it's working great now! It is strange though that those same gman lines had to get that IGNORE_VOLUME_LIMIT tag because the game thinks they're playing at 0 volume even if you definitely can hear them. I'll def need to do another playthrough to test and and apply that tags to cutscene character lines to be safe.

what's the avol and dist of those same lines being said? like all zero or ?

**Comment by Zaphero1** [comment]
Both are far away and have 0 volume despite playing as clear as day, it's strange.
![image](https://user-images.githubusercontent.com/19298996/230181987-a05c64b8-9051-46e7-a440-62637bc916af.png)
I can confirm both the tags are working so I have gotten them playing no problem by adding those tags to them in the dictionary.

**Comment by Zaphero1** [comment]
Looks like it has a compatibility issue with MetaAudio, it thinks all the sounds are playing at 0 volume and much farther away than they are, so no captions play.
![image](https://user-images.githubusercontent.com/19298996/231980914-26221d0f-472e-411b-8ad2-7051805d6ed5.png)
https://github.com/hzqst/MetaHookSv/issues/230

**Comment by hzqst** [comment]
> Looks like it has a compatibility issue with MetaAudio, it thinks all the sounds are playing at 0 volume and much farther away than they are, so no captions play. ![image](https://user-images.githubusercontent.com/19298996/231980914-26221d0f-472e-411b-8ad2-7051805d6ed5.png) #230

try https://github.com/hzqst/MetaHookSv/releases/tag/v20230414a

**Comment by Zaphero1** [comment]
Looks like that fixed it (or at least fixed it enough for differences to be slight)! Thank you very much!

Without MetaAudio.dll:
![image](https://user-images.githubusercontent.com/19298996/232006253-76ec9b71-40f5-4819-a6ef-827c5a4ff46a.png)
With MetaAudio.dll:
![image](https://user-images.githubusercontent.com/19298996/232007082-ba76af7d-ea85-412f-90d8-70f0bfe58858.png)
[Example save.zip](https://github.com/hzqst/MetaHookSv/files/11231316/Example.save.zip)
