### ISSUE TITLE
Some textures appear to be fullbright or have incorrect lighting applied to them

### ISSUE THREAD

**Issue by HowaitoHaato** [hzqst/MetaHookSv#268]
Basically what the title says.  It seems that it mostly happens with stuff you can interact with. 
I'm using an AMD card (RX 570 8gb).
Here's some examples:

![20230403181519_1](https://user-images.githubusercontent.com/129798156/229629371-c200104e-ff86-4a34-98bf-b511fc149d74.jpg)
![20230403181541_1](https://user-images.githubusercontent.com/129798156/229629384-b6034721-cecc-4944-b195-977a81187f32.jpg)

Also, someone else using an AMD card has also reported this, but the HDR mode doesn't seem to work, just turns the whole screen white:

![20230403181554_1](https://user-images.githubusercontent.com/129798156/229629589-ff40d111-cbed-4ecd-b0e5-ebdba4e14655.jpg)

**Comment by hzqst** [comment]
Which map can I repro the fullbright glitch with?

**Comment by HowaitoHaato** [comment]
The maps in the screenshot are hplanet and the first map of azure sheep (asmap00)

**Comment by hzqst** [comment]
The unexpected fullbright has been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20230410a
