### ISSUE TITLE
Better implementation of character encoding (CaptionMod)

### ISSUE THREAD

**Issue by qabRieL99** [hzqst/MetaHookSv#27]
As of right now, if you had tried to add support to new languages, especially the ones with special (or accented) characters in their alphabets, you'd need to add every single special character by hand. Is it possible to update the plug-in that it somehow recognizes every single character automatically?

**Comment by hzqst** [comment]
idk if Windows has such an API to recognize non-English alphabet charachers or not. if there is such an API, it is possible to do.

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/pull/357

**Comment by qabRieL99** [comment]
I believe you overhauled that whole thing in a recent commit, but my problem returned after that.

![20250101190012_1](https://github.com/user-attachments/assets/1d4458e3-5ada-4b58-9b74-9312433935ed)

As in the example, s should linger on its own and continue in the next line. The "ı" character is causing it to behave like that.
