### ISSUE TITLE
[Renderer] echoes-13.bsp crashes as soon as it loads (Sven Co-op port)

### ISSUE THREAD

**Issue by HowaitoHaato** [hzqst/MetaHookSv#274]
Title pretty much. 
Using AMD RX570 8gb as my GPU

Link to the ported Sven Co-op version:
http://scmapdb.wikidot.com/map:half-life:echoes

**Comment by hzqst** [comment]
Can't repro

Could you please try [latest amd graphic driver](https://www.amd.com/en/support/graphics/radeon-500-series/radeon-rx-500-series/radeon-rx-570)?

**Comment by HowaitoHaato** [comment]
Tried both. 
Still crashes without fail. I'm attaching a video that shows exactly what happens (sorry for the quality, had to compress it to keep it under the 10MB limit)

https://user-images.githubusercontent.com/129798156/233725650-3b0a257c-1ea2-43e5-85c4-7d17c157c273.mp4

If I turn off the renderer by adding a ; to it in the plugins.lst file, then it loads fine, but I'd rather have it because my framerate is awful without it, specially on echoes.

**Comment by HowaitoHaato** [comment]
Doesn't seem to crash anymore on recent MetahookSV versions, if anyone else is having this issue, just update to the lastest version.

**Comment by hzqst** [comment]
Seems to be fixed. Just comment here or reopen this issue if anyone encounter the crash again.
