### ISSUE TITLE
[CM] Nextsubtitle does not work

### ISSUE THREAD

**Issue by Zaphero1** [hzqst/MetaHookSv#276]
I'm trying to use the next subtitle feature for longer speech-files, but it never seems to generate that second line no matter what Delaytonextsubtitle is set to or what duration is set to for either subtitle.
![image](https://user-images.githubusercontent.com/19298996/233803750-14948936-f627-4a75-8927-e8381b704372.png)
![image](https://user-images.githubusercontent.com/19298996/233803761-af1069f2-cba9-49c4-ad67-658545d8ce49.png)
![20230422145144_1](https://user-images.githubusercontent.com/19298996/233803869-cadb5fc9-b672-4f7a-a508-39bc74925a91.jpg)

Is there a setting that needs to be enabled first for it?

**Comment by hzqst** [comment]
![image](https://user-images.githubusercontent.com/12287588/233814945-bba55149-8ac4-4a4d-a719-5c7f5133f3f3.png)
Try `test2` instead of `#test2` in the NextSubtitle

**Comment by Zaphero1** [comment]
There we go, so I was missing something to get it working! Thank you very much!

**Comment by Zaphero1** [comment]
Does Nextsubtitle work for sentence calls too? I couldn't split up the Nihilanth Freeman joke in Echoes because the second one just didn't play when I did.

**Comment by hzqst** [comment]
> Does Nextsubtitle work for sentence calls too? I couldn't split up the Nihilanth Freeman joke in Echoes because the second one just didn't play when I did.

It does.
