### ISSUE TITLE
[CM] Mods that crash on startup when subtitles are enabled

### ISSUE THREAD

**Issue by Zaphero1** [hzqst/MetaHookSv#280]
So far I've found:
Field Intensity,
Residual Life (1.9),
and
Gunman Chronicles
To crash on startup when CaptionMod is installed and enabled as a plugin.
since that has a built in caption system that's very limited.

Field Intensity and Residual Life both return the same fatal error of 
```
Could not found: 
g_iVisibleMouse 
```
but Gunman Chronicles just crashes silently. I am not sure why specifically those two.
![image](https://user-images.githubusercontent.com/19298996/234766088-b7bdf6c6-e9d3-4d72-bd58-c7da3a41c4e8.png)
![image](https://user-images.githubusercontent.com/19298996/234766732-b8ab304b-2275-49ce-b079-fd25f8588c39.png)

For possible sources of the issues, Field Intensity uses its own limited subtitle system that can't cover all dialog, while Residual Life and Gunman Chronicles keep their custom sounds in pk3 files.

**Comment by hzqst** [comment]
Try https://github.com/hzqst/MetaHookSv/releases/tag/v20230428a

**Comment by Zaphero1** [comment]
They are all crashing silently with that unfortunately.
Here are the crashlogs for each.
[Crashlogs.zip](https://github.com/hzqst/MetaHookSv/files/11350336/Crashlogs.zip)

**Comment by hzqst** [comment]
try https://github.com/hzqst/MetaHookSv/releases/tag/v20230428b

**Comment by Zaphero1** [comment]
That is making them all crash silently unfortunately. 
Crashlogs with that build here:
[More crashlogs.zip](https://github.com/hzqst/MetaHookSv/files/11351306/More.crashlogs.zip)

**Comment by hzqst** [comment]
try https://github.com/hzqst/MetaHookSv/releases/tag/v20230428c

Seems that some critical interfaces are missing from those mods. Probably out-of-dated HLSDK.

**Comment by Zaphero1** [comment]
Looks like that fixed it! They all launch now and based on debug it is reading the lines in those pk3s! Thank you very much!
