### ISSUE TITLE
Compilation Error with my plugin [ PVOID Uknown size ]

### ISSUE THREAD

**Issue by ollerjoaco** [hzqst/MetaHookSv#282]
Hi Im getting an error when trying to compile a plugin. I got a lot of errors but I managed to fix almost all except for this one that Im not sure what can it be.

VS Output: 
C2036 ´PVOID´: Unknow size.
E0852 Expression must be a pointer to a complete object type

These are the lines ( second one its the one that VS tell me its wrong )

```
		PVOID dwClientBase = g_pMetaHookAPI->GetModuleBase(GetModuleHandle("client.dll"));
		g_pfnEV_HLDM_DecalGunshot = (void(*)(pmtrace_t *, int, float, int, int, int, bool, char))(dwClientBase + 0x20B0);
```

![image](https://user-images.githubusercontent.com/57648434/236964949-e3ddbcd0-6379-44df-9369-2a194edb193c.png)

**Comment by hzqst** [comment]
You can't add a PVOID `dwClientBase` and an integer literal `0x20B0` together unless you convert `dwClientBase` to an *Arithmetic type* (e.g. `unsigned long` or `ULONG_PTR`)  or *Pointer type to an known type* (e.g. `char *` or `PUCHAR` aka `unsigned char *`) explicitly.

I guess this expression is what you want indeed:
`g_pfnEV_HLDM_DecalGunshot = (decltype(g_pfnEV_HLDM_DecalGunshot))( (PUCHAR)dwClientBase + 0x20B0 )`

**Comment by ollerjoaco** [comment]
Ohh thanks that was it. I didnt know about PUCHAR thanks again!
