### ISSUE TITLE
SUGGESTION: Make ragdolls reactive to bullets / Blood decals emit out of ragdolls

### ISSUE THREAD

**Issue by tqoac** [hzqst/MetaHookSv#283]
I had a thought come to mind, would there be a way to have ragdolls react to bullets? Like for say you shoot a player ragdoll and a blood particle comes out and a blood decal would be cast, or have blood decals spawn and follow a ragdoll?

**Comment by di57inct** [comment]
https://github.com/hzqst/MetaHookSv/issues/176

**Comment by tqoac** [comment]
Closing as duplicate
