### ISSUE TITLE
[BulletPhysics] [SUGGESTION] Add CVar to control how long until physics enter sleep

### ISSUE THREAD

**Issue by tqoac** [hzqst/MetaHookSv#284]
In source engine branches, there exists a convar called 'ragdoll_sleepaftertime' that defines what velocity a ragdoll has to be until it enters sleep and stops moving. Could we get a similar command for it, I find that the ragdolls take too long to freeze, so having a command to control this would be great.

**Comment by hzqst** [comment]
`bv_ragdoll_sleepaftertime` has been added in https://github.com/hzqst/MetaHookSv/releases/tag/v20230519a

**Comment by tqoac** [comment]
> `bv_ragdoll_sleepaftertime` along with `bv_ragdoll_sleeplinearvel` and `bv_ragdoll_sleepangularvel` has been added in https://github.com/hzqst/MetaHookSv/releases/tag/v20230519a

Thank you so much! I've been having issues with ragdolls shaking alot, this should help stop it!
