### ISSUE TITLE
Adding Echoes Installer to release builds

### ISSUE THREAD

**Issue by Zaphero1** [hzqst/MetaHookSv#286]
Is there anything that needs to get done before it can be included in the release builds like bug hunting/hammering out on the renderer and other plugins, or is it okay if it gets through with its complete subtitle support? We probably need a build ready to share and get more people testing it.

**Comment by hzqst** [comment]
It's ready to go if you mean CaptionMod.
the Echoes Installer was already there called `install-to-Echoes.bat` iirc.

**Comment by Zaphero1** [comment]
Got it!
