### ISSUE TITLE
布娃娃有时候会失去作用

### ISSUE THREAD

**Issue by 1912188434** [hzqst/MetaHookSv#288]
问题：
1.在使用cl_minmodel 1时会比较严重，在游戏中会偶尔触发[100%]
2.在超过五个角色死亡后会触发 [45%]
3.如果玩家死后且靠近墙面有概率触发 [60%]
https://github.com/hzqst/MetaHookSv/assets/62979586/174269af-48e7-41b7-b1ce-9fb730196b91

**Comment by hzqst** [comment]
Fixed since https://github.com/hzqst/MetaHookSv/releases/tag/v20241208b
