### ISSUE TITLE
Renderer.dll插件会导致使用鼠标光标的面板无法正常使用，并且和ABCEnchance的雷达功能冲突。

### ISSUE THREAD

**Issue by NoobLCH** [hzqst/MetaHookSv#289]
本地使用release版本的：MetaHookSv-refs/tags/v20230528a（其实这个好像一直就有这个问题）
分辨率：1920*1080
模式：窗口模式（无边框窗口）
发现涉及到用鼠标光标操作的面板，进入后大部分情况点击不动按钮，小部分情况按的是A按钮但实际按到的是B按钮。
光标操作的面板如下图：
![image](https://github.com/hzqst/MetaHookSv/assets/83013106/b0155400-0176-4270-b4f5-d5f22604de4e)
![image](https://github.com/hzqst/MetaHookSv/assets/83013106/5d447d63-125e-4902-8ceb-5bd1866f5eb1)

不能正常操控面板的录像可见群文件。

本地做过一下尝试：
1. 开启Renderer.dll，关闭所有能关闭的画面设置，仍然不能正确操控面板。所关闭的功能：
r_hdr 0
r_shadow 0
r_water 0
r_ssao 0
r_light_dynamic 0
r_ssr 0
r_detailtextures 0
r_detailtextures 1
r_detailtextures 0
r_studio_celshade 0
r_fxaa 0
r_wsurf_zprepass 0
r_wsurf_sky_occlusion 0
2. 直接关闭Renderer.dll，能正常操控面板。
3. plugins.lst的设置如下：
ABCEnchance.dll
CaptionMod.dll
Renderer.dll
;BulletPhysics.dll
StudioEvents.dll
CommunicationDemo.dll
SCModelDownloader.dll
SteamScreenshots.dll
;DontFlushSoundCache.dll

此外，也能确认Renderer.dll和ABCEnchace的雷达功能有冲突，怀疑二者可能有相似之处？
开启Renderer.dll的雷达会显示不出地形。
![image](https://github.com/hzqst/MetaHookSv/assets/83013106/91fb3dee-c505-4c69-a8c5-4af948ed25ae)
关闭Renderer.dll后，雷达能正确显示地形。
![image](https://github.com/hzqst/MetaHookSv/assets/83013106/94d4c9ea-b71e-4633-9695-b37b52d91911)

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20230626a
