### ISSUE TITLE
The game still crashes

### ISSUE THREAD

**Issue by d3nchk** [hzqst/MetaHookSv#291]
1.It is necessary to solve the issue with opengl crash, no one is going to fix drivers, it is already clear, because almost a year has passed, and nothing has changed.
Moreover, I caught crashes on nvidia graphics cards, they are just harder to catch than on AMD.
Can you somehow fine-tune the renderer, so it does not crash opengl, otherwise what is the point of this project, if some maps at all do not start - immediately crashed, or play, and after two or three changes of maps the game inevitably crashed.
At the moment, I can attach from the event log error code opengl (but I understand that you do not tell anything)

Failed application name: svencoop.exe, version: 0.4.0.0, timestamp: 0x64734ffc
Failed module name: atioglxx.dll, version: 31.0.14051.5006, timestamp: 0x644196c6
Exclusion code: 0xc0000005
Error Offset: 0x008969cb
Failed process ID: 0x1208
Start time of the failed application: 0x01d99d38a78756e1
Failed application path: C:\Games\CS1.6\svencoop.exe
Путь сбойного модуля: C:\Windows\System32\DriverStore\FileRepository\u0391252.inf_amd64_b298c070ddf486e2\B391109\atioglxx.dll
Report ID: 088988d9-a756-460b-a0b5-5d08b821f31f

Let's solve this issue already.

2.And when will support for PBR maps be added to the models? I really need it!

**Comment by hzqst** [comment]
1. Your amd user-mode driver `atioglxx.dll` (31.0.14051.5006)  seems to be an out-dated one as it was found crashing game since 2022.

`31.0.22000.11015` should fix the issue.

see: https://community.amd.com/t5/opengl-vulkan/opengl-user-mode-driver-crash-got-instant-crash-inside/td-p/556169

2. When I find solution to build tangent from vertex and normal.

**Comment by hzqst** [comment]
> > 1. Your amd user-mode driver `atioglxx.dll` (31.0.14051.5006)  seems to be an out-dated one as it was found crashing game since 2022.
> > 
> > `31.0.22000.11015` should fix the issue.
> > see: https://community.amd.com/t5/opengl-vulkan/opengl-user-mode-driver-crash-got-instant-crash-inside/td-p/556169
> > 
> > 2. When I find solution to build tangent from vertex and normal.
> 
> It's not that simple. AMD wouldn't be itself if it didn't once again shit itself. Namely, the guys shut down support for WS2022, now even through the device manager you can't manually put fresh drivers. But in any case I have 2023 version - Adrenalin 23.4.3 WHQL Release Date 4/27/2023 But I went further and ripped out this dll from the new distrubitv and hand-picked it via safe mode into the directory. As a result, the game still crashes. Only now in the event log is not written anything. I do not know what to do, have any ideas how to overcome it?

try adding -nobindless in the launch parameters.

**Comment by d3nchk** [comment]
> > > 1. Your amd user-mode driver `atioglxx.dll` (31.0.14051.5006)  seems to be an out-dated one as it was found crashing game since 2022.
> > > 
> > > `31.0.22000.11015` should fix the issue.
> > > see: https://community.amd.com/t5/opengl-vulkan/opengl-user-mode-driver-crash-got-instant-crash-inside/td-p/556169
> > > 
> > > 2. When I find solution to build tangent from vertex and normal.
> > 
> > 
> > It's not that simple. AMD wouldn't be itself if it didn't once again shit itself. Namely, the guys shut down support for WS2022, now even through the device manager you can't manually put fresh drivers. But in any case I have 2023 version - Adrenalin 23.4.3 WHQL Release Date 4/27/2023 But I went further and ripped out this dll from the new distrubitv and hand-picked it via safe mode into the directory. As a result, the game still crashes. Only now in the event log is not written anything. I do not know what to do, have any ideas how to overcome it?
> 
> try adding -nobindless in the launch parameters.

I tried it with this parameter.
I also tried removing it.

What else can I do?

**Comment by d3nchk** [comment]
> > 1. Your amd user-mode driver `atioglxx.dll` (31.0.14051.5006)  seems to be an out-dated one as it was found crashing game since 2022.
> > 
> > `31.0.22000.11015` should fix the issue.
> > see: https://community.amd.com/t5/opengl-vulkan/opengl-user-mode-driver-crash-got-instant-crash-inside/td-p/556169
> > 
> > 2. When I find solution to build tangent from vertex and normal.
> 
> It's not that simple. AMD wouldn't be itself if it didn't once again shit itself. Namely, the guys shut down support for WS2022, now even through the device manager you can't manually put fresh drivers. But in any case I have 2023 version - Adrenalin 23.4.3 WHQL Release Date 4/27/2023 But I went further and ripped out this dll from the new distrubitv and hand-picked it via safe mode into the directory. As a result, the game still crashes. Only now in the event log is not written anything. I do not know what to do, have any ideas how to overcome it?

Failed application name: svencoop.exe, version: 0.4.0.0, timestamp: 0x64734ffc
Failed module name: atioglxx.dll, version: 31.0.22000.11015, timestamp: 0x645a5a58
Exclusion code: 0xc0000005
Error Offset: 0x008b8238
Failed process ID: 0x267c
Start time of the failed application: 0x01d99e0334d99dca
Failed application path: C:\Games\CS1.6\svencoop.exe
Путь сбойного модуля: C:\Windows\System32\DriverStore\FileRepository\u0390767.inf_amd64_d061b8afea284919\B390703\atioglxx.dll
Report ID: daba01d1-8219-45cc-af50-b0d0bd428496

**Comment by d3nchk** [comment]
logfile
L 06/13/2023 - 17:44:17: Log file started (file "logs\L0613001.log") (game "cstrike") (version "48/1.1.2.7/8684")
L 06/13/2023 - 17:44:17: Loading map "de_lake_csgo"
L 06/13/2023 - 17:44:17: Server cvars start
L 06/13/2023 - 17:44:17: Server cvar "allow_spectators" = "1.0"
L 06/13/2023 - 17:44:17: Server cvar "amx_client_languages" = "1"
L 06/13/2023 - 17:44:17: Server cvar "amx_language" = "en"
L 06/13/2023 - 17:44:17: Server cvar "amxmodx_version" = ""
L 06/13/2023 - 17:44:17: Server cvar "bot_allow_grenades" = "1"
L 06/13/2023 - 17:44:17: Server cvar "bot_allow_machine_guns" = "1"
L 06/13/2023 - 17:44:17: Server cvar "bot_allow_pistols" = "1"
L 06/13/2023 - 17:44:17: Server cvar "bot_allow_rifles" = "1"
L 06/13/2023 - 17:44:17: Server cvar "bot_allow_rogues" = "1"
L 06/13/2023 - 17:44:17: Server cvar "bot_allow_shield" = "1"
L 06/13/2023 - 17:44:17: Server cvar "bot_allow_shotguns" = "1"
L 06/13/2023 - 17:44:17: Server cvar "bot_allow_snipers" = "1"
L 06/13/2023 - 17:44:17: Server cvar "bot_allow_sub_machine_guns" = "1"
L 06/13/2023 - 17:44:17: Server cvar "bot_auto_vacate" = "1"
L 06/13/2023 - 17:44:17: Server cvar "bot_chatter" = "normal"
L 06/13/2023 - 17:44:17: Server cvar "bot_deathmatch" = "0"
L 06/13/2023 - 17:44:17: Server cvar "bot_debug" = "0"
L 06/13/2023 - 17:44:17: Server cvar "bot_defer_to_human" = "0"
L 06/13/2023 - 17:44:17: Server cvar "bot_difficulty" = "0"
L 06/13/2023 - 17:44:17: Server cvar "bot_join_after_player" = "1"
L 06/13/2023 - 17:44:17: Server cvar "bot_join_delay" = "0"
L 06/13/2023 - 17:44:17: Server cvar "bot_join_team" = "any"
L 06/13/2023 - 17:44:17: Server cvar "bot_nav_edit" = "0"
L 06/13/2023 - 17:44:17: Server cvar "bot_nav_zdraw" = "4"
L 06/13/2023 - 17:44:17: Server cvar "bot_prefix" = ""
L 06/13/2023 - 17:44:17: Server cvar "bot_profile_db" = "BotProfile.db"
L 06/13/2023 - 17:44:17: Server cvar "bot_quicksave" = "0"
L 06/13/2023 - 17:44:17: Server cvar "bot_quota" = "0"
L 06/13/2023 - 17:44:17: Server cvar "bot_quota_mode" = "normal"
L 06/13/2023 - 17:44:17: Server cvar "bot_show_danger" = "0"
L 06/13/2023 - 17:44:17: Server cvar "bot_show_nav" = "0"
L 06/13/2023 - 17:44:17: Server cvar "bot_stop" = "0"
L 06/13/2023 - 17:44:17: Server cvar "bot_traceview" = "0"
L 06/13/2023 - 17:44:17: Server cvar "bot_walk" = "0"
L 06/13/2023 - 17:44:17: Server cvar "bot_zombie" = "0"
L 06/13/2023 - 17:44:17: Server cvar "coop" = "0"
L 06/13/2023 - 17:44:17: Server cvar "deathmatch" = "1"
L 06/13/2023 - 17:44:17: Server cvar "decalfrequency" = "30"
L 06/13/2023 - 17:44:17: Server cvar "edgefriction" = "2"
L 06/13/2023 - 17:44:17: Server cvar "ff_damage_reduction_bullets" = "0.35"
L 06/13/2023 - 17:44:17: Server cvar "ff_damage_reduction_grenade" = "0.25"
L 06/13/2023 - 17:44:17: Server cvar "ff_damage_reduction_grenade_self" = "1"
L 06/13/2023 - 17:44:17: Server cvar "ff_damage_reduction_other" = "0.25"
L 06/13/2023 - 17:44:17: Server cvar "game_version" = "5.22.0.588-dev"
L 06/13/2023 - 17:44:17: Server cvar "humans_join_team" = "any"
L 06/13/2023 - 17:44:17: Server cvar "max_queries_sec" = "3.0"
L 06/13/2023 - 17:44:17: Server cvar "max_queries_sec_global" = "30"
L 06/13/2023 - 17:44:17: Server cvar "max_queries_window" = "60"
L 06/13/2023 - 17:44:17: Server cvar "metamod_version" = "1.21p40"
L 06/13/2023 - 17:44:17: Server cvar "mp_afk_bomb_drop_time" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_autokick" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_autokick_timeout" = "-1"
L 06/13/2023 - 17:44:17: Server cvar "mp_autoteambalance" = "1"
L 06/13/2023 - 17:44:17: Server cvar "mp_buy_anywhere" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_buytime" = "99.000000"
L 06/13/2023 - 17:44:17: Server cvar "mp_c4timer" = "45"
L 06/13/2023 - 17:44:17: Server cvar "mp_chattime" = "10"
L 06/13/2023 - 17:44:17: Server cvar "mp_consistency" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_fadetoblack" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_falldamage" = "1"
L 06/13/2023 - 17:44:17: Server cvar "mp_flashlight" = "1"
L 06/13/2023 - 17:44:17: Server cvar "mp_footsteps" = "1"
L 06/13/2023 - 17:44:17: Server cvar "mp_forcecamera" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_forcechasecam" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_forcerespawn" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_fraglimit" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_fragsleft" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_freeforall" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_freezetime" = "0.000000"
L 06/13/2023 - 17:44:17: Server cvar "mp_friendlyfire" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_give_player_c4" = "1"
L 06/13/2023 - 17:44:17: Server cvar "mp_hostage_hurtable" = "1"
L 06/13/2023 - 17:44:17: Server cvar "mp_hostagepenalty" = "5.000000"
L 06/13/2023 - 17:44:17: Server cvar "mp_infinite_ammo" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_infinite_grenades" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_item_staytime" = "300"
L 06/13/2023 - 17:44:17: Server cvar "mp_kickpercent" = "0.66"
L 06/13/2023 - 17:44:17: Server cvar "mp_limitteams" = "2"
L 06/13/2023 - 17:44:17: Server cvar "mp_logdetail" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_logfile" = "1"
L 06/13/2023 - 17:44:17: Server cvar "mp_logmessages" = "1"
L 06/13/2023 - 17:44:17: Server cvar "mp_mapvoteratio" = "0.66"
L 06/13/2023 - 17:44:17: Server cvar "mp_maxmoney" = "16000"
L 06/13/2023 - 17:44:17: Server cvar "mp_maxrounds" = "0.000000"
L 06/13/2023 - 17:44:17: Server cvar "mp_playerid" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_radio_maxinround" = "60"
L 06/13/2023 - 17:44:17: Server cvar "mp_radio_timeout" = "1.5"
L 06/13/2023 - 17:44:17: Server cvar "mp_respawn_immunity_effects" = "1"
L 06/13/2023 - 17:44:17: Server cvar "mp_respawn_immunity_force_unset" = "1"
L 06/13/2023 - 17:44:17: Server cvar "mp_respawn_immunitytime" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_round_infinite" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_round_restart_delay" = "5"
L 06/13/2023 - 17:44:17: Server cvar "mp_roundover" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_roundtime" = "5.000000"
L 06/13/2023 - 17:44:17: Server cvar "mp_scoreboard_showdefkit" = "1"
L 06/13/2023 - 17:44:17: Server cvar "mp_scoreboard_showhealth" = "3"
L 06/13/2023 - 17:44:17: Server cvar "mp_scoreboard_showmoney" = "3"
L 06/13/2023 - 17:44:17: Server cvar "mp_show_scenarioicon" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_startmoney" = "16000.000000"
L 06/13/2023 - 17:44:17: Server cvar "mp_timeleft" = "0"
L 06/13/2023 - 17:44:17: Server cvar "mp_timelimit" = "20.000000"
L 06/13/2023 - 17:44:17: Server cvar "mp_tkpunish" = "1"
L 06/13/2023 - 17:44:17: Server cvar "mp_weapons_allow_map_placed" = "1"
L 06/13/2023 - 17:44:17: Server cvar "mp_windifference" = "1"
L 06/13/2023 - 17:44:17: Server cvar "mp_winlimit" = "0.000000"
L 06/13/2023 - 17:44:17: Server cvar "pausable" = "1"
L 06/13/2023 - 17:44:17: Server cvar "sv_accelerate" = "10"
L 06/13/2023 - 17:44:17: Server cvar "sv_aim" = "0"
L 06/13/2023 - 17:44:17: Server cvar "sv_airaccelerate" = "10"
L 06/13/2023 - 17:44:17: Server cvar "sv_allowupload" = "1"
L 06/13/2023 - 17:44:17: Server cvar "sv_alltalk" = "0"
L 06/13/2023 - 17:44:17: Server cvar "sv_bounce" = "1"
L 06/13/2023 - 17:44:17: Server cvar "sv_cheats" = "0"
L 06/13/2023 - 17:44:17: Server cvar "sv_clienttrace" = "1"
L 06/13/2023 - 17:44:17: Server cvar "sv_contact" = ""
L 06/13/2023 - 17:44:17: Server cvar "sv_friction" = "4"
L 06/13/2023 - 17:44:17: Server cvar "sv_gravity" = "800"
L 06/13/2023 - 17:44:17: Server cvar "sv_logblocks" = "0"
L 06/13/2023 - 17:44:17: Server cvar "sv_maxrate" = "0"
L 06/13/2023 - 17:44:17: Server cvar "sv_maxspeed" = "320"
L 06/13/2023 - 17:44:17: Server cvar "sv_minrate" = "0"
L 06/13/2023 - 17:44:17: Server cvar "sv_password" = ""
L 06/13/2023 - 17:44:17: Server cvar "sv_proxies" = "1"
L 06/13/2023 - 17:44:17: Server cvar "sv_restart" = "0"
L 06/13/2023 - 17:44:17: Server cvar "sv_restartround" = "0"
L 06/13/2023 - 17:44:17: Server cvar "sv_stepsize" = "18"
L 06/13/2023 - 17:44:17: Server cvar "sv_stopspeed" = "100"
L 06/13/2023 - 17:44:17: Server cvar "sv_uploadmax" = "0.5"
L 06/13/2023 - 17:44:17: Server cvar "sv_voiceenable" 

CRASH

**Comment by d3nchk** [comment]
I can not find commands to turn on the rendering logging, it would be visible at what stage the game crashes
Is there such a command?

**Comment by hzqst** [comment]
> I can not find commands to turn on the rendering logging, it would be visible at what stage the game crashes Is there such a command?

`C:\Program Files (x86)\Steam\dumps\*.dmp` would be helpful than logging stuffs.

**Comment by d3nchk** [comment]
> > I can not find commands to turn on the rendering logging, it would be visible at what stage the game crashes Is there such a command?
> 
> `C:\Program Files (x86)\Steam\dumps\*.dmp` would be helpful than logging stuffs.

So what's the bottom line? How are we going to solve the problem of outbursts?
Is there a command for the rendering log in the end or not?
In Steam, the game can not buy, blocked access

**Comment by hzqst** [comment]
> > > I can not find commands to turn on the rendering logging, it would be visible at what stage the game crashes Is there such a command?
> > 
> > 
> > `C:\Program Files (x86)\Steam\dumps\*.dmp` would be helpful than logging stuffs.
> 
> So what's the bottom line? How are we going to solve the problem of outbursts? Is there a command for the rendering log in the end or not? In Steam, the game can not buy, blocked access

Try Visual Studio to attach to the game process before joining the game and check the callstacks when crashing.

**Comment by d3nchk** [comment]
> Try Visual Studio to attach to the game process before joining the game and check the callstacks when crashing.

I would love to, but I'm not a coder, I can hardly deploy visual studio correctly at all, there is a whole ritual of tambourine to put this toolkit at all.
Surely there must be easier ways.
Maybe in the renderer add debug mode? Or some rendering modes to choose from, I don't know, so I poke around, try it out.
Because I say that I tested the build on another computer in general, with another card, there was NVIDIA T1000 8Gb, the game did not immediately break out as I had on my PC of course, but also after two to three maps, crashed.
Simply, I am testing on a hard, first I have models with 50-80 thousand polygons, plus textures up to 4k, and secondly, I am testing with the maximum number of bots 24-32 players. In the third map is heavy, this is a port of cs go. Well, I play an hour and a half, if it does not fly out. So not everyone may have problems, but they are, I assure you. It's not my bad hands.

**Comment by d3nchk** [comment]
> > > > I can not find commands to turn on the rendering logging, it would be visible at what stage the game crashes Is there such a command?
> > > 
> > > 
> > > `C:\Program Files (x86)\Steam\dumps\*.dmp` would be helpful than logging stuffs.
> > 
> > 
> > So what's the bottom line? How are we going to solve the problem of outbursts? Is there a command for the rendering log in the end or not? In Steam, the game can not buy, blocked access
> 
> Try Visual Studio to attach to the game process before joining the game and check the callstacks when crashing.

I put the new build, it still crashes
There seems to be some dependence on the size and detail maps
Difficult maps a la de_lake_csgo game crashes without a chance in 100% of 100, and the default type cs_italy, loaded, but randomly during the battle crashes.
Will we be able to fix the renderer or not, at least plans are any, worth the hope?

**Comment by d3nchk** [comment]
> 



> > > > > > I can not find commands to turn on the rendering logging, it would be visible at what stage the game crashes Is there such a command?
> > > > > 
> > > > > 
> > > > > `C:\Program Files (x86)\Steam\dumps\*.dmp` would be helpful than logging stuffs.
> > > > 
> > > > 
> > > > So what's the bottom line? How are we going to solve the problem of outbursts? Is there a command for the rendering log in the end or not? In Steam, the game can not buy, blocked access
> > > 
> > > 
> > > Try Visual Studio to attach to the game process before joining the game and check the callstacks when crashing.
> > 
> > 
> > I put the new build, it still crashes There seems to be some dependence on the size and detail maps Difficult maps a la de_lake_csgo game crashes without a chance in 100% of 100, and the default type cs_italy, loaded, but randomly during the battle crashes. Will we be able to fix the renderer or not, at least plans are any, worth the hope?
> 
> Check the TaskManager and see if metahook.exe or cstrike.exe hit 1.4GiB of memory usage on that map. if yes then it might an OOM or called out of memory error.

2945, then drops to 2700 and the game crashes

**Comment by d3nchk** [comment]
> > > > > > I can not find commands to turn on the rendering logging, it would be visible at what stage the game crashes Is there such a command?
> > > > > 
> > > > > 
> > > > > `C:\Program Files (x86)\Steam\dumps\*.dmp` would be helpful than logging stuffs.
> > > > 
> > > > 
> > > > So what's the bottom line? How are we going to solve the problem of outbursts? Is there a command for the rendering log in the end or not? In Steam, the game can not buy, blocked access
> > > 
> > > 
> > > Try Visual Studio to attach to the game process before joining the game and check the callstacks when crashing.
> > 
> > 
> > I put the new build, it still crashes There seems to be some dependence on the size and detail maps Difficult maps a la de_lake_csgo game crashes without a chance in 100% of 100, and the default type cs_italy, loaded, but randomly during the battle crashes. Will we be able to fix the renderer or not, at least plans are any, worth the hope?
> 
> Check the TaskManager and see if metahook.exe or cstrike.exe hit 1.4GiB of memory usage on that map. if yes then it might an OOM or called out of memory error.

What to do in the end?

**Comment by d3nchk** [comment]
> > > > > > I can not find commands to turn on the rendering logging, it would be visible at what stage the game crashes Is there such a command?
> > > > > 
> > > > > 
> > > > > `C:\Program Files (x86)\Steam\dumps\*.dmp` would be helpful than logging stuffs.
> > > > 
> > > > 
> > > > So what's the bottom line? How are we going to solve the problem of outbursts? Is there a command for the rendering log in the end or not? In Steam, the game can not buy, blocked access
> > > 
> > > 
> > > Try Visual Studio to attach to the game process before joining the game and check the callstacks when crashing.
> > 
> > 
> > I put the new build, it still crashes There seems to be some dependence on the size and detail maps Difficult maps a la de_lake_csgo game crashes without a chance in 100% of 100, and the default type cs_italy, loaded, but randomly during the battle crashes. Will we be able to fix the renderer or not, at least plans are any, worth the hope?
> 
> Check the TaskManager and see if metahook.exe or cstrike.exe hit 1.4GiB of memory usage on that map. if yes then it might an OOM or called out of memory error.

In the previous reply I wrote about the map de_Lake_csgo, it does not load at all, about the memory I wrote.
For example map cs_italy (default loaded), while loading the same thing comes to about 3 gb, but the map is successfully loaded.
Until the exit could not get to, but randomly on the standard maps occurs, the consumption was 1200 mb.
Screenshot attached 
![screen](https://github.com/hzqst/MetaHookSv/assets/112010596/102cce5f-40e6-4d25-9f7b-23d471ea3fdd)

**Comment by hzqst** [comment]
> > > > > > > I can not find commands to turn on the rendering logging, it would be visible at what stage the game crashes Is there such a command?
> > > > > > 
> > > > > > 
> > > > > > `C:\Program Files (x86)\Steam\dumps\*.dmp` would be helpful than logging stuffs.
> > > > > 
> > > > > 
> > > > > So what's the bottom line? How are we going to solve the problem of outbursts? Is there a command for the rendering log in the end or not? In Steam, the game can not buy, blocked access
> > > > 
> > > > 
> > > > Try Visual Studio to attach to the game process before joining the game and check the callstacks when crashing.
> > > 
> > > 
> > > I put the new build, it still crashes There seems to be some dependence on the size and detail maps Difficult maps a la de_lake_csgo game crashes without a chance in 100% of 100, and the default type cs_italy, loaded, but randomly during the battle crashes. Will we be able to fix the renderer or not, at least plans are any, worth the hope?
> > 
> > 
> > Check the TaskManager and see if metahook.exe or cstrike.exe hit 1.4GiB of memory usage on that map. if yes then it might an OOM or called out of memory error.
> 
> Any idea how to solve the problem? You periodically disappear, and it is not clear what to do.

I have no idea what happened with your game since you don't provide any crashdump for analysis. From what I can tell it's probably either amd graphic driver issue or out of memory error.

**Comment by d3nchk** [comment]
> > > > > > > > I can not find commands to turn on the rendering logging, it would be visible at what stage the game crashes Is there such a command?
> > > > > > > 
> > > > > > > 
> > > > > > > `C:\Program Files (x86)\Steam\dumps\*.dmp` would be helpful than logging stuffs.
> > > > > > 
> > > > > > 
> > > > > > So what's the bottom line? How are we going to solve the problem of outbursts? Is there a command for the rendering log in the end or not? In Steam, the game can not buy, blocked access
> > > > > 
> > > > > 
> > > > > Try Visual Studio to attach to the game process before joining the game and check the callstacks when crashing.
> > > > 
> > > > 
> > > > I put the new build, it still crashes There seems to be some dependence on the size and detail maps Difficult maps a la de_lake_csgo game crashes without a chance in 100% of 100, and the default type cs_italy, loaded, but randomly during the battle crashes. Will we be able to fix the renderer or not, at least plans are any, worth the hope?
> > > 
> > > 
> > > Check the TaskManager and see if metahook.exe or cstrike.exe hit 1.4GiB of memory usage on that map. if yes then it might an OOM or called out of memory error.
> > 
> > 
> > Any idea how to solve the problem? You periodically disappear, and it is not clear what to do.
> 
> I have no idea what happened with your game since you don't provide any crashdump for analysis. From what I can tell it's probably either amd graphic driver issue or out of memory error.

Okay, I'll try sometime to buy a copy in style, in order to send the log. The problem is that for Russia it is forbidden to buy in Steam. So I would have long ago provided the dump.

**Comment by d3nchk** [comment]
> > > > > > > > I can not find commands to turn on the rendering logging, it would be visible at what stage the game crashes Is there such a command?
> > > > > > > 
> > > > > > > 
> > > > > > > `C:\Program Files (x86)\Steam\dumps\*.dmp` would be helpful than logging stuffs.
> > > > > > 
> > > > > > 
> > > > > > So what's the bottom line? How are we going to solve the problem of outbursts? Is there a command for the rendering log in the end or not? In Steam, the game can not buy, blocked access
> > > > > 
> > > > > 
> > > > > Try Visual Studio to attach to the game process before joining the game and check the callstacks when crashing.
> > > > 
> > > > 
> > > > I put the new build, it still crashes There seems to be some dependence on the size and detail maps Difficult maps a la de_lake_csgo game crashes without a chance in 100% of 100, and the default type cs_italy, loaded, but randomly during the battle crashes. Will we be able to fix the renderer or not, at least plans are any, worth the hope?
> > > 
> > > 
> > > Check the TaskManager and see if metahook.exe or cstrike.exe hit 1.4GiB of memory usage on that map. if yes then it might an OOM or called out of memory error.
> > 
> > 
> > Any idea how to solve the problem? You periodically disappear, and it is not clear what to do.
> 
> I have no idea what happened with your game since you don't provide any crashdump for analysis. From what I can tell it's probably either amd graphic driver issue or out of memory error.

I'm sending you the dump. Just don't get lost.
[assert_cstrike.exe_20230629193612_1.zip](https://github.com/hzqst/MetaHookSv/files/11908293/assert_cstrike.exe_20230629193612_1.zip)

**Comment by hzqst** [comment]
> 

This looks like an out of memory error (std_bad_alloc exception) but I am not sure.

**Comment by d3nchk** [comment]
> > 
> 
> This looks like an out of memory error (std_bad_alloc exception) but I am not sure.

What do you recommend?
I tested on different computers, mine has 16 gigabytes of RAM, the other has 32.

**Comment by hzqst** [comment]
> > > 
> > 
> > 
> > This looks like an out of memory error (std_bad_alloc exception) but I am not sure.
> 
> What do you recommend? I tested on different computers, mine has 16 gigabytes of RAM, the other has 32.

The 32bit msvcrt (C runtime libraries) can handle up to only 1.4 gigs of RAM and I found no way to get rid of this unless GoldSrc were upgraded to 64bit.
