### ISSUE TITLE
[Renderer] MOVETYPE_FOLLOW not working

### ISSUE THREAD

**Issue by hzqst** [hzqst/MetaHookSv#294]

**Comment by DrAbcOfficial** [comment]
原因：
函数调用顺序为：R_EntityComponents_StartFrame -> R_DrawCurrentEntity -> HUD_AddEntity
R_EntityComponents_StartFrame 中清空了g_ClientEntityRenderComponents
R_DrawCurrentEntity 中使用空白的 g_ClientEntityRenderComponents 来绘制
HUD_AddEntity 最后才添加这帧的 g_ClientEntityRenderComponents 

简单粗暴非常不优雅的解决尝试：
![20230709021501](https://github.com/hzqst/MetaHookSv/assets/29565652/9e483de2-5d97-488b-a671-708110a96422)
![20230709021518](https://github.com/hzqst/MetaHookSv/assets/29565652/801edec9-43f7-4511-ac78-5dfd7711ff3d)

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20230709c
