### ISSUE TITLE
[BP] Ragdolls sleeping on last death frame if out of the player's view

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#295]
If a player dies behind a wall for example, the ragdoll doesn't initiate and the model is stuck in the last death animation frame.
Will provide video if necessary.

**Comment by hzqst** [comment]
I guess it's because the server stops sending frame updates for the dying player entity out of view?

**Comment by di57inct** [comment]
I don't know, but i'm guessing it's related to update https://github.com/hzqst/MetaHookSv/commit/e2634d479c9d2b3938d18663be8e9389615b43d5 and update https://github.com/hzqst/MetaHookSv/commit/0c048551b05f82e3a76fabf44a45a6696c50efb6 didn't fully fix it.

**Comment by di57inct** [comment]
Video examples here. Notice that in the second clip, the player wasn't even behind a wall(my camera was just not facing him) and he still got stuck in the last animation frame which should have triggered the ragdoll.
Here is my ragdoll file:
```
[DeathAnim]
101 99
102 31
103 72
104 14
105 142
106 155
107 14
108 139
109 21
110 16

[RigidBody]
Head 7  6   capsule  -5   5.0   0.1   3
Spine 5  4   capsule  -2   8.0   0.1   10
Pelvis 1  2  capsule  2   7.5   0.1   10

LArm 9 10  capsule  5  2.5   8.0    2
LArm2 10 11  capsule  6   2.5   10.0    2

RArm 18 19  capsule  5   2.5   8.0    2
RArm2 19 20  capsule  6   2.5   10.0    2

LLeg 26 27  capsule  10   3.6   10.0    2
LLeg2 27 28  capsule  8   3.0   8.0    2

RLeg 30 31  capsule  10   3.6   10.0    2
RLeg2 31 32  capsule  8   3.0   8.0    2

[Constraint]
Spine  Head   conetwist 6 7   0 0 0     0  5  0        0.01  0.01  0.2
Pelvis Spine  conetwist 1 5    0 0 0     0 8  0        0.1  0.1  0.1

Spine  LArm   conetwist 8 9    0 0 0     0 -6.5  0        0.2 0.2 0.2
LArm   LArm2  conetwist 9 10    0 0 0     0 -6  0       0.2 0.2 0.1

Spine  RArm   conetwist 16 17    0 0 0     0 -6.5  0        0.2 0.2 0.2
RArm   RArm2  conetwist 17 18    0 0 0     0 -6  0        0.2 0.2 0.1

Pelvis LLeg   conetwist 24 24  0 0 0     0 -7  0        0.1  0.1  0.25
LLeg2  LLeg   hinge     25 25  0 0 0     0 8 0         -0.2  0.0  0

Pelvis RLeg   conetwist 29 29  0 0 0     0 -7  0        0.1  0.1  0.25
RLeg2  RLeg   hinge     30 30  0 0 0     0 8 0         -0.2  0.0  0

[WaterControl]
Head    0  0  0    1.03  0.5  0
Spine   0  0  0    1.03  0.5  0
Pelvis  0  0  0    1.03  0.5  0

LArm    0  0  0    1.03  0.5  0
LArm2   0  0  0    1.03  0.5  0

RArm    0  0  0    1.03  0.5  0
RArm2   0  0  0    1.03  0.5  0

LLeg    0  0  0    1.03	0.5  0
LLeg2   0  0  0    1.03	0.5  0

RLeg    0  0  0    1.03	0.5  0
RLeg2   0  0  0    1.03	0.5  0
```

https://github.com/hzqst/MetaHookSv/assets/3608544/952180e4-5d7e-4de8-bce5-06b6d26ab15c

https://github.com/hzqst/MetaHookSv/assets/3608544/02063769-a526-417f-8ccb-6965f1bec456

**Comment by di57inct** [comment]
https://github.com/hzqst/MetaHookSv/assets/3608544/e5a6cefb-d1b3-4919-9e0f-910bfb6ec853

Notice how the ragdoll updates as soon as in the player's view.

**Comment by di57inct** [comment]
@hzqst has this been fixed by any chance? it's a really game breaking bug.

**Comment by di57inct** [comment]
I've tried setting all **[DeathAnim]** frames to 0. Bug still happens, but I'm getting this error in the console when model is spawned:

> CreateRigBody: Failed to create rigbody for bone LLeg, invalid boneindex (42)
> CreateRigBody: Failed to create rigbody for bone LLeg2, invalid boneindex (43)
> CreateRigBody: Failed to create rigbody for bone RLeg, invalid boneindex (48)
> CreateRigBody: Failed to create rigbody for bone RLeg2, invalid boneindex (49)
> CreateConstraint: Failed to create constraint, linked rigidbody LLeg not found
> CreateConstraint: Failed to create constraint, rigidbody LLeg2 not found
> CreateConstraint: Failed to create constraint, linked rigidbody RLeg not found
> CreateConstraint: Failed to create constraint, rigidbody RLeg2 not found
> CreateWaterControl: Failed to create water control point, rigidbody LLeg not found
> CreateWaterControl: Failed to create water control point, rigidbody LLeg not found
> CreateWaterControl: Failed to create water control point, rigidbody LLeg2 not found
> CreateWaterControl: Failed to create water control point, rigidbody LLeg2 not found
> CreateWaterControl: Failed to create water control point, rigidbody RLeg not found
> CreateWaterControl: Failed to create water control point, rigidbody RLeg not found
> CreateWaterControl: Failed to create water control point, rigidbody RLeg2 not found
> CreateWaterControl: Failed to create water control point, rigidbody RLeg2 not found

**Comment by di57inct** [comment]
Closing in favor of new, better tested and more detailed issue: https://github.com/hzqst/MetaHookSv/issues/364
