### ISSUE TITLE
[ Engine ] VirusTotal Scan reports 9 security issues

### ISSUE THREAD

**Issue by ollerjoaco** [hzqst/MetaHookSv#298]
https://www.virustotal.com/gui/file/dbfd7ee0b46b76d3089ba0d3c18a81efb896e3fa7a4f3d5cf6a5661b8e63e813/detection

Reported and scanned by [MkfMtr](https://gamebanana.com/members/1610927)

**Comment by MilkPossum** [comment]
DLL files will almost always trigger antiviruses even if they're completely normal.
