### ISSUE TITLE
Mouse cursor won't work with HUD

### ISSUE THREAD

**Issue by Anotherspess** [hzqst/MetaHookSv#3]
Although not that big of a deal, it's difficult to select some HUD elements with metahooksv, mainly inventory items, using votemenu and muting players in scoreboard. It'd be ideal if one could use console commands for such things, but I doubt they'll implement that in Sven any time soon.

**Comment by hzqst** [comment]
The bug comes from CaptionMod's VGUI2 hook.
Removing or commenting "captionmod.dll" from "\Sven Co-op\svencoop\metahook\configs\plugins.lst" could temperorily resolve this problem, I am trying to fix later.
