### ISSUE TITLE
[BP] 为JiggleBone增加Flag标记，从而可选择关闭JiggleBone与其他物体的碰撞

### ISSUE THREAD

**Issue by DrAbcOfficial** [hzqst/MetaHookSv#302]
![94fc33194dd19c37a40d79e0155e85f4](https://github.com/hzqst/MetaHookSv/assets/29565652/e2ff39f3-f9d4-4d20-a444-9ff8bc1d30c7)
<img width="1281" alt="156ed4563a2d5e2660bf02058ffbac84" src="https://github.com/hzqst/MetaHookSv/assets/29565652/f0657d8b-6358-483d-82bc-7253fddf9417">

**Comment by hzqst** [comment]
<img width="456" alt="image" src="https://github.com/user-attachments/assets/283c24ab-2226-4a66-96b3-d5600c8ab8ba">

Done in the recent update.
