### ISSUE TITLE
DDS BC7 Compressed Format

### ISSUE THREAD

**Issue by d3nchk** [hzqst/MetaHookSv#303]
Currently, only DXT 1 and DXT 5 formats are supported. The picture is very bad. Please add support for BC7 Compressed format.

**Comment by hzqst** [comment]
Could you please try https://github.com/hzqst/MetaHookSv/releases/tag/v20230731a?

**Comment by d3nchk** [comment]
> Could you please try https://github.com/hzqst/MetaHookSv/releases/tag/v20230731a?

Tried it. It doesn't work. 
Tried BC7_UNORM, BC7_UNORM_SRGB formats

**Comment by d3nchk** [comment]
> > > Could you please try https://github.com/hzqst/MetaHookSv/releases/tag/v20230731a?
> > 
> > 
> > Tried it. It doesn't work. Tried BC7_UNORM, BC7_UNORM_SRGB, BPTC formats
> 
> Can you provide the corresponding dds textures with BC7_UNORM format?

Ok
[cstrike.zip](https://github.com/hzqst/MetaHookSv/files/12231291/cstrike.zip)

**Comment by hzqst** [comment]
Should've been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20230803a

<img width="666" alt="屏幕截图 2023-08-03 000132" src="https://github.com/hzqst/MetaHookSv/assets/12287588/26168492-6fbf-42f8-b5ab-c7106353df86">

**Comment by d3nchk** [comment]
> Should've been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20230803a
> 
> <img alt="屏幕截图 2023-08-03 000132" width="666" src="https://user-images.githubusercontent.com/12287588/257875654-26168492-6fbf-42f8-b5ab-c7106353df86.png">

Yeah, it's working. The picture quality is noticeably better. Thank you!
