### ISSUE TITLE
[BulletPhysics] Ragdolls stop rendering and return to static death animation. (DOD, Half-Life)

### ISSUE THREAD

**Issue by tqoac** [hzqst/MetaHookSv#304]
I've noticed that in games, specifically multiplayer (such as Day of Defeat, or Half-Life server) that when a player dies, shortly after they ragdoll (or until they respawn), the ragdoll is removed and the corpse with the last frame of the death animation (which is what would usually show without BP) would be present. I suspect that has something to do with how both of these games have persistent corpses, I would've liked it to be a ragdoll even after the player has died / respawned, is there a way to fix that / add a cvar to control how long ragdolls stay? (such as `bv_ragdoll_staytime`)

**Comment by di57inct** [comment]
Probably related to https://github.com/hzqst/MetaHookSv/issues/295

**Comment by tqoac** [comment]
I actually just noticed that @di57inct already reported this before for Counter Strike, I wonder why it doesn't work on other GoldSRC games? https://github.com/hzqst/MetaHookSv/issues/157
