### ISSUE TITLE
Sky Box Abnormality

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#306]
In CS1.6, if you enter one map and enter another map again, you will get the sky map of the previous map. This is not because the map did not set sky, but because the rendering plugin changed it

**Comment by hzqst** [comment]
你关了renderer只用原版一样有这个bug啊

**Comment by q52888940** [comment]
原版有这个bug是因为地图没有设置sky天空名，但是刚下载新版本就发现了这个bug，就算地图属性里已经设置了天空名，换地图时依然会用上一张地图的天空，确实是bug

**Comment by hzqst** [comment]
https://github.com/hzqst/MetaHookSv/releases/tag/v20230901a 中已经修复。
