### ISSUE TITLE
[BulletPhysics] Ragdoll will disappear and be replaced with static corpse on games outside Counter Strike

### ISSUE THREAD

**Issue by caoqt1** [hzqst/MetaHookSv#308]
Even after commit https://github.com/hzqst/MetaHookSv/commit/52c9f9905d9f2c1ca6a6900de361cc80e2ed0a90 was made, Ragdolls will still disappear and be replaced with ClCorpses, I suspect this is mainly because this change was made only for Counter-Strike, as I only encountered this issue on Day of Defeat and Half-Life for when players / bots died and respawned.

**Comment by hzqst** [comment]
Dead player in Half-Life is an entity with renderfx=kRenderFxDeadPlayer & renderamt = playerindex. there is no ClCorpses message.

**Comment by tqoac** [comment]
> Dead player in Half-Life is an entity with renderfx=kRenderFxDeadPlayer & renderamt = playerindex. there is no ClCorpses message.

Well then, how would we go about saving the ragdoll and not having it be destroyed and replaced with static corpse?

**Comment by hzqst** [comment]
> > Dead player in Half-Life is an entity with renderfx=kRenderFxDeadPlayer & renderamt = playerindex. there is no ClCorpses message.
> 
> Well then, how would we go about saving the ragdoll and not having it be destroyed and replaced with static corpse?

It does by default if you have _ragdoll.txt in Half-Life.

**Comment by tqoac** [comment]
> > > Dead player in Half-Life is an entity with renderfx=kRenderFxDeadPlayer & renderamt = playerindex. there is no ClCorpses message.
> > 
> > 
> > Well then, how would we go about saving the ragdoll and not having it be destroyed and replaced with static corpse?
> 
> It does by default if you have _ragdoll.txt in Half-Life.

Thats strange... I've tested Day of Defeat with _ragdoll.txt files for all character models in the game, when a player dies, it correctly does a ragdoll until they respawn, at which the ragdoll will be deleted and swapped out with static corpse.

**Comment by hzqst** [comment]
Probably a Day of Defeat-Dedicated issue, I will get back to you when I made any progress on it.

**Comment by di57inct** [comment]
> Probably a Day of Defeat-Dedicated issue, I will get back to you when I made any progress on it.

It happens in cs and cz too

**Comment by tqoac** [comment]
> Probably a Day of Defeat-Dedicated issue, I will get back to you when I made any progress on it.

Thank you, I also remember having this happen on Half-Life servers, same thing happens, player dies, respawns, ragdoll gets deleted and replaced with corpses.

**Comment by di57inct** [comment]
Here is proof of it happening in CS. When you look away, the ragdoll is replaced with static corpse, but after you touch it, it turns back into a ragdoll.

https://github.com/hzqst/MetaHookSv/assets/3608544/4af4be8f-54cb-4a71-afbe-0d0f43d8539b


https://github.com/hzqst/MetaHookSv/assets/3608544/2706bcdf-f7b9-477f-8b99-027e472192ae

**Comment by di57inct** [comment]
Also related to https://github.com/hzqst/MetaHookSv/issues/295

**Comment by hzqst** [comment]
Duplicated of #364
