### ISSUE TITLE
脸在CS中被删除

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#309]
![Y`B`)G`GYY$9YXMM0UY3{$C](https://github.com/hzqst/MetaHookSv/assets/68973128/d0c2d032-9f70-41fa-a2c4-559ed2eb1843)
这个BUG很久了，只要用了{
    "classname" "studio_texture"
    "basetexture" "XXX.bmp"
    "flags" "STUDIO_NF_CELSHADE_FACE"
}
在cs中脸就被删了，以前没用上，今天来反馈下

另外布娃娃为什么在CS中对人质无效了

**Comment by q52888940** [comment]
![V%HF@XRO6`4MX`WMC UJ(38](https://github.com/hzqst/MetaHookSv/assets/68973128/2b63f35f-0ad3-47e8-bcdf-6d3dff911798)

**Comment by hzqst** [comment]
模型能发下不，我有空进游戏看看？

**Comment by q52888940** [comment]
> 模型能发下不，我有空进游戏看看吗？

模型用的插件里带的模型测试的，任何模型只要用了STUDIO_NF_CELSHADE_FACE效果贴图就会被删除，只在CS零点行动里面测试了，其他MOD没测试

**Comment by q52888940** [comment]
补充一下， 感觉CS中的人物模型划线也消失了，很久了，至少半年前出现的

**Comment by q52888940** [comment]
你会解决这个问题吗，我可以帮你制作张地图把模型塞进去供你测试

**Comment by hzqst** [comment]
> 你会解决这个问题吗，我可以帮你制作张地图把模型塞进去供你测试

可以，地图发来

**Comment by q52888940** [comment]
[CZERO.ZIP](https://github.com/hzqst/MetaHookSv/files/12561372/CZERO.ZIP)

**Comment by hzqst** [comment]
![FACEFACE0000](https://github.com/hzqst/MetaHookSv/assets/12287588/8f3b7a03-b973-4209-9ef8-d13bd9295e03)


Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20230918a
