### ISSUE TITLE
[征求]会考虑解除宽屏限制吗

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#311]

**Comment by q52888940** [comment]
另外问下会优化下BSP吗，现在mod几十万面没问题，但BSP有些还是会卡，不知道什么原因

**Comment by hzqst** [comment]
![image](https://github.com/hzqst/MetaHookSv/assets/12287588/63653092-e814-4fd2-999f-eefd30317cb0)

宽屏不是本来就支持？

BSP会卡的话我不知道你说的是哪张图，目前我没有碰到过纯bsp能导致明显掉帧的

**Comment by q52888940** [comment]
https://www.baidu.com/link?url=XOA7yM0gbmvq0nWFqhUlEIrKAKCLi33J1Dr19HPvm4yln_BiNjaDlIUSzGKT2ErZ&wd=&eqid=c576715100014a020000000664f9dbac
很早之前的metahook插件了。但只支持旧版本3266。用3266测试使用上面网址的插件可以有更多的分辨率选项。

**Comment by q52888940** [comment]
在cs的一些图，你也知道有些为了地图成品质量地图会塞很多固拼以及模型,听说这对服务器也不太友好？比较复杂的地图在某些场景就会有掉帧的情况，有办法优化下吗
例如这张地图https://gamebanana.com/mods/83211. 在某些场景不加入bot的情况下从300fps掉到70-80，我的显卡是2060s
加入zbot更是不友好，当然这也和zbot是cpu渲染的有很大关系，毕竟太老了

**Comment by hzqst** [comment]
我看了下那个视频，所谓的“新宽屏”其实就是在计算垂直FOV的时候强制使用4:3的屏幕比例（金源默认使用的是水平FOV，垂直FOV是通过屏幕长宽比计算出来的）

想要保持跟4：3分辨率一致的FOV效果只需要[在计算垂直FOV时锁定屏幕比例为4：3即可](https://github.com/hzqst/MetaHookSv/blob/f4a651d43c2f5ffcfc4125f8cb16c27307930765/Plugins/Renderer/gl_rmain.cpp#L2385)

使用方法：`r_adjust_fov 2`

![800x600](https://github.com/hzqst/MetaHookSv/assets/12287588/48b4b8a0-4b5f-4816-a40d-ad6ec56992a5)
![1920x1080](https://github.com/hzqst/MetaHookSv/assets/12287588/c2c37d92-5b10-402f-8edc-3b40cc24c788)
Added in
