### ISSUE TITLE
字幕设置崩溃

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#312]
在cs中点击点击两次游戏设置-音频中的字幕设置游戏会崩溃,-cs零点行动测试
另外请问下，人名怎么标记，我准备给无线电都写上，但是不知道怎么写谁发出的
给人质测试人名发出，但是没效果

**Comment by hzqst** [comment]
Uploading 2023-09-17 13-03-19.mp4…

无法复现crash

人名在dictionary.csv的Speaker项下面填写，支持使用#开头的本地化字符串。（如果要以表格形式编辑csv请使用Microsoft Excel打开）

**Comment by q52888940** [comment]
![O97`JT786~JEIF6L1FM%R_9](https://github.com/hzqst/MetaHookSv/assets/68973128/81a560c6-f252-47c3-8aa5-48a9457c75b6)
模型要么设置了二次元效果的贴图正常其他全黑，要么就什么都不设置才能恢复正常

**Comment by q52888940** [comment]
你可以看到部件头部的耳机与模型已经完全没有法线了，我不知道也不确定这个BUG是怎么引起的

**Comment by q52888940** [comment]
![image](https://github.com/hzqst/MetaHookSv/assets/68973128/98159fb7-71dc-4586-8029-92772fc67c69)
![image](https://github.com/hzqst/MetaHookSv/assets/68973128/fd69eb9e-e38b-468c-b735-dab5f41c8d2d)
开启 r_adjust_fov 2后环境遮蔽变得不明显？

**Comment by hzqst** [comment]
> 你可以看到部件头部的耳机与模型已经完全没有法线了，我不知道也不确定这个BUG是怎么引起的

模型发来
