### ISSUE TITLE
Changing Map Skybox Issue

### ISSUE THREAD

**Issue by ntaditya** [hzqst/MetaHookSv#313]
when changing one map to another the skybox of the previous map loads into the new map and so on

for eg :- i load de_dust2 then i changelevel to de_nuke the skybox of de_dust2 will replace the skybox of de_nuke

demonstration - https://www.youtube.com/watch?v=4rI22HHt490
de_nuke skybox in 35_hp2

**Comment by hzqst** [comment]
https://github.com/hzqst/MetaHookSv/assets/12287588/da9ddfe5-687c-4c5d-9879-5b37cb5adc9c

Can't repro with Counter-Strike (Steam hw.dll 8684)

**Comment by ntaditya** [comment]
i even performed a clean install - https://www.youtube.com/watch?v=GDYxv7gQk2o still the issue occurs 
am i installing it wrong ?

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20230901a
