### ISSUE TITLE
[CaptionMod] Alpha channel of the background panel turns off when crossing between maps

### ISSUE THREAD

**Issue by Przetrosz** [hzqst/MetaHookSv#315]
During short loadings between maps, alpha channel of the background panel turns off, resulting in lack of transparency. It wouldn't really be a problem if not for the corners that are white during this transition. Could they be turned black for that particular moment instead of white?

![20230907023651_1](https://github.com/hzqst/MetaHookSv/assets/144294333/1482eb23-3048-4783-a2fe-cf8dfbfcfc99)

**Comment by hzqst** [comment]
Fixed in [latest commit](https://github.com/hzqst/MetaHookSv/releases/tag/v20230917b)

**Comment by Przetrosz** [comment]
Now I see that the lack of transparency is due to not using the new renderer. Would it be possible for the transparent panel to also be available in the vanilla version? Anyway, thanks a lot that the corners don't break now.

**Comment by hzqst** [comment]
> Now I see that the lack of transparency is due to not using the new renderer. Would it be possible for the transparent panel to also be available in the vanilla version? Anyway, thanks a lot that the corners don't break now.

Valve **completely broken the capability of transparent blending in loading state** from vanilla engine  (probably because they didn't expect modders to draw any transparent stuffs over screen while loading).

**Comment by Przetrosz** [comment]
Alright then. Most importantly, the corners work now.
