### ISSUE TITLE
新版本V模型贴图消失

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#318]
![2L{_}1E{$PY)F2O7U%52RBR](https://github.com/hzqst/MetaHookSv/assets/68973128/197c6e90-6b2c-4e24-85b9-8ce3d25417be)

**Comment by q52888940** [comment]
目前只发现V模型会这样

**Comment by q52888940** [comment]
![% 03HAE M}X`7V1}$Z$Y254](https://github.com/hzqst/MetaHookSv/assets/68973128/e00be7c3-fae0-4218-83c7-4fe1e8e93f56)
一些人物模型

**Comment by q52888940** [comment]
r_adjust_fov开启时，环境遮蔽光消失，另外不知道是不是我这边问题，r_vertical_fov开启后我没有看出r_adjust_fov 2的任何效果

**Comment by q52888940** [comment]
![SJW49VFBI2 7P90JU{XX71Z](https://github.com/hzqst/MetaHookSv/assets/68973128/7c08a2c0-16a0-4701-8209-e82f6260558a)
CS原版武器没有受影响，我不知道是不是我在我的模型加入了external.txt更换了贴图，并且加入二次元效果的原因

**Comment by hzqst** [comment]
出问题的模型发来

**Comment by q52888940** [comment]
[Desktop.ZIP](https://github.com/hzqst/MetaHookSv/files/12662547/Desktop.ZIP)
我认为模型其中一个贴图加入了    "flags" "STUDIO_NF_CELSHADE"效果，只要有还没加入    "flags" "STUDIO_NF_CELSHADE"效果的贴图就会变成图中那样

**Comment by q52888940** [comment]
[Desktop.ZIP](https://github.com/hzqst/MetaHookSv/files/12662694/Desktop.ZIP)
怀疑是替换贴图或者模型其中一个贴图启动了“二次元效果”但是其他贴图没使用就会发生图中的事情，不确定

**Comment by q52888940** [comment]
[人物.zip](https://github.com/hzqst/MetaHookSv/files/12662730/default.zip)

**Comment by q52888940** [comment]
> [人物.zip](https://github.com/hzqst/MetaHookSv/files/12662730/default.zip)

以上是其中两个模型

**Comment by q52888940** [comment]
果然，测试发现这个BUG在二次元效果关闭后恢复

**Comment by hzqst** [comment]
最新版应该解决了：https://github.com/hzqst/MetaHookSv/releases/tag/v20230923a
