### ISSUE TITLE
Visual artifacts on the latest update

### ISSUE THREAD

**Issue by H3ADROOM** [hzqst/MetaHookSv#319]
I've downloaded latest MetaHookSv version (MetaHookSv-refs/tags/v20230925b) and in game I have artifacts. I will provide screenshots below. Issue is present on different PCs. Tested on NVIDIA Quadro T1000 and NVIDIA RTX 3070.

![225840_20230925180755_1](https://github.com/hzqst/MetaHookSv/assets/61066950/6f052124-b789-4c50-b040-6e01548c0852)
![225840_20230925180951_1](https://github.com/hzqst/MetaHookSv/assets/61066950/7287ea6b-7c2b-4fa5-8ceb-2cd46358fc6e)
![225840_20230925180855_1](https://github.com/hzqst/MetaHookSv/assets/61066950/34cdea44-8394-47bb-a1bf-509dd2a25258)

**Comment by hzqst** [comment]
Can't repro this issue with my 4060 laptop. Could you please provide more detailed information, like runtime environment (Windows or wine or proton) and the map? btw you could try `r_gamma_blend 0` and `gl_bindless 0`

**Comment by H3ADROOM** [comment]
I run Windows 11. Issue is present on almost any map that has effects. Best examples would be "ka_cbp_b03" and "ka_risingsun". Another issue is that transparency is screwed. In spots where something should be hollow - it is completely black. `gl_bindless 0` doesn't change anything for me, but `r_gamma_blend 0` certanily does, pixelated artifcats are gone, transparancy is still broken though.

**Comment by H3ADROOM** [comment]
Here are some screenshots that show the issue

![225840_20230926130826_1](https://github.com/hzqst/MetaHookSv/assets/61066950/e319bb06-e686-4fff-8932-66d1513c9c4c)
![225840_20230926130116_1](https://github.com/hzqst/MetaHookSv/assets/61066950/dfc6cd1a-95c4-4b1a-a59b-bd65e35774a9)
![225840_20230926125704_1](https://github.com/hzqst/MetaHookSv/assets/61066950/af7fe80d-196e-4484-b715-a2886a23609b)

**Comment by H3ADROOM** [comment]
With `r_gamma_blend 0` 
![225840_20230926125655_1](https://github.com/hzqst/MetaHookSv/assets/61066950/90a79513-0684-4d75-a590-0283e4e41ae5)
Without `r_gamma_blend 0` 
![225840_20230926125658_1](https://github.com/hzqst/MetaHookSv/assets/61066950/924ac0e6-a483-41ff-bd2c-c7a0a00862fa)

**Comment by hzqst** [comment]
> Here are some screenshots that show transparency issue
> 
> ![225840_20230926130826_1](https://user-images.githubusercontent.com/61066950/270652136-e319bb06-e686-4fff-8932-66d1513c9c4c.png) ![225840_20230926130116_1](https://user-images.githubusercontent.com/61066950/270652182-dfc6cd1a-95c4-4b1a-a59b-bd65e35774a9.png) ![225840_20230926125704_1](https://user-images.githubusercontent.com/61066950/270652198-af7fe80d-196e-4484-b715-a2886a23609b.png)

The transparent issue was fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20230926a

**Comment by H3ADROOM** [comment]
> The transparent issue was fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20230926a

Hmmmm, this release has a false positive for `Trojan:Win32/Wacatac.H!ml`

**Comment by H3ADROOM** [comment]
I won't force you to hurry up, but are there any updates on the artifacts? Transparency issue is gone, it works fine. As I said `r_gamma_blend 0` removes those artifacts, but bloom is not present anymore.

**Comment by hzqst** [comment]
> I won't force you to hurry up, but are there any updates on the artifacts? Transparency issue is gone, it works fine. As I said `r_gamma_blend 0` removes those artifacts, but bloom is not present anymore.

I have no idea what's going on with the artifacts as I can't repro the issue at all on my end. I've tested with latest commit on 4060 laptop, RX6800 and UHD770, no artifact was found.

**Comment by SMGgoPrrrrrr** [comment]
Hi I also get artifacts but only when enabling dynamic lights. I also have gl_bindless on 1 and r_gamma_blend on 1.

My specs idk
Gtx 1660ti 6gb
i5 10600kf
32gb ram
a samsung ssd - lol




![svencoop 2023-09-28 00-49-31](https://github.com/hzqst/MetaHookSv/assets/98787612/af65a578-32e4-4096-bd24-c2f40660e33a)

**Comment by hzqst** [comment]
> Hi I also get artifacts but only when enabling dynamic lights. I also have gl_bindless on 1 and r_gamma_blend on 1.
> 
> My specs idk Gtx 1660ti 6gb i5 10600kf 32gb ram a samsung ssd - lol
> 
> ![svencoop 2023-09-28 00-49-31](https://user-images.githubusercontent.com/98787612/271188620-af65a578-32e4-4096-bd24-c2f40660e33a.png)

Can you please try https://github.com/hzqst/MetaHookSv/releases/tag/v20230928d ?

**Comment by SMGgoPrrrrrr** [comment]
yeah np.... Just tried it and got the same results.

**Comment by di57inct** [comment]
Confirming this issue on RTX 4080 with latest driver version 546.01

> |index|api|             plugin name|          plugin version|
> |    0| v2|   Gmcx_model_effect.dll|                        |
> |    1| v4|        StudioEvents.dll|     2023-10-14T02:31:51|
> |    2| v4|  BulletPhysics_AVX2.dll|     2023-10-14T02:29:54|
> |    3| v4|       Renderer_AVX2.dll|     2023-10-14T02:31:36|
> |    4| v4|          CaptionMod.dll|     2023-10-14T02:30:07|

![image](https://github.com/hzqst/MetaHookSv/assets/3608544/552be319-421d-4c41-96c9-d609235112c0)

For some reason it also glitches out the nvidia shadow play lol

https://github.com/hzqst/MetaHookSv/assets/3608544/bb115103-5d2c-4767-acce-3d0d1b6a3931

https://github.com/hzqst/MetaHookSv/assets/3608544/5b818896-034d-4f68-b93f-e683cdb80fe0

https://github.com/hzqst/MetaHookSv/assets/3608544/2c3f5325-a359-4e68-bb6d-08fb60619d0e

**Comment by di57inct** [comment]
![image](https://github.com/hzqst/MetaHookSv/assets/3608544/e896bd1d-1569-42ae-9d22-176ea4cbc9ad)

**Comment by di57inct** [comment]
Problem not present in

```
|    1| v4|        StudioEvents.dll|     2023-09-18T17:02:17|
|    2| v4|  BulletPhysics_AVX2.dll|     2023-09-18T16:59:41|
|    3| v4|       Renderer_AVX2.dll|     2023-09-18T17:01:58|
|    4| v4|          CaptionMod.dll|     2023-09-18T16:59:58|
```

**Comment by H3ADROOM** [comment]
Issue is still present, even on the latest update from 8 hrs ago (v20231230a)

**Comment by rbar1um43** [comment]
I have the same issue)

![20240105114218_1](https://github.com/hzqst/MetaHookSv/assets/56739369/fd827387-6fe8-400f-a081-9e01ed87479e)

**Comment by rbar1um43** [comment]
I get a lot of this artifacts especcially in Condition Zero Deleted Scenes.

**Comment by rbar1um43** [comment]
I get a lot of this artifacts especcially in Condition Zero Deleted Scenes.

![20240105110627_1](https://github.com/hzqst/MetaHookSv/assets/56739369/dfe5ecf9-df0d-4dc2-b48e-3d952e14017b)
![20240105114218_1](https://github.com/hzqst/MetaHookSv/assets/56739369/5dd2db8f-6630-410c-afec-18ec4436b053)

**Comment by rbar1um43** [comment]
I get a lot of this artifacts especcially in Condition Zero Deleted Scenes.

![20240105115014_1](https://github.com/hzqst/MetaHookSv/assets/56739369/b68a53d6-b82e-4879-8992-e79e6946c21c)
![20240105115019_1](https://github.com/hzqst/MetaHookSv/assets/56739369/8df7d42a-1aa1-46df-9535-a53b6720b7c7)

**Comment by hzqst** [comment]
> I get a lot of this artifacts especcially in Condition Zero Deleted Scenes.
> 
> ![20240105115014_1](https://private-user-images.githubusercontent.com/56739369/294397774-b68a53d6-b82e-4879-8992-e79e6946c21c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzEwNjgsIm5iZiI6MTcwNDQzMDc2OCwicGF0aCI6Ii81NjczOTM2OS8yOTQzOTc3NzQtYjY4YTUzZDYtYjgyZS00ODc5LTg5OTItZTc5ZTY5NDZjMjFjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA0NTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4OGNhNWMwMzAyYWM3NTM3Mzg2ODE4MjYxNTQzZWZiODMwNjM3MmU4ZTgzZjA3YWNmMzI2YWI1YTcwOWRkOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jXn0z23xmOodxCtqJ-cxGRw1j1hiROSZu8OsHw5UJ9M) ![20240105115019_1](https://private-user-images.githubusercontent.com/56739369/294397812-8df7d42a-1aa1-46df-9535-a53b6720b7c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzEwNjgsIm5iZiI6MTcwNDQzMDc2OCwicGF0aCI6Ii81NjczOTM2OS8yOTQzOTc4MTItOGRmN2Q0MmEtMWFhMS00NmRmLTk1MzUtYTUzYjY3MjBiN2M3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA0NTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMjE5YjY1MGQ4MmEyMjJjZjFlMDU2YWRkNzI1ZWMzNGU2OTQwNzdiYWMwOTEwMWJmODM1ZGI4ZWE5MGRhZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P9Gzc9nlw8kBfVKDISL_mTYJCQY0nBJ3nI0pZomJ3cw)

try `r_gamma_blend 0`

**Comment by rbar1um43** [comment]
> > I get a lot of this artifacts especcially in Condition Zero Deleted Scenes.
> > ![20240105115014_1](https://private-user-images.githubusercontent.com/56739369/294397774-b68a53d6-b82e-4879-8992-e79e6946c21c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzEwNjgsIm5iZiI6MTcwNDQzMDc2OCwicGF0aCI6Ii81NjczOTM2OS8yOTQzOTc3NzQtYjY4YTUzZDYtYjgyZS00ODc5LTg5OTItZTc5ZTY5NDZjMjFjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA0NTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4OGNhNWMwMzAyYWM3NTM3Mzg2ODE4MjYxNTQzZWZiODMwNjM3MmU4ZTgzZjA3YWNmMzI2YWI1YTcwOWRkOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jXn0z23xmOodxCtqJ-cxGRw1j1hiROSZu8OsHw5UJ9M) ![20240105115019_1](https://private-user-images.githubusercontent.com/56739369/294397812-8df7d42a-1aa1-46df-9535-a53b6720b7c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzEwNjgsIm5iZiI6MTcwNDQzMDc2OCwicGF0aCI6Ii81NjczOTM2OS8yOTQzOTc4MTItOGRmN2Q0MmEtMWFhMS00NmRmLTk1MzUtYTUzYjY3MjBiN2M3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA0NTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMjE5YjY1MGQ4MmEyMjJjZjFlMDU2YWRkNzI1ZWMzNGU2OTQwNzdiYWMwOTEwMWJmODM1ZGI4ZWE5MGRhZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P9Gzc9nlw8kBfVKDISL_mTYJCQY0nBJ3nI0pZomJ3cw)
> 
> try `r_gamma_blend 0`

Yeah, problem solved. No more artifacts.

**Comment by rbar1um43** [comment]
> > I get a lot of this artifacts especcially in Condition Zero Deleted Scenes.
> > ![20240105115014_1](https://private-user-images.githubusercontent.com/56739369/294397774-b68a53d6-b82e-4879-8992-e79e6946c21c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzEwNjgsIm5iZiI6MTcwNDQzMDc2OCwicGF0aCI6Ii81NjczOTM2OS8yOTQzOTc3NzQtYjY4YTUzZDYtYjgyZS00ODc5LTg5OTItZTc5ZTY5NDZjMjFjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA0NTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4OGNhNWMwMzAyYWM3NTM3Mzg2ODE4MjYxNTQzZWZiODMwNjM3MmU4ZTgzZjA3YWNmMzI2YWI1YTcwOWRkOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jXn0z23xmOodxCtqJ-cxGRw1j1hiROSZu8OsHw5UJ9M) ![20240105115019_1](https://private-user-images.githubusercontent.com/56739369/294397812-8df7d42a-1aa1-46df-9535-a53b6720b7c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzEwNjgsIm5iZiI6MTcwNDQzMDc2OCwicGF0aCI6Ii81NjczOTM2OS8yOTQzOTc4MTItOGRmN2Q0MmEtMWFhMS00NmRmLTk1MzUtYTUzYjY3MjBiN2M3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA0NTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMjE5YjY1MGQ4MmEyMjJjZjFlMDU2YWRkNzI1ZWMzNGU2OTQwNzdiYWMwOTEwMWJmODM1ZGI4ZWE5MGRhZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P9Gzc9nlw8kBfVKDISL_mTYJCQY0nBJ3nI0pZomJ3cw)
> 
> try `r_gamma_blend 0`

Parts of some models apper trasparent for some reason.

![20240105121702_1](https://github.com/hzqst/MetaHookSv/assets/56739369/856c30a4-f16d-4860-afe8-21f0ad9ae57c)
![20240105121716_1](https://github.com/hzqst/MetaHookSv/assets/56739369/2239b545-9b85-4dc5-93e3-be490c8e4fcc)
![20240105122316_1](https://github.com/hzqst/MetaHookSv/assets/56739369/b33604f7-041d-454b-97f2-be58cc33112a)
![20240105122622_1](https://github.com/hzqst/MetaHookSv/assets/56739369/8783e3d8-874f-42d4-ae6d-b7a301cdb12a)
![20240105122641_1](https://github.com/hzqst/MetaHookSv/assets/56739369/07b684fc-f5f9-4fa7-bb18-437ea8af6096)

**Comment by hzqst** [comment]
Should've been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240114a

Tested on NVIDIA Geforce 4060M, Graphic Driver : 4.6.0 NVIDIA 528.92

![previous](https://github.com/hzqst/MetaHookSv/assets/12287588/45ba7aab-e1cb-4e22-bd8a-c431e8165036)

![fixed](https://github.com/hzqst/MetaHookSv/assets/12287588/0f757494-52a2-4060-b44a-68a7aeed936e)
