### ISSUE TITLE
加载Renderer.dll导致无法进入游戏

### ISSUE THREAD

**Issue by NoobLCH** [hzqst/MetaHookSv#32]
进入游戏在主菜单载入的时候游戏就炸了，提示
Sven Co-op has Crashed unexpectedly. A crash report has been submitted automatically. We apologize for the inconvencience.

**Comment by q52888940** [comment]
这和插件没关系吧 我尝试没有错误

**Comment by hzqst** [comment]
是hook的初始化时机问题，最新的[commit](https://github.com/hzqst/MetaHookSv/commit/833a95c0e1a59bfca36f3b3cbcbfc19d7277c69d)中已经解决。
