### ISSUE TITLE
[Renderer] r_light_dynamic 1 造成的奇怪的半透明材质渲染

### ISSUE THREAD

**Issue by Megalounge** [hzqst/MetaHookSv#324]
https://streamable.com/hif8xh

视频效果如上，主要表现为渲染半透明材质是会有如此棋盘样貌的材质出现在屏幕上半区域，水面上会有较为明显的效果
如果将该参数调为0 会导致时不时的卡顿

**Comment by Megalounge** [comment]
经过一些测试 https://github.com/hzqst/MetaHookSv/releases/tag/v20230918c 此版本的release不会有这样的渲染错误

**Comment by SMGgoPrrrrrr** [comment]
https://github.com/hzqst/MetaHookSv/issues/319 
same but it looks somewhat different. It gets fixed exactly the same way you showed in the video.

**Comment by hzqst** [comment]
可以试试最新的https://github.com/hzqst/MetaHookSv/releases/tag/v20231014a吗？因为我这边完全无法复现所以只能尽可能改改看起来可能会出问题的地方。

**Comment by Megalounge** [comment]
> 可以试试最新的 https://github.com/hzqst/MetaHookSv/releases/tag/v20231014a 吗？因为我这边完全无法复现所以只能尽可能改改看起来可能会出问题的地方。

问题依旧还在，和之前一样，关闭r_light_dynamic就不会有这样子的问题

**Comment by SMGgoPrrrrrr** [comment]
I'm starting to think this is related to drivers and some gpus. Many people have been reporting random checkerboard popping on their screens. Maybe this feature is able to trigger that anomaly somehow.

**Comment by hzqst** [comment]
> I'm starting to think this is related to drivers and some gpus. Many people who own nvidia gpus have been reporting random checkerboard popping on their screens. Maybe this feature is able to trigger that anomaly somehow. If not maybe even the monitor.

I was not even be able to repro this issue on RTX 4060 mobile. haven't got an older gpu to test though.

**Comment by SMGgoPrrrrrr** [comment]
> > I'm starting to think this is related to drivers and some gpus. Many people who own nvidia gpus have been reporting random checkerboard popping on their screens. Maybe this feature is able to trigger that anomaly somehow. If not maybe even the monitor.
> 
> I was not even be able to repro this issue on RTX 4060 mobile. haven't got an older gpu to test though.

Apparently its related to chromium and doesn't happen during gaming. I don't mind playing with gamma blend on 0 for the time being.

**Comment by SMGgoPrrrrrr** [comment]
> > Can you try the latest https://github.com/hzqst/MetaHookSv/releases/tag/v20231014a ? Since I can't reproduce it at all, I can only try my best to correct the possible problems.
> 
> The problem still exists. As before, turning off r_light_dynamic will not cause this problem.

Try r_gamma_blend 0 and r_light_dynamic 1 that also works.

**Comment by hzqst** [comment]
Should've been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240114a

Tested on NVIDIA Geforce 4060M, Graphic Driver : 4.6.0 NVIDIA 528.92

![previous](https://github.com/hzqst/MetaHookSv/assets/12287588/45ba7aab-e1cb-4e22-bd8a-c431e8165036)

![fixed](https://github.com/hzqst/MetaHookSv/assets/12287588/0f757494-52a2-4060-b44a-68a7aeed936e)
