### ISSUE TITLE
FOV problem

### ISSUE THREAD

**Issue by d3nchk** [hzqst/MetaHookSv#325]
On older builds, I used values:
default_fov "120"
viewmodel_fov "90"
r_adjust_fov "1"

This achieved a normal widescreen FOV and a normal, "flattened" view of the viewmodel

In newer builds, for some reason the default_fov command doesn't work at all. When you activate viewmodel_fov value greater than zero, flattens the model. At the same time, the main FOV is rigidly clamped within 90 , and there is no way to change it.
When activating r_vertical_fov 1 the computer starts screaming like a cut by coolers, the load is satanic, fps drops sharply.

What the hell is going on in the new build, in the document to the engine in general nothing is said about it.

How to solve the problem?

**Comment by d3nchk** [comment]
![old_build](https://github.com/hzqst/MetaHookSv/assets/112010596/7d906d06-c2f8-4dd9-8911-a62eb45b3917)
![new_build](https://github.com/hzqst/MetaHookSv/assets/112010596/a3a44d30-08b8-4bd9-99f5-78f5ead16974)

**Comment by hzqst** [comment]
The issue with "stretched" viewmodel has been fixed in the latest commit.
