### ISSUE TITLE
[Renderer] Animated textures not working

### ISSUE THREAD

**Issue by SMGgoPrrrrrr** [hzqst/MetaHookSv#327]
Animated textures like fire and steam don't "move" they appear frozen. Idk how I didn't noticed before lol.

**Comment by hzqst** [comment]
Fixed in latest commit.

https://github.com/hzqst/MetaHookSv/assets/12287588/5628bb24-7963-4776-bbe0-53e91ef403b2

**Comment by SMGgoPrrrrrr** [comment]
:o ok thx 👍
