### ISSUE TITLE
按照说明正确安装后 打开metahook.exe 显示这个

### ISSUE THREAD

**Issue by Anikomat** [hzqst/MetaHookSv#329]
<img width="267" alt="Screenshot 2023-11-19 015140" src="https://github.com/hzqst/MetaHookSv/assets/101886441/a74922c5-df00-4eeb-8929-23919460aeeb">

**Comment by Anikomat** [comment]
MetaHookSv-refs/tags/v20231118b [Latest](https://github.com/hzqst/MetaHookSv/releases/latest) 的build不能正常运行
但是MetaHookSv-refs/tags/v20231118a 更早一些这个build可以

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20231119a
