### ISSUE TITLE
cs布娃娃错误

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#33]
![de_dust0000](https://user-images.githubusercontent.com/68973128/126867934-32fc6716-58ee-46bb-9ae0-fc0119f097ca.jpg)
我只给GIGN模型写了布娃娃配置(只写了动作序号)但所有模型在播放步枪动作的时候就变成了这样

**Comment by hzqst** [comment]
配置文件编写方法请参考
https://github.com/hzqst/MetaHookSv/blob/main/BulletPhysicsCN.md

**Comment by q52888940** [comment]
在CS中monster藤壶部分是不是可以删除

**Comment by hzqst** [comment]
> 在CS中monster藤壶部分是不是可以删除

留着不影响，也可以删

**Comment by q52888940** [comment]
如果只给一个模型写了配置文件那么其他模型也会读取他的配置文件？

**Comment by hzqst** [comment]
> 如果只给一个模型写了配置文件那么其他模型也会读取他的配置文件？

不会，每个模型都要单独写配置文件，因为每个模型的骨骼对应的肢体长度不一定全部一样

**Comment by q52888940** [comment]
不好意思说 刚体那段没看明白
我的理解是 $hbox 3 "Bip01 Pelvis" -4.690000 -4.440000 -6.750000 4.000000 5.560000 6.750000
pelvis是内部名称 
刚体绑定第X号骨骼 从这里开始我就看的云里雾里了

**Comment by q52888940** [comment]
在CS中我只写了CS人物GIGN的死亡动作序号，但我开启bv_debug死亡时并没有出现我的模型数据 反而包括GIGN以及其他模型在一些动作时出现了图里的情况，并且我把CS的模型拿到SVEN COOP测试有效

**Comment by q52888940** [comment]
我发现这是Renderer.dll的错误 即使我把布娃娃DLL删除也会这样

**Comment by q52888940** [comment]
你会修复他吗

**Comment by hzqst** [comment]
> 你会修复他吗

请提供出问题的的CS模型和对应的_ragdoll.txt配置文件

**Comment by q52888940** [comment]
[arctic.zip](https://github.com/hzqst/MetaHookSv/files/6873504/arctic.zip)
没有给任何模型写配置文件，没有开启布娃娃插件，在CS零点行动测试，这个BUG出现在渲染插件里

**Comment by q52888940** [comment]
找到原因了吗

**Comment by hzqst** [comment]
> 找到原因了吗

这里建议你把r_studio_cache_bone改成0试试

**Comment by q52888940** [comment]
r_studio_cache_bone 0有效 请问这个命令的作用是什么 以及我现在在CS如何使用布娃娃

**Comment by hzqst** [comment]
> r_studio_cache_bone 0有效 请问这个命令的作用是什么 以及我现在在CS如何使用布娃娃

这个命令是给SvenCoop缓存骨骼加速渲染用的，CS系的MOD的模型渲染器GameStudioRenderer好像跟SC不太一样，所以不能用这个

**Comment by q52888940** [comment]
好的 那我在去测试布娃娃
