### ISSUE TITLE
Captionmod not working

### ISSUE THREAD

**Issue by sigmagamma** [hzqst/MetaHookSv#330]
install-to-HalfLife.bat didn't work,  so I directly modified gamedir (set GameDir=C:\Program Files (x86)\Steam\steamapps\common\Half-Life)

Following that Meathook installed correctly, I think? but I can't figure out how to run the game with CaptionMod.
When running meathook.exe, cap_enabled does nothing, and neither does cap_show. I've also tried running the game from Steam with -game meathook, that didn't work either.
![image](https://github.com/hzqst/MetaHookSv/assets/9645762/2582a9ba-2d0f-41e3-bf78-df2393c6d077)

**Comment by hzqst** [comment]
All plugins except Renderer are not ready for the new HL25 engine yet.

**Comment by qabRieL99** [comment]
Do you plan on updating it?

**Comment by hzqst** [comment]
> Do you plan on updating it?

yes but it requires maybe days or even months because valve added too much shit to the VGUI2.

**Comment by qabRieL99** [comment]
Just realized that the default font for the subtitles is Tahoma, so selecting that as the used font fixes the issue.
