### ISSUE TITLE
Fatal error when install MetaHookSV to Sven coop

### ISSUE THREAD

**Issue by SonThanhVN** [hzqst/MetaHookSv#331]
![image](https://github.com/hzqst/MetaHookSv/assets/46934330/af3c2298-e37a-420f-9e4e-c9c1b6221f7f)

**Comment by SonThanhVN** [comment]
is this cause by the new HL25 engine or something ?

**Comment by SonThanhVN** [comment]
Solution:
Use version before the HL25 engine update fix
the new version of MetaHook only made for HL25 engine so use older version fix it

**Comment by hzqst** [comment]
Fixed in the latest commit.
