### ISSUE TITLE
Fatal error for Counter Strike

### ISSUE THREAD

**Issue by Ryuknosuke** [hzqst/MetaHookSv#332]
![image](https://github.com/hzqst/MetaHookSv/assets/151928131/625e929e-1e8a-4bcc-909e-6821ea557674)

**Comment by Mutch0199** [comment]
Getting the same error for Half-Life. Am I doing something wrong? using the .bat file to install

**Comment by Ryuknosuke** [comment]
> Getting the same error for Half-Life, really want to play through the game with MetaAudio and the new update. Am I doing something wrong? using the .bat file to install.

![image](https://github.com/hzqst/MetaHookSv/assets/151928131/27cb7f16-41f2-445c-a1b4-1d2cee370b4a)
I got this error for Counter Strike update but not included with metahook, the problem solved is you need change into "beta steam update"

**Comment by hzqst** [comment]
The BulletPhysics.dll and CaptionMod.dll are in WIP state now. You will have to rip them off from the plugins.lst. see https://github.com/hzqst/MetaHookSv/blob/main/BulletPhysics.md#compatibility and https://github.com/hzqst/MetaHookSv/blob/main/CaptionMod.md#compatibility

**Comment by pizzadox11** [comment]
> The BulletPhysics.dll and CaptionMod.dll are in WIP state now. You will have to manually rip them off from the plugins.lst if you were using .bat to install plugins. see https://github.com/hzqst/MetaHookSv/blob/main/BulletPhysics.md#compatibility and https://github.com/hzqst/MetaHookSv/blob/main/CaptionMod.md#compatibility

its not working at all, renderer.dll causes r_setupgl to not be found and the engine version is 9899

**Comment by pizzadox11** [comment]
still not working
