### ISSUE TITLE
Crash and error when starting a game.

### ISSUE THREAD

**Issue by MilkPossum** [hzqst/MetaHookSv#333]
![image](https://github.com/hzqst/MetaHookSv/assets/149012290/bc4994fb-d40d-4208-aa0f-b93aad15ab24)

**Comment by hzqst** [comment]
Which graphic card are you using?

**Comment by MilkPossum** [comment]
Will you be able to fix it?

**Comment by hzqst** [comment]
> Will you be able to fix it?

No, your card is too old. The shader uses an extension that was initiated since 2013 but your card was from 2012.
