### ISSUE TITLE
MetaHook Error on Startup with HL25 Update

### ISSUE THREAD

**Issue by TyrannoWright** [hzqst/MetaHookSv#334]
I'm unsure if this is because I have it installed incorrectly, but MetaHook no longer appears to function for me after the anniversary update. Seems to originate from FileSystem_Stdio.dll
![Screenshot 2023-11-26 120252](https://github.com/hzqst/MetaHookSv/assets/10506744/2f7fb104-4b3d-4134-be74-3e0f0dab5dca)
![Screenshot 2023-11-26 120312](https://github.com/hzqst/MetaHookSv/assets/10506744/5082ce64-d33e-4e72-910a-eee2c4bcc825)

**Comment by TyrannoWright** [comment]
Suppose so. As I read, not all plugins are compatible with the update beside the renderer. Though MetaAudio hasn't been updated since 2021.

**Comment by hzqst** [comment]
> Suppose so. As I read, not all plugins are compatible with the update beside the renderer. Though MetaAudio hasn't been updated since 2021.

I've [drafted a PR](https://github.com/LAGonauta/MetaAudio/pull/59) to fix the issue, you can either wait for LAGonauta to come with a new release or build from [my repo](https://github.com/hzqst/MetaAudio) by yourself.
