### ISSUE TITLE
MH_LoadEngine error on startup (pre-25th engine)

### ISSUE THREAD

**Issue by nolemretaWxd** [hzqst/MetaHookSv#335]
![image](https://github.com/hzqst/MetaHookSv/assets/31414969/58a53594-1092-4182-9654-c7c2ede9c70b)
MetaHookSv shows this error on startup, on pre-25th GoldSrc (on 25th version, it just throws uncompatible engine version error)

**Comment by hzqst** [comment]
Try [latest release](https://github.com/hzqst/MetaHookSv/releases)

**Comment by di57inct** [comment]
Can confirm same error on pre-25 builds with latest version.
![image](https://github.com/hzqst/MetaHookSv/assets/3608544/fba0a4d8-e74e-4db4-886f-bf94a14dfd5a)

**Comment by hzqst** [comment]
> Can confirm same error on pre-25 builds with latest version. ![image](https://private-user-images.githubusercontent.com/3608544/288428814-fba0a4d8-e74e-4db4-886f-bf94a14dfd5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzEzODEsIm5iZiI6MTcwMTg3MTA4MSwicGF0aCI6Ii8zNjA4NTQ0LzI4ODQyODgxNC1mYmEwYTRkOC1lNzRlLTRkYjQtODg2Zi1iZjk0YTE0ZGZkNWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDZUMTM1ODAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTRiZjY0MGNjZDdhYzE4OGJkMDIyZjczOGQ2MDc1NGI4MDY4ZDY0MDQyMmJhNmFmMzllNjE0MWIzZDliYTgxZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IhGFzWj8NDm-1vZZTmW6KNY-B_KRwwMknKHoNVOYdaI)

What is pre-25 builds? do you mean engine buildnum 8684?

**Comment by di57inct** [comment]
> Protocol version 48
> Exe version 1.1.2.7/Stdio (cstrike)
> Exe build: 19:53:27 Aug  3 2020 (8684)

**Comment by hzqst** [comment]
Fixed in the latest commit.

**Comment by di57inct** [comment]
Thank you ❤️

**Comment by di57inct** [comment]
Now it's giving the error on the new engine build. Works fine on legacy one.
![image](https://github.com/hzqst/MetaHookSv/assets/3608544/ead23ffe-c455-4fed-8fe6-501522d42f59)

**Comment by hzqst** [comment]
> Now it's giving the error on the new engine build. Works fine on legacy one. ![image](https://private-user-images.githubusercontent.com/3608544/289358593-ead23ffe-c455-4fed-8fe6-501522d42f59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMTI3MDUsIm5iZiI6MTcwMjIxMjQwNSwicGF0aCI6Ii8zNjA4NTQ0LzI4OTM1ODU5My1lYWQyM2ZmZS1jNDU1LTRmZWQtOGZlNi01MDE1MjJkNDJmNTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTBUMTI0NjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmUxNDMyYWRjZDdhMTYwNjUwN2I1MTIzNzkyYTY2YTlmZGRmZDdkZDI0NTg4N2JmYzZiYzk4MDI5MGMyNWQ1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.520TShWQYL3d0y3goUYIzEP4bLb2fAZsu5oLDzWD8T0)

rip BulletPhysics.dll and CaptionMod.dll off the plugins.lst.
