### ISSUE TITLE
最新版插件无法进入CS

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#34]
---------------------------
Fatal Error
---------------------------
Could not found: R_LoadSkys
Engine buildnum：8684
---------------------------
---------------------------

**Comment by hzqst** [comment]
Fixed in latest commit

**Comment by q52888940** [comment]
已解决
每张地图不同的HDR影子文件什么时候发布 我想根据太阳实体填写不同的样子角度
