### ISSUE TITLE
武器贴图过于暗

### ISSUE THREAD

**Issue by Satoheii** [hzqst/MetaHookSv#340]
武器的贴图忘了从哪次更新开始，变得好像会受到环境光影的影响（？）
这导致在僵尸模式的时候，地图暗下来几乎看不到武器的样子，请问这个有没有办法解决？

![image](https://github.com/hzqst/MetaHookSv/assets/92193811/438ee53f-77bb-4287-a8cc-9a589e5c393e)

**Comment by hzqst** [comment]
viewmodel不是一直都会受脚底地形亮度的影响？

**Comment by Satoheii** [comment]
我下了Github最早可以下的版本v20220901看了一下，确实那时候比较光亮的

![image](https://github.com/hzqst/MetaHookSv/assets/92193811/933389ae-d9d9-4d97-8065-d792adb90711)

**Comment by Satoheii** [comment]
我超，大佬牛逼，刚刚更新了一下问题没了，请问是不是修复了？

**Comment by hzqst** [comment]
> 我超，大佬牛逼，刚刚更新了一下问题没了，请问是不是修复了？

优质解答：不知道

**Comment by Satoheii** [comment]
牛逼
