### ISSUE TITLE
idk why it dosen't work

### ISSUE THREAD

**Issue by ziper221** [hzqst/MetaHookSv#341]
![image](https://github.com/hzqst/MetaHookSv/assets/137253031/da609864-f282-43e1-956d-783e8321f662)

**Comment by di57inct** [comment]
disable bulletphysics and captionmod in plugins.lst they are not supported on the new engine for now

**Comment by ziper221** [comment]
bro😭😭😭😭

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240106d
