### ISSUE TITLE
TWO PROBLEM

### ISSUE THREAD

**Issue by d3nchk** [hzqst/MetaHookSv#343]
1.The game randomly crashes, giving an error (see the screenshot under FAIL1).
2.If you start the game, and open the first map, everything is okay. However, if after this map to open any other map, we get what is on the picture FAIL2.
![FAIL1](https://github.com/hzqst/MetaHookSv/assets/112010596/bb3b566d-afa2-4fd3-a728-3f6efe5d79f1)
![FAIL2](https://github.com/hzqst/MetaHookSv/assets/112010596/e3da1669-6aef-4258-945e-1867f51c69e0)

**Comment by hzqst** [comment]
Could you please try https://github.com/hzqst/MetaHookSv/releases/tag/v20231221c?

**Comment by d3nchk** [comment]
> Could you please try https://github.com/hzqst/MetaHookSv/releases/tag/v20231221c?

Did a quick check, everything seems okay.
If anything comes up later, I'll let you know.
