### ISSUE TITLE
Antivirus firing with Gen:Variant.Razy.582211 detection on latest build

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#345]
Using Bitdefender with latest signatures.
![image](https://github.com/hzqst/MetaHookSv/assets/3608544/ac93c9c4-eba8-499e-a283-14694b28fd93)

**Comment by hzqst** [comment]
You should report false positive to the Bitdefender.

**Comment by di57inct** [comment]
Will do. Thanks :)

**Comment by di57inct** [comment]
Just here to say that bitdefender doesn't detect it as a threat anymore.

**Comment by di57inct** [comment]
Update for latest release as of today:
MetaHook.exe is getting flagged again as Gen:Variant.Lazy.481091
StudioEvents.dll is getting flagged as Gen:Variant.Tedy.536143
False positive reports sent to BitDefender with links to source codes

**Comment by di57inct** [comment]
All false positives reported and unflagged.
