### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#35]
以下为CS零点行动测试
1.记忆属性没了，即使在控制台R_HDR 0 下次进入游戏一切都会回归默认设置
2.CS零点行动任务模式无法打开手电筒
3.CS零点行动任务模式暂停时我的视角飞了出去
![#cs_italy_cz0000_看图王](https://user-images.githubusercontent.com/68973128/126916184-d2414624-3198-4970-a0ef-3ba1c7aa790a.jpg)
(第三个问题虽然不大，但在任务模式中玩家购买武器和打开控制台会自动暂停，难受不说，很容易头晕。）

**Comment by hzqst** [comment]
Uploading 2021-07-26 09-50-33.mp4…

> 1.记忆属性没了，即使在控制台R_HDR 0 下次进入游戏一切都会回归默认设置

无法复现

**Comment by hzqst** [comment]
https://user-images.githubusercontent.com/12287588/126923255-d3946956-06d5-4c34-acc5-63e1ece65cf9.mp4

> 2.CS零点行动任务模式无法打开手电筒

依然无法复现

**Comment by q52888940** [comment]
刚刚再次测试
BUG1原因是多人游戏和任务游戏的设置不会同步，我在任务模式里开启HDR在多人模式并不会开启，也许他们本质不是一个游戏？
bug2是我没有让服务器允许手电筒
BUG3是METAHOOK里的武器摇摆例子插件的不兼容
以上问题已解决 但我还是不明白BUG一的原因 难道他们不是一个游戏？
