### ISSUE TITLE
MetaHookSv won't launch on the latest Half-Life build

### ISSUE THREAD

**Issue by rbar1um43** [hzqst/MetaHookSv#352]
Latest build of Half-Life won't launch with MetaHookSv. It gives me fatal error:
![bug](https://github.com/hzqst/MetaHookSv/assets/56739369/0ba2d13c-935a-4257-bb28-a883f0d5667e)

Build number is 9920.
![version](https://github.com/hzqst/MetaHookSv/assets/56739369/7dfd5739-ab0f-44c4-acb9-786fd8cee059)

**Comment by rbar1um43** [comment]
BulletPhysics is incompatible. I've disabled it and MetaHookSv now works. Close the thread.

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240106d
