### ISSUE TITLE
Weird Player model on CS1.6 build 8684

### ISSUE THREAD

**Issue by lespaul64** [hzqst/MetaHookSv#36]
I just noticed some weird player model on certain animations.

CS1.6 version:
`] version
Protocol version 48
Exe version 1.1.2.7 (cstrike)
Exe build: 19:53:27 Aug  3 2020 (8684)`

I use only 2 metahook plugins:
`Renderer.dll
MetaAudio.dll`

You can see the image i attached.
![bugbugbug](https://user-images.githubusercontent.com/19327772/127631959-926e2259-b2b9-4d9c-8e9f-1ced4016010d.jpg)

**Comment by hzqst** [comment]
Did you try `r_stdio_bone_cache 0` ? I've removed this cvar in the latest commit however.

**Comment by lespaul64** [comment]
> Did you try `r_studio_cache_bone 0` ?

OMG, i'm so sorry i don't even know such command existed. And i have no idea what it does. Yes you are right setting r_studio_cache_bone 0 fix the issue.
Thank you.

**Comment by hzqst** [comment]
> > Did you try `r_studio_cache_bone 0` ?
> 
> OMG, i'm so sorry i don't even know such command existed. And i have no idea what it does. Yes you are right setting r_studio_cache_bone 0 fix the issue.
> Thank you.

Since `r_studio_cache_bone 1`  is conflicting with Counter-Strike, I will remove this cvar in next update to avoid any possible confliction with other mods anyway.
