### ISSUE TITLE
Fatal Error on launch (HL25) and GoldSrc_new (8684)

### ISSUE THREAD

**Issue by rbar1um43** [hzqst/MetaHookSv#360]
HL build is 9920
MetaHookSv version is [v20240110c]
![изображение](https://github.com/hzqst/MetaHookSv/assets/56739369/17ff277f-697f-4f64-80ec-192bdd0b2abc)

**Comment by rbar1um43** [comment]
> HL build is 9920 MetaHookSv version is [v20240110c] ![изображение](https://private-user-images.githubusercontent.com/56739369/295929588-17ff277f-697f-4f64-80ec-192bdd0b2abc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODMwNjAsIm5iZiI6MTcwNDk4Mjc2MCwicGF0aCI6Ii81NjczOTM2OS8yOTU5Mjk1ODgtMTdmZjI3N2YtNjk3Zi00ZjY0LTgwZWMtMTkyYmRkMGIyYWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE0MTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NmM1ZDE3M2MwMTE3ODE1ZTU2ZjU0NjAwNjJkYmE1M2RlMmQ5MjhjNWYyZDkwYjYxNGUwOGE3YzA2MGI3N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fWv8vTmxguHlC0WWYSGiSN9C-dBESg2usrX2EYpVPQI)

Same error on HL build 8684.

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240111a
