### ISSUE TITLE
[Renderer] [HL25] Smoke is nonexistence with r_gamma_blend 1 in CS 1.6 and CZ on nvidia gtx 1060

### ISSUE THREAD

**Issue by rbar1um43** [hzqst/MetaHookSv#362]
HL 25 build 9920
MetaHookSv version [v20240114d]

CS 1.6 r_gamma_blend 1
![20240114175953_1](https://github.com/hzqst/MetaHookSv/assets/56739369/b1143966-50bf-4d60-ba73-cb2a10b6c7bc)

r_gamma_blend 0
![20240114175928_1](https://github.com/hzqst/MetaHookSv/assets/56739369/7dcde64f-c2aa-4108-859f-603fc54b09ff)

CZ r_gamma_blend 1
![20240114175015_1](https://github.com/hzqst/MetaHookSv/assets/56739369/286308da-523b-4c54-b45a-78f427993f45)

r_gamma_blend 0
![20240114175044_1](https://github.com/hzqst/MetaHookSv/assets/56739369/99b504ef-b18a-4cfd-9ee3-94d8f91a4a8c)

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240115b
<img width="811" alt="2024-01-15 220415" src="https://github.com/hzqst/MetaHookSv/assets/12287588/0f8ab582-26bb-49d1-aa21-716cba25eefe">
