### ISSUE TITLE
[BP] Ragdolls replaced by static corpse when model is changed

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#365]
New changed model has ragdoll file too.

https://github.com/hzqst/MetaHookSv/assets/3608544/cc914f07-9c41-4f12-9057-23166abd055b

**Comment by hzqst** [comment]
Should've been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240116a

**Comment by di57inct** [comment]
Confirming fix ❤️
