### ISSUE TITLE
fade doesn't work

### ISSUE THREAD

**Issue by BlackShadow** [hzqst/MetaHookSv#37]
r_shadow_fade doesn't work.

**Comment by hzqst** [comment]
The cvar parser for `r_shadow_fade` is not working correctly, Next update will fix this.

**Comment by BlackShadow** [comment]
some HDR commands doesn't work as well. It may be better to check every cvar.

**Comment by BlackShadow** [comment]
Also when you change shadow values such as angle etc... It won't apply until level restart.

**Comment by hzqst** [comment]
Should be fixed incb68ba31afab4d5147660dc464c60a165bfa714c.
Changes to some of the cvars will not take effect immediately, unless using `r_reload` to force those cvars being reloaded.
