### ISSUE TITLE
[Renderer] Crash when trying to launch CS on engine 8684

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#381]
MH version [v20240122a](https://github.com/hzqst/MetaHookSv/releases/tag/v20240122a)
![image](https://github.com/hzqst/MetaHookSv/assets/3608544/64196f8b-425d-40f7-86e1-44dc80f699ee)
![image](https://github.com/hzqst/MetaHookSv/assets/3608544/31289801-b605-4312-8e68-718867572b1e)

**Comment by di57inct** [comment]
nvm im an idiot

**Comment by asdian** [comment]
bump, how did you fix that? i have that same Win32Error = 126 popup
