### ISSUE TITLE
Player colors not functioning correctly

### ISSUE THREAD

**Issue by Ryor97** [hzqst/MetaHookSv#383]
On a player model with topcolor and bottomcolor parts, both parts gets painted with the topcolor, and bottomcolor gets just ignored.
Tried running the game without metahook, and the issue was gone.
This also wasnt present in older versions of metahook.
![color](https://github.com/hzqst/MetaHookSv/assets/157422428/7809a71d-0b4e-4c22-b836-f1e80d5eb841)
as seen on this image, when i set topcolor to 170 (blue), the entire model becomes blue, and not only the parts that are supposed to.
when i change bottomcolor, nothing happens.

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240124a
