### ISSUE TITLE
[Renderer] Sprite render issue

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#392]
> Protocol version 48
> Exe version 1.1.2.7/Stdio (cstrike)
> Exe build: 19:53:27 Aug  3 2020 (8684)

> |index|api|             plugin name|          plugin version|
> |    0| v2|   Gmcx_model_effect.dll|                        |
> |    1| v4|         ThreadGuard.dll|     2024-01-31T12:29:19|
> |    2| v4|     PrecacheManager.dll|     2024-01-31T12:28:26|
> |    3| v4|        StudioEvents.dll|     2024-01-31T12:29:16|
> |    4| v4|  BulletPhysics_AVX2.dll|     2024-01-31T12:27:32|
> |    5| v4|       Renderer_AVX2.dll|     2024-01-31T12:24:02|
> |    6| v4|          CaptionMod.dll|     2024-01-31T12:28:01|
> |    7| v4|      VGUI2Extension.dll|     2024-01-31T12:27:39|

Issue not present in vanilla version. Sprites and plugin can be found at https://github.com/Roccoxx/Equipment-Sprites

Metahook:
![image](https://github.com/hzqst/MetaHookSv/assets/3608544/deae739a-1faf-4515-a350-24d9bc560504)

Vanilla:
![image](https://github.com/hzqst/MetaHookSv/assets/3608544/b5f444ce-13a5-41b3-bccb-7c53d6f78ec7)

**Comment by hzqst** [comment]
You should either disable [r_sprite_lerping](https://github.com/hzqst/MetaHookSv/blob/main/docs/Renderer.md#sprite-interpolation) or set sprite framerate to 0.0 instead of 1.0

```
entity_set_float(iEnt, EV_FL_framerate, 0.0); //idk why the fuck they set this shit to 1.0 for such "static" sprites.
```
