### ISSUE TITLE
[VGUI2] Server browser auto resized and broke in CS

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#397]
All other tabs(internet, etc) have the same issue.

![image](https://github.com/hzqst/MetaHookSv/assets/3608544/db46ecb4-efe4-4327-b732-e2cf347b208a)

**Comment by hzqst** [comment]
![image](https://github.com/hzqst/MetaHookSv/assets/12287588/5c6ab0d3-eb9c-484a-bdd8-d2d5f8da7f2b)

not be able to repro this issue with official cstrike 8684

**Comment by di57inct** [comment]
Issue present on a fresh new install on steam too(legacy branch):
![image](https://github.com/hzqst/MetaHookSv/assets/3608544/8f2dfac8-0dd1-4255-83ad-220509854cf7)
![image](https://github.com/hzqst/MetaHookSv/assets/3608544/ff46e92e-faa9-44bd-8626-2b541d9702be)

**Comment by di57inct** [comment]
Confirming fix, ty
