### ISSUE TITLE
Sky bug when joining the game with r_wsurf_vbo 1

### ISSUE THREAD

**Issue by incognico** [hzqst/MetaHookSv#4]
When joining the game with `r_wsurf_vbo 1` the sky is black with strange lines:
![20210325231820_1](https://user-images.githubusercontent.com/2098066/112551272-08285e80-8dc1-11eb-8e10-802a641e85c2.jpg)

After toggling `r_wsurf_vbo` (`r_wsurf_vbo 0;r_wsurf_vbo 1`) the problem is solved and the sky is normal again. It only happens when joining a server with it enabled.

**Comment by incognico** [comment]
Just updated to the latest build, it seems fixed?

**Comment by hzqst** [comment]
> Just updated to the latest build, it seems fixed?

Yes I reverted the "projection-camera sky surface" back to "legacy skybox" in the latest build.
