### ISSUE TITLE
Possible to launch metahook through Steam?  (re: renaming metahook.exe to hl.exe?)

### ISSUE THREAD

**Issue by sofakng** [hzqst/MetaHookSv#415]
I'm running metahook through WINE (Crossover/macOS) and it's working great but I was wondering if I could launch it using Steam directly.  (ie. clicking Half-Life and [Play])

For example, can I rename hl.exe to something else and then rename metahook.exe to hl.exe?

This would make it much easier to start and I believe the arguments (-insecure and -game) could be added using the Steam launch arguments.

The reason this would be nice is because it wouldn't require separate shortcuts but more importantly these are difficult to create on Crossover (it's a pain).

**Comment by hzqst** [comment]
> For example, can I rename hl.exe to something else and then rename metahook.exe to hl.exe?

ofc you can, this is what i've done with svencoop.exe

**Comment by sofakng** [comment]
ok - thanks!  I thought metahook.exe called hl.exe but it looks like metahook.exe replaces hl.exe.

thanks again!
