### ISSUE TITLE
[Error] Texture Gamma and Lightmap Gamma Settings Reset Upon Game Restart

### ISSUE THREAD

**Issue by Zerahfys** [hzqst/MetaHookSv#419]
With MetahookSV v20240302a, I encounter an issue: Texture Gamma and Lightmap Gamma settings **reset** upon game launch, requiring me to constantly reconfigure these parameters.

Is there a way to set these launch parameters when starting the game or another solution?

Sample video: https://youtu.be/aTN5R2RncJE

**Comment by hzqst** [comment]
Those cvars are not saved by vanilla engine even if metahook is not installed aren't they?

**Comment by Zerahfys** [comment]
Yes, apparently that's what's happening. I reinstalled the game and replaced the config.cfg file with the default one. However, I still can't get those cvars (Texture and Lightmap Gamma) to stay saved. I don't know why this issue occurs only with those parameters.

**Comment by hzqst** [comment]
> Yes, apparently that's what's happening. I reinstalled the game and replaced the config.cfg file with the default one. However, I still can't get those cvars (Texture and Lightmap Gamma) to stay saved. I don't know why this issue occurs only with those parameters.

Probably because Valve just don't want other guys to change those cvars in the first place.
