### ISSUE TITLE
SSAO Problem

### ISSUE THREAD

**Issue by BlackShadow** [hzqst/MetaHookSv#42]
![20210801104140_1](https://user-images.githubusercontent.com/30868395/127763341-7b3ac5e1-6fe1-4b64-aaf6-c3b762663a20.jpg)

**Comment by hzqst** [comment]
you might see black pixel fighting on wall or terrain if your defalt_fov is not 90. you have to either turn SSAO off or change default_fov back to 90
I will see if there is any solution to mitigate the problem.

**Comment by hzqst** [comment]
Fixed in 14c8918ac1b4f45ddd44763f0d171ba956855537

**Comment by hzqst** [comment]
Still got this issue when scoping.

**Comment by hzqst** [comment]
fov is clamped to `50 ~ 90` for SSAO (SSAO will not work when fov is out of range) now.
