### ISSUE TITLE
[Renderer]No skybox when playing some of third-party maps

### ISSUE THREAD

**Issue by ebrontower** [hzqst/MetaHookSv#421]
![JM_alaska0019](https://github.com/hzqst/MetaHookSv/assets/43536516/41da0055-cd77-4343-9a82-896a6005eb7e)
As it shows there should be a skybox like that one in de_dust2 but it turns totally dark when Renderer.dll activated

**Comment by hzqst** [comment]
所以你不把地图发出来我怎么复现问题呢？

**Comment by rbar1um43** [comment]
Found that map https://gamebanana.com/mods/360136

**Comment by hzqst** [comment]
> Found that map https://gamebanana.com/mods/360136

换了两个显卡（N卡和A卡）和两个游戏版本（8684和9920）都完全无法复现。

![image](https://github.com/hzqst/MetaHookSv/assets/12287588/663ae3f6-350c-4f8a-9f4a-51f0912197d1)
<img width="1264" alt="屏幕截图 2024-03-17 234807" src="https://github.com/hzqst/MetaHookSv/assets/12287588/6a41f452-3170-4e8d-a227-ddb0df770a37">

**Comment by di57inct** [comment]
> As it shows there should be a skybox like that one in de_dust2

Not really

> SKY:  snowrt, snowbk, snowlf, snowft, snowup, snowdn

Also works fine for me but i'm using previous version right now.
```
] mh_pluginlist 
|index|api|             plugin name|          plugin version|
|    0| v2|   Gmcx_model_effect.dll|                        |
|    1| v4|         ThreadGuard.dll|     2024-02-27T03:45:43|
|    2| v4|     PrecacheManager.dll|     2024-02-27T03:44:50|
|    3| v4|        StudioEvents.dll|     2024-02-27T03:45:40|
|    4| v4|  BulletPhysics_AVX2.dll|     2024-02-27T03:43:56|
|    5| v4|       Renderer_AVX2.dll|     2024-02-27T03:40:29|
|    6| v4|          CaptionMod.dll|     2024-02-27T03:44:26|
|    7| v4|      VGUI2Extension.dll|     2024-02-27T03:44:03|
```

The map has some issues when being started via HLDS though:
![image](https://github.com/hzqst/MetaHookSv/assets/3608544/e83230dc-b370-4d53-8d5a-52b71d0cfb6a)

**Comment by hzqst** [comment]
ok找到问题了，那个整合包的作者把`env/gfx/snow**.tga`给删了导致那张图加载不到正确的天空贴图，原版引擎默认在找不到天空贴图的情况下会fallback到`desert**.tga/desert**.bmp`，而Renderer不会。

![image](https://github.com/hzqst/MetaHookSv/assets/12287588/cf92bc2b-fd53-4db9-831b-557a79cf1d72)

Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240318b
