### ISSUE TITLE
[Renderer] Fog isn't working

### ISSUE THREAD

**Issue by HowaitoHaato** [hzqst/MetaHookSv#424]
Basically what the title says, here's a video of it on restriction07.

https://github.com/hzqst/MetaHookSv/assets/129798156/ea128aca-9abc-4a45-af7e-08b87cdfeabf

Here's a pic of the same map, but without the renderer active.

![20240317222303_1](https://github.com/hzqst/MetaHookSv/assets/129798156/e5b3f0fd-0b64-4a6d-8023-f0e5fdad8f44)

My GPU is an RX 570 8gb
And here is what my plugins.lst looks like:

VGUI2Extension.dll
CaptionMod.dll
Renderer.dll
;BulletPhysics.dll
StudioEvents.dll
PrecacheManager.dll
CommunicationDemo.dll
SCModelDownloader.dll
;SteamScreenshots.dll
ThreadGuard.dll
SCCameraFix.dll

**Comment by hzqst** [comment]
Fixed in the latest commit.

https://github.com/hzqst/MetaHookSv/releases/tag/v20240318a
