### ISSUE TITLE
[Renderer] Fog doesn't hide the skybox at all

### ISSUE THREAD

**Issue by HowaitoHaato** [hzqst/MetaHookSv#425]
Tried out the new version, and now the fog works, but sadly it doesn't seem to work properly, as it doesn't seem to hide the skybox at all, making it look really ugly.

![20240318175826_1](https://github.com/hzqst/MetaHookSv/assets/129798156/b9da1cc1-5f8e-4922-b84d-5c09b1a12087)

**Comment by hzqst** [comment]
You can enable sky fog by `r_wsurf_sky_fog 1`

**Comment by HowaitoHaato** [comment]
Alright, thanks, that solves that issue. 
But now I'm having another issue, not sure if it's related to this or not, should I create another thread for it so you can better keep track of it? But it seems that in maps that have no fog, the screen goes black except for my weapon and some sprites. Here's an example of it on Stadium4

![20240319015347_1](https://github.com/hzqst/MetaHookSv/assets/129798156/c786323d-2b76-4254-baee-9368eeb82ba1)

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240319a.

**Comment by HowaitoHaato** [comment]
Thanks. No more issues with fog from what I tried so far.
