### ISSUE TITLE
infected files

### ISSUE THREAD

**Issue by janiowy** [hzqst/MetaHookSv#426]
I think the MetaHookSv-windows-x86.zip is infected with a virus, when I download the file, my windows defender blocks the download and says it is a trojan. this happens with all versions. please check it out

**Comment by hzqst** [comment]
> I think the MetaHookSv-windows-x86.zip is infected with a virus, when I download the file, my windows defender blocks the download and says it is a trojan. this happens with all versions. please check it out

false positive from the retard Micro$oft defender.
