### ISSUE TITLE
R_StudioFindVBOCache: invalid index

### ISSUE THREAD

**Issue by SonThanhVN** [hzqst/MetaHookSv#429]
i recently have this error when joining or entering a map
![image](https://github.com/hzqst/MetaHookSv/assets/46934330/ae619b94-7676-48c0-bd2f-6fa0d751c1da)

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240401a

**Comment by SonThanhVN** [comment]
I will try when im home
