### ISSUE TITLE
Zoomed screen issue

### ISSUE THREAD

**Issue by BlackShadow** [hzqst/MetaHookSv#43]
I don't know if this is a MetaHook (but i believe it is) problem but for some users screen starts zoomed for some reason.

Changing size of text, apps and other items to %100 in Windows Display Settings fixes the issue mostly.

**Comment by hzqst** [comment]
current desktop DPI not 100%?

**Comment by BlackShadow** [comment]
This still happens people with %100 DPI i believe.

**Comment by hzqst** [comment]
How to reproduce?

**Comment by BlackShadow** [comment]
![image](https://user-images.githubusercontent.com/30868395/127810861-3ccecbfa-b8ae-4a95-8a56-fb8c1044a503.png)

Change your DPI to 125 or higher

**Comment by hzqst** [comment]
Can't repro with 125% DPI, are you playing with mutiple monitors?

**Comment by BlackShadow** [comment]
Yes i have double monitors. But this issue happened on another device which was a laptop and using %100 DPI. This bug is really hard to re-produce changing DPI %100 doesn't fix always.

**Comment by hzqst** [comment]
I've changed ordinary DPI-awareness to per-monitor DPI-awareness in the latest commit.

**Comment by BlackShadow** [comment]
Testing now... Actually even if it works for me i'm not sure if this fix will works for other people. If it works for me i'll close this issue for now until if people still complains about it.

**Comment by BlackShadow** [comment]
Tested on every DPI, seems working for me. Closing this for now.
