### ISSUE TITLE
[Renderer] Weird black particles/sprites when headshotting with the sniper rifle, and in general with scripted weapons

### ISSUE THREAD

**Issue by HowaitoHaato** [hzqst/MetaHookSv#430]
This has actually been happening for a while to me, but since it was something minor I never got around reporting it, but lately I have been playing with scripted weapons and with those it's a a lot more annoying. 
But basically, there seems to be some weird broken black particle or sprite when headshotting with the sniper rifle, or shooting anything in general with scripted weapons, see the videos:

https://github.com/hzqst/MetaHookSv/assets/129798156/010ea5cc-782f-4c68-9cae-ffb4b547ed83

https://github.com/hzqst/MetaHookSv/assets/129798156/abeeced5-869f-42fa-b08f-03c67bb2dd0b

https://github.com/hzqst/MetaHookSv/assets/129798156/d3816fa2-2865-4b98-b875-eadb4ac7125d

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240404a

**Comment by HowaitoHaato** [comment]
Seems to work just fine, thanks.
