### ISSUE TITLE
[HL25] Configuration panel is too big even with -no_high_dpi

### ISSUE THREAD

**Issue by rbar1um43** [hzqst/MetaHookSv#431]
![изображение](https://github.com/hzqst/MetaHookSv/assets/56739369/22130791-4bd7-497a-9d79-d9706badc697)

**Comment by rbar1um43** [comment]
Resolution is 2560x1440

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240423a
