### ISSUE TITLE
[Renderer] issues for Sven crashed/freeze and hang for AMD user

### ISSUE THREAD

**Issue by Ryuknosuke** [hzqst/MetaHookSv#434]
When i start Sven Co-op suddenly my Sven freeze getting white screen/not responding and my **AMD** appear like this

![image](https://github.com/hzqst/MetaHookSv/assets/151928131/f0b094a5-b6e8-4b10-be0d-3f18369b8e5a)

![image](https://github.com/hzqst/MetaHookSv/assets/151928131/50d59439-442b-4938-8256-b9ad3389612a)

**Comment by Ryuknosuke** [comment]
Solved by decreasing

- [ ] Graphics: Decal limit 300.000000
- [ ] Graphics: Particle limit 300.000000

**Comment by KaniEMUACH** [comment]
Did you fix it?
