### ISSUE TITLE
plese fix

### ISSUE THREAD

**Issue by janiowy** [hzqst/MetaHookSv#436]
plese fix the false virus error
(i cant even download the metahooksv because my defender blocks it)
![image](https://github.com/hzqst/MetaHookSv/assets/164049522/f24f4386-df0c-48ef-855f-28e83c94f39e)
![image](https://github.com/hzqst/MetaHookSv/assets/164049522/dee0af6a-b393-44ef-9fdb-9568180c08d5)
![image](https://github.com/hzqst/MetaHookSv/assets/164049522/047bb42f-8e69-452a-b331-e9a233f5ca01)
![image](https://github.com/hzqst/MetaHookSv/assets/164049522/8f067037-7031-41c7-8c19-915122b31128)
and many more:
![image](https://github.com/hzqst/MetaHookSv/assets/164049522/a1cc3901-49aa-4ad0-833c-e61b7f025fe6)
(only metahooksv)

sory for polish language on screenshots

**Comment by hzqst** [comment]
You should either report the false positive to Microsoft [here](https://www.microsoft.com/en-us/wdsi/filesubmission/) or compile from source code by yourself.
