### ISSUE TITLE
Black Texture issue

### ISSUE THREAD

**Issue by BlackShadow** [hzqst/MetaHookSv#44]
Textures going black randomly, mostly happens after level change. (GoldSrc)

![image](https://user-images.githubusercontent.com/30868395/127776070-1054981f-11c7-4a44-9e8a-18d220ae0666.png)

How to reproduce:

Just go to map c1a0b from c1a0a, you'll see the changed goes to black.

**Comment by BlackShadow** [comment]
Side note: Screen goes black for a second during level change.

**Comment by hzqst** [comment]
Issue with black texture (black lightmap indeed) should be fixed in latest commit

**Comment by BlackShadow** [comment]
Yes this one's fixed. But during level changes screen still goes black for a second.
