### ISSUE TITLE
[renderer] freeimage.dll version mismatch, expect "3.18.100" got "3.17.0"! error in new version

### ISSUE THREAD

**Issue by DudeWithTheFood** [hzqst/MetaHookSv#443]

**Comment by hzqst** [comment]
Remove the deprecated version of FreeImage dll from there: `\SteamLibrary\steamapps\common\Sven Co-op\FreeImage.dll`

**Comment by DudeWithTheFood** [comment]
> Remove the deprecated version of FreeImage dll from there: `\SteamLibrary\steamapps\common\Sven Co-op\FreeImage.dll`

i'm using half-life. not sven

**Comment by hzqst** [comment]
> \SteamLibrary\steamapps\common\Sven Co-op\FreeImage.dll

it's `\SteamLibrary\steamapps\common\Half-Life\FreeImage.dll` then
