### ISSUE TITLE
切换地图出现人物模型消失的情况

### ISSUE THREAD

**Issue by ManevogerKrCode** [hzqst/MetaHookSv#444]
玩了一会换服务器或者说重新进去会出现人物模型消失的情况 然后我自己clone项目debug了一下 只知道注释掉hook r_gldrawpoint以后会显示模型 不过黑不溜秋的 看不懂那个函数里面的代码没学过这些渲染类的东西

**Comment by hzqst** [comment]
需要详细复现方法
