### ISSUE TITLE
Not work in Sven Coop and CS 1.6

### ISSUE THREAD

**Issue by MysticDeathProject** [hzqst/MetaHookSv#445]
Hi latest updates have viruses? I don't know how to fix it because in my antivirus haven't restore files and backup need turn off antivirus but when I again start windows then again failes removes can you fix it please because I still sit on the windows 7 and I need antivirus

![image](https://github.com/hzqst/MetaHookSv/assets/22016802/4567e844-7e8c-4e5b-adf9-cf5b326b95b1)

**Comment by hzqst** [comment]
it's false positive. build from source code by yourself and see if it still reports virus.

**Comment by MysticDeathProject** [comment]
Hi I tried to compile by myself there have errors with compilling on vs2022 there writting error how I can adding to you on the steam and discord can you help me please, I want play with this mod this mod is amazing on Sven Coop and CS 1.6 and Half-Life

**Comment by MysticDeathProject** [comment]
My discord Mysticpawn#2073 please add me
