### ISSUE TITLE
[BP] Fatal Error while you kill many zombie

### ISSUE THREAD

**Issue by Rikunosukee** [hzqst/MetaHookSv#446]
![image](https://github.com/hzqst/MetaHookSv/assets/151928131/53e12891-007a-4ecb-b394-ec99cfdac258)

This almost happen every map that had many `zombie_ragdoll` you kill
which map are including 
http://scmapdb.wikidot.com/map:robination
http://scmapdb.wikidot.com/map:infested also happen in infested2

**Comment by hzqst** [comment]
Could it be an out-of memory error?

**Comment by hzqst** [comment]
Fixed since BulletPhysics has been refactored.
