### ISSUE TITLE
Can't mute anyone (Scoreboard mute is bypassed)

### ISSUE THREAD

**Issue by LingKuja** [hzqst/MetaHookSv#447]
For some reason, having this mod prevents you to mute voice chat by some players (scoreboard muting), despite the button being there and the icon clearly showing that the user was muted, you can still hear their audio.

Replicating the issue is easy: just mute anyone on the scoreboard and you'll still hear them, they just won't pop up on the screen.

**Comment by hzqst** [comment]
Should've been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240610a

**Comment by LingKuja** [comment]
that seems to have fixed the issue, thanks.
But there is a new issue whereas it fails to recognize the renderer.dll, and for some reason there was a "VGUI2Extension" dll in the plugins.lst but there was no signs of the file on the plugins folder.

**Comment by LingKuja** [comment]
I tried to compile the latest version, since it's just the VGUI2Extention.dll that keeps messing up and it come up with this error
![cmd_2024-06-11_14-26-54](https://github.com/hzqst/MetaHookSv/assets/35222780/277d3522-09a2-48fa-965f-55e7519f0233)

I have installed cmake, git for windows, and the build tools (msvc143 latest)

**Comment by hzqst** [comment]
> I tried to compile the latest version, since it's just the VGUI2Extention.dll that keeps messing up and it come up with this error ![cmd_2024-06-11_14-26-54](https://private-user-images.githubusercontent.com/35222780/338581721-277d3522-09a2-48fa-965f-55e7519f0233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTcyNDksIm5iZiI6MTcxODExNjk0OSwicGF0aCI6Ii8zNTIyMjc4MC8zMzg1ODE3MjEtMjc3ZDM1MjItMDlhMi00OGZhLTk2NWYtNTVlNzUxOWYwMjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE0NDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3OGE5ODJjMjlhNjZhM2MyYmNlODMzZWM4MGEyOWQ5NTM0OWU5MmI0NGYxYzU2NWViYzkwYTM3OTFjODYyNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cpnAbOKMyXuFn21d-eAZqTFHmtJLnqrFfWSlqnbT88w)
> 
> I have installed cmake, git for windows, and the build tools (msvc143 latest) I would upload a log directly if I knew where it dumped it

Fixed in the latest commit.

**Comment by LingKuja** [comment]
Can confirm, just built it took and everything seems to work fine except for an error with ResourceReplacer. But since I don't use it, it's alright on my end. Thank you for you work.

![image](https://github.com/hzqst/MetaHookSv/assets/35222780/ef9a317a-42aa-4f14-9713-0b30800a8e15)
