### ISSUE TITLE
Visual Studio 2022 - MetaHook Project issue

### ISSUE THREAD

**Issue by BlackShadow** [hzqst/MetaHookSv#45]
MetaHook.sln  - MetaHook-DLL.sln doesn't seem to be working. Solutions opens unloaded

![image](https://user-images.githubusercontent.com/30868395/127847198-19b9f765-015d-4d83-938d-e2f83a50790c.png)

**Comment by BlackShadow** [comment]
![image](https://user-images.githubusercontent.com/30868395/127847416-a0745c8f-0872-4cdc-9a6c-b5a8a0facbf7.png)


Can't reload because global.props is missing.

**Comment by hzqst** [comment]
Did you run `build-initdeps.bat`? according to _Build Instruction_ you have to run `build-initdeps.bat` before everything.

**Comment by BlackShadow** [comment]
Oops i forgot to do it in new build.
