### ISSUE TITLE
关于新纹理

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#450]
一年多没有测试新功能，请问支持4096的纹理是直接可以加载含有4096尺寸的贴图的wad吗，还是依然需要外部加载

**Comment by q52888940** [comment]
我可能没说清楚我的意思，我的意思是可以直接在wad里放置超过512的贴图制作地图并且被游戏加载吗，支持除原版bmp以外的贴图格式吗，如jpg

**Comment by hzqst** [comment]
wad里面本身就存储的是带调色板的原始颜色数据。跟bmp、png这些文件格式有什么关系？难道你认为wad是一个压缩包，可以随便往里面压缩进各种各样的文件？

wad格式本身支持保存多大的图我不清楚，反正renderer接管之后的贴图加载器本身是支持最大4096x4096的图，不管这个256色位图的原始数据来自mdl还是wad还是spr（前提是你的工具能在不报错的前提下制作得出这么大的图）
