### ISSUE TITLE
ResourceReplacer在cs中不可用

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#453]
无任何效果，版本8684，cs零点行动

**Comment by hzqst** [comment]
我这边测试没问题啊？

**Comment by q52888940** [comment]
[#de_game_test_.txt](https://github.com/user-attachments/files/16390402/de_game_test_.txt)
因为不能上传后缀gmr的文件，所以转txt了，我放在了maps里
最新版的压缩包里没有此插件，我是从前面几个版本找的这个插件装上去的，没有效果

**Comment by hzqst** [comment]
“针对地图替换模型文件的功能” 只在 “进入他人服务器” 时可用，在本地建房时不可用。

原因如下：

本地建房时、服务端和客户端共享同一个缓存的模型池。

服务端在.gmr文件还未加载时就已经提前预缓存了所有cs中可能用到的模型。（在“本地客户端”连上“本地服务器”之后才会读取gmr列表）

等客户端加载完gmr列表，客户端发现预缓存池里已经有v_xxx.mdl了，就不会再从磁盘加载一遍v_xxx.mdl，也就不会触发ResourceReplacer.dll的替换行为了。

说到底，ResourceReplacer作为MetaHook的插件，本来就不应该干涉跟服务端有关的任何东西。如果需要本地建房也能替换模型，理论上就是应该用amxx或者修改mp.dll之类的手段，在服务端层面完成替换。
