### ISSUE TITLE
cstrike 4554 (no steam) PrecacheManager Could not found S_LoadSound

### ISSUE THREAD

**Issue by Tzvisapp** [hzqst/MetaHookSv#455]
![image](https://github.com/user-attachments/assets/cf374a56-a101-4efb-a6cd-dddc4c2d984e)
Precache manager causing problems
new issue or old?
thanks

**Comment by hzqst** [comment]
![](https://github.com/user-attachments/assets/f0c7a345-1b03-485f-a911-305570c93793)

**Comment by Tzvisapp** [comment]
Yeah, I am using this.. idk what is wrong..

**Comment by hzqst** [comment]
This mean you were running an old version, the error string `[PrecacheManager] Could not found: S_LoadSound` is not even a thing in the latest binaries.

**Comment by Tzvisapp** [comment]
^ weird..
I'll compile the binaries myself then.
