### ISSUE TITLE
请求让地图中某些模型不显示阴影

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#457]
在制作地图时有一些模型我不想让他显示阴影，以前的方法是修改渲染模式，但现在有一些模型因为更改渲染模式后会变得很奇怪，所以请求一个功能 设置地图某个模型不渲染阴影.

另外我尝试在CS中使用超过512尺寸贴图的模型成功了，但超过512(1024)的地图贴图被游戏弹窗拒绝进入

**Comment by hzqst** [comment]
<img width="308" alt="image" src="https://github.com/user-attachments/assets/a2b68502-7953-4676-a434-63e1aca0879a">

高级模式-->手动添加键值对"effects" "8192"

地图贴图不清楚，可能wad格式本身的问题，也可能跟地图的编译器（hlvis / hlrad）有关系

**Comment by q52888940** [comment]
![M4%HP24(K)X4O02EH{XXKAE](https://github.com/user-attachments/assets/e60f6a0e-7248-4f78-9f46-9fa2cdd4463a)
CZERO测试没有效果,即便实体为CYCLER

**Comment by hzqst** [comment]
czero / cstrike的默认设置最多只允许服务端传输8bits（也就是0~255）的effects这项属性给客户端

见

`\steamapps\common\Half-Life\cstrike\delta.lst`

```
entity_state_t gamedll Entity_Encode
{
...
DEFINE_DELTA( effects, DT_INTEGER, 8, 1.0 ),
...
}
```

将其中的8改为13（因为2的13次方刚好等于8192）或者更大的数字（比如16）即可解决服务端effects=8192无法传输到客户端的问题。
（警告：修改delta.lst后的客户端无法与原版无修改的客户端联机，也无法进入原版未修改delta.lst的服务器。修改delta.lst后的服务器无法为原版无修改的客户端提供服务。也就是说客户端和服务端的delta.lst设定必须保持完全一致才能互通）

**Comment by q52888940** [comment]
再次失败..

**Comment by q52888940** [comment]
更换ENV_SPRITE实体解决
