### ISSUE TITLE
spr透明度错误

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#458]
![}()$JJJ7ZO6 RZPUO9Z(4QS](https://github.com/user-attachments/assets/7f79ae58-4b88-4f69-bc09-882f4bff68c3)

CZERO 8684 关闭FXAA或HDR会出现这种情况
N卡

**Comment by hzqst** [comment]
相同场景AMD和INTEL的独显集显均无法复现，只能在N卡上复现，所以我的结论是这是老黄家显卡驱动特有bug，建议找老黄去

（下方issue里只是针对特定情况的workaround，没法解决所有问题，想解决所有问题只能等nv自己把显卡驱动的问题修复了）

https://github.com/hzqst/MetaHookSv/issues/324

**Comment by q52888940** [comment]
r_gamma_blend 0 对我无效，奇怪的是FXAA或HDR开其中某一个都能解决这个问题，不然烟雾弹都是黑色的
