### ISSUE TITLE
在CS中环境遮蔽光不工作

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#464]
尽管使用AMXX插件修改服务器的FOV市场也无法工作
在CS中只有开启宽屏视野才会出现环境遮蔽
这个问题很久了
我想请求设置视场FOV功能，毕竟不是人人都喜欢宽屏视野，他的广角开的太大，在CS这种竞技游戏中很难瞄准

**Comment by q52888940** [comment]
另外我在互联网找了很久关于垂直视野的资料，还是没怎么懂，垂直视野只是拉高了屏幕垂直的FOV吗？希望得到回答

**Comment by hzqst** [comment]
1、HBAO是100%照搬的老黄的十几年前的代码（https://github.com/nvpro-samples/gl_ssao） 。那玩意有bug，在特定fov下会产生黑影artifacts，所以我对90以下的horizontal fov都屏蔽了HBAO。后面考虑换成https://github.com/NVIDIAGameWorks/HBAOPlus或者别的算法。

2、写个amxx插件发SetFOV消息不是可以随便改cs客户端的fov的吗？这个功能有什么用metahook的必要吗？

3、https://github.com/hzqst/MetaHookSv/blob/main/docs/RendererCN.md#%E5%9E%82%E7%9B%B4fov 应该写得很清楚了。
