### ISSUE TITLE
为什么light_dynamic实体不能照亮V模型

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#465]
在地图做了个测试，这个实体很强大，但是无法照亮V模型，就会显得人物模型有光，但第一人称反差的奇怪感

**Comment by hzqst** [comment]
因为viewmodel在引擎中本质上是一个在透明pass渲染的物体，所以不受延迟渲染（deferred rendering）光照影响

至于为什么一个不透明的物体会跑到透明pass去渲染？那就要问v社的脑残临时工了
