### ISSUE TITLE
当有两个模型使用一套外置贴图时，贴图变黑

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#466]
![image](https://github.com/user-attachments/assets/201f1cf2-0469-4dd0-88aa-853919c7692a)

**Comment by q52888940** [comment]
我应该修改一下标题，这个情况并不是在两个模型用一套外置贴图，而是不知道如何触发的，但都是有挂外置贴图的模型

**Comment by hzqst** [comment]
不给复现方法我怎么修？

**Comment by hzqst** [comment]
那至少给一个能让我在我本机能尝试复现（哪怕实际上没法复现）的包含模型和贴图的samples吧？

**Comment by q52888940** [comment]
[新建文件夹 (7).zip](https://github.com/user-attachments/files/16563703/7.zip)
主要是怕你麻烦
装入AMXX插件，我已经准备好了一张供你测试的地图，人物贴图人物模型，和地图中车的生成坐标，进入游戏后不要开启HDR，坐上车被置换的模型贴图全黑，如上面的图

**Comment by q52888940** [comment]
[Uploading 新建文件夹 (9).zip…]()
不用那么麻烦了，已测试一把武器模型置换贴图后不开HDR全黑

**Comment by q52888940** [comment]
FXAA或HDR开启时正常，这个也许和上次说的显卡问题是一样的问题源

**Comment by q52888940** [comment]
[Uploading 新建文件夹 (9).zip…]()
不好意思 我好像没上传上去?

**Comment by q52888940** [comment]
[Uploading mdl.zip…]()

**Comment by q52888940** [comment]
链接：https://pan.baidu.com/s/1QMqOWFPnGjV2lesLdj1t-Q 
提取码：s9mb

**Comment by q52888940** [comment]
换DDS,DXT1解决
