### ISSUE TITLE
一些功能请求

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#467]
1.能否考虑在游戏加载前或加载后添加命令允许调整外置贴图或模型内大贴图的大小，或是外置贴图的开关，GL_MAX_SIZE这个命令现在对被替换贴图的模型不可用了

2.能否考虑在CS.HL这些游戏恢复一些旧版Renderer的功能，如增加同屏可见的实体数量,3DSKY等，我相信很多人还是把Renderer用在这些游戏上而不是SVENCOOP

3.粒子效果与动态模糊

4.考虑让模型分离，如手和武器，以略过子模型选项，这样可以避免一些资源浪费，并且可以增加面值与数量

5.第一人称模型的XYZ修改

**Comment by hzqst** [comment]
1.使用cvar把贴图弄小的意义是什么？本来使用外置贴图为的就是使用大贴图，这样不是本末倒置？既然你都要限制贴图大小了你直接用原始贴图不就行了？

2.8686及以前版本服务器最多发256个实体过来，这比MAX_VISEDICTS 512 还少一半呢，改了这个你又来要求改MAX_PACKET_ENTITIES，完事了又发现MAX_TEMP_ENTITIES只有500个，又要求改MAX_TEMP_ENTITIES，这样下去没完没了了。然后你又来抬杠说9920支持到1024个MAX_PACKET_ENTITIES了，结果你发现你的其他插件在9920上面根本跑不起来。
![image](https://github.com/user-attachments/assets/6a380422-5e10-4494-8c4f-88d79744b0c4)

3.我觉得粒子系统就不是Renderer应该做的，这玩意属于客户端负责的部分，就算要做也应该单独起一个插件。但是就算这样用的人也少的可怜。况且现在这个游戏里乱七八糟的粒子引擎太多了：quake particle、TEMP ENTITY、ParticleMan.dll、sc自己的一套粒子系统，完全没必要再自己另起炉灶搞一个新的。原版的ParticleMan.dll在99%情况下都够用了。

4.没懂，意思是起源1的c_hand?

5.意义是？

**Comment by q52888940** [comment]
> 1.使用cvar把贴图弄小的意义是什么？本来使用外置贴图为的就是使用大贴图，这样不是本末倒置？既然你都要限制贴图大小了你直接用原始贴图不就行了？
> 
> 2.8686及以前版本服务器最多发256个实体过来，这比MAX_VISEDICTS 512 还少一半呢，改了这个你又来要求改MAX_PACKET_ENTITIES，完事了又发现MAX_TEMP_ENTITIES只有500个，又要求改MAX_TEMP_ENTITIES，这样下去没完没了了。然后你又来抬杠说9920支持到1024个MAX_PACKET_ENTITIES了，结果你发现你的其他插件在9920上面根本跑不起来。 ![image](https://private-user-images.githubusercontent.com/12287588/356847157-6a380422-5e10-4494-8c4f-88d79744b0c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTEwNDksIm5iZiI6MTcyMzM1MDc0OSwicGF0aCI6Ii8xMjI4NzU4OC8zNTY4NDcxNTctNmEzODA0MjItNWUxMC00NDk0LThjNGYtODhkNzk3NDRiMGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA0MzIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjYmNkOTI5ODI4YzM5Y2Y1NzJlM2I4MDEwYmQ5NjIzODU5YzJlN2M2YWM1NWYxZGRmZTJkZjgyMGQyZDU5ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JLmMVtGICq48uzD5XJc0vPyir6KD2kUGMAYbMJSZP-s)
> 
> 3.我觉得粒子系统就不是Renderer应该做的，这玩意属于客户端负责的部分，就算要做也应该单独起一个插件。但是就算这样用的人也少的可怜。况且现在这个游戏里乱七八糟的粒子引擎太多了：quake particle、TEMP ENTITY、ParticleMan.dll、sc自己的一套粒子系统，完全没必要再自己另起炉灶搞一个新的。原版的ParticleMan.dll在99%情况下都够用了。
> 
> 4.没懂，意思是起源1的c_hand?
> 
> 5.意义是？
、


4.是的，也许这样可以更省资源并且有更多的选择权利给模型作者？
好吧 关于其他的你说的是对的 但我记得用旧版的Renderer对我做的地图有帮助，当地图实体过于多的时候，他至少让我进入游戏了，而不是弹窗。 

那么3DSKY会考虑恢复吗？
