### ISSUE TITLE
[Renderer] Invisible player and view models

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#468]
Join CS server 51.195.68.15:27015 to see the bug.
Problem not present in https://github.com/hzqst/MetaHookSv/releases/tag/v20240319a

**Comment by asdian** [comment]
well, you should provide video (or details in that matter) instead, not asking him to join the server.

**Comment by di57inct** [comment]
Nothing video or screenshots would provide. Title says everything.
The view/weapon(first person) models and player models are invisible.
Using cl_minmodels 1(forcing override to default player models) doesn't fix the issue.

**Comment by hzqst** [comment]
Can't connect to 51.195.68.15, is the server still alive?
