### ISSUE TITLE
游戏中多次更换带有置换贴图或透明贴图的模型贴图会错乱

### ISSUE THREAD

**Issue by q52888940** [hzqst/MetaHookSv#471]
![image](https://github.com/user-attachments/assets/6c018053-7780-41df-b846-65f0983542fd)
在游戏中多次更换带有置换贴图的模型后，在下一次或下下次进入游戏，人物模型贴图被置换的地方换全黑或错乱，特别是在CZ任务模式转普通多人模式时BUG出险率更高

**Comment by q52888940** [comment]
图里的模型被错误贴了其他角色的置换贴图

**Comment by q52888940** [comment]
我认为这可能客户端没有快速捕捉到玩家更换了模型所以导致错乱？

**Comment by hzqst** [comment]
引擎版本？

**Comment by q52888940** [comment]
8684

> 引擎版本？

**Comment by hzqst** [comment]
控制台`developer 255`之后换图观察出现错乱的贴图的原贴图有没有被释放

注意以下查找内容：

`GL_LoadTextureEx: [models/player/你的模型/textures/你的自定义贴图.png] -> [@MDL_0950C33A_0600_0400] [311]`

其中`@MDL_0950C33A_0600_0400`是该贴图在引擎中的内部名称，311是贴图的OpenGL TextureID，你需要把控制台消息完整复制到记事本之后全文搜索该名称

如果搜到类似如下内容 `GL_FreeTextureEntry: [311] [@MDL_0950C33A_0600_0400] [1].`

则说明该贴图被意外释放了

**Comment by q52888940** [comment]
GL_LoadTexture2: Using new texture loader [models/player/Arctic/Arctic.mdlt_arctic.bmp] -> [@MDL_4F44A9B8_0200_0200] [2733]
GL_LoadTexture2: Using new texture loader [models/player/Arctic/Arctic.mdlv_hands.bmp] -> [@MDL_CEDF93E4_0200_0100] [2734]
GL_LoadTexture2: Using new texture loader [models/player/Arctic/Arctic.mdlanfrien_shephardeyeball_l.bmp] -> [@MDL_8BE4BE27_0080_0080] [2735]
GL_LoadTexture2: Using new texture loader [models/player/Arctic/Arctic.mdlanfrien_shephardeyeball_r.bmp] -> [@MDL_E2D8027A_0080_0080] [2736]
GL_LoadTexture2: Using new texture loader [models/player/Arctic/Arctic.mdlanfrien_shephardglass.bmp] -> [@MDL_8BFD8525_0100_0080] [2737]
GL_LoadTexture2: Using new texture loader [models/player/Arctic/Arctic.mdlanfrien_shephardhelmet.bmp] -> [@MDL_678037F0_0080_0040] [2738]
GL_LoadTexture2: Using new texture loader [models/player/Arctic/Arctic.mdlBackpack1.BMP] -> [@MDL_AA1E1AFB_0100_0100] [2739]
GL_LoadTexture2: Using new texture loader [models/player/Arctic/Arctic.mdlGrunt_Head_Skimask.bmp] -> [@MDL_73B1C42B_0200_0100] [2740]
GL_LoadTexture2: Using new texture loader [models/player/Arctic/Arctic.mdlGrunt_Vest_01.bmp] -> [@MDL_EF201297_0200_0200] [2741]
GL_LoadTexture2: Using new texture loader [models/player/Arctic/Arctic.mdlGrunt_OP4_Misc_Shared.bmp] -> [@MDL_D2E2C1BC_0200_0200] [2883]
GL_LoadTexture2: Using new texture loader [models/player/Arctic/Arctic.mdlGrunt_Rucksack.bmp] -> [@MDL_3AE1513C_0200_0100] [2884]
GL_LoadTexture2: Using new texture loader [models/player/Arctic/Arctic.mdlCT_CAP_Male.bmp] -> [@MDL_C3A40A29_0100_0100] [2885]
GL_LoadTextureEx: [renderer/texture/player/arctic/t_arctic.dds] -> [@MDL_92C0319A_0800_0800] [2886]
GL_LoadTextureEx: [renderer/texture/player/arctic/v_hands.dds] -> [@MDL_25BADAEB_0400_0200] [2887]
GL_LoadTextureEx: [renderer/texture/player/arctic/anfrien_shephardhelmet.dds] -> [@MDL_3A6AD4E1_0400_0200] [2888]
GL_LoadTextureEx: [renderer/texture/player/arctic/anfrien_shephardhelmet_NORMAL.dds] -> [@MDL_98C9D861_0400_0200] [2889]
GL_LoadTextureEx: [renderer/texture/player/arctic/anfrien_shephardhelmet_SPECULAR.dds] -> [@MDL_CFE314C9_0400_0200] [2890]
GL_LoadTextureEx: [renderer/texture/player/arctic/t_arctic_NORMAL.dds] -> [@MDL_DBBCFCB4_0800_0800] [2891]
GL_LoadTextureEx: [renderer/texture/weapon/hand/v_hands_NORMAL.dds] -> [@MDL_61034F6E_0400_0200] [2892]
GL_LoadTextureEx: [renderer/texture/player/arctic/anfrien_shephardglass_NORMAL.dds] -> [@MDL_66AD7B99_0100_0080] [2893]
GL_LoadTextureEx: [renderer/texture/player/arctic/anfrien_shephardglass_SPECULAR.dds] -> [@MDL_26DC0CEB_0100_0080] [2894]
这是进入游戏后控制台出现的关于这个变黑的模型的贴图数据，奇怪的是虽然错乱的不止它一个，但是控制台只给我打印了它的

**Comment by hzqst** [comment]
没有任何GL_FreeTextureEntry的记录？

**Comment by q52888940** [comment]
这是所有关于模型的控制台记录，我的每个角色模型以及子模型都有大量的外置贴图，我甚至把所有贴图都转为DXT1模式以防是和透明贴图功能冲突（上次提到的）

> 没有任何GL_FreeTextureEntry的记录？

**Comment by q52888940** [comment]
这个BUG在老版本其实也出现过，我N卡2060，驱动是最新版的，不知道是显卡的原因还是什么，但是以前关于提到过得BUG开启FXAA都可以解决

**Comment by q52888940** [comment]
且 我目前认为触发的原因是当玩家死亡突然复活或突然更换模型之类的会引发

**Comment by hzqst** [comment]
这里建议你拉取最新的代码之后把`/Plugins/Renderer/gl_rmain.cpp` 第2652~2660行删掉再自己编译一份试试，我觉得根据描述大概率是这里的问题。
<img width="463" alt="image" src="https://github.com/user-attachments/assets/02d3208e-30fc-4c1a-901b-528a8dfe7f48">

**Comment by hzqst** [comment]
建议试试这个版本 https://github.com/hzqst/MetaHookSv/releases/tag/v20240916a
