### ISSUE TITLE
Afraid of Monsters: Director's Cut, crash due to "g_pGameStudioRenderer"

### ISSUE THREAD

**Issue by Blackgrowl** [hzqst/MetaHookSv#472]
Afraid of Monsters: Director's Cut causes a crash if you use "Renderer.dll" with it, the crash appears as seen in this picture:
![image](https://github.com/user-attachments/assets/a5120cee-85bc-4592-9e15-c203a2574f1a)

Transcripted:
[Renderer] Could not found: g_pGameStudioRenderer
Engine buildnum: 9920

You can get the mod from here:
https://www.moddb.com/mods/afraid-of-monsters/downloads/half-life-afraid-of-monsters-director-s-cut

**Comment by q52888940** [comment]
I think it's because this MOD uses their own renderer

**Comment by Blackgrowl** [comment]
> I think it's because this MOD uses their own renderer

I think you are right, AoM does have some 4:3 black borders and sometimes even a TV Noise for cutscene effects.
I don't suppose you know how to fix this? If it means removing those cutscene effects, that's fine by me.

**Comment by hzqst** [comment]
Done in https://github.com/hzqst/MetaHookSv/releases/tag/v20240827b

**Comment by Blackgrowl** [comment]
> Done in https://github.com/hzqst/MetaHookSv/releases/tag/v20240827b

Hey, thank you very much for this, this even fixed the crash in the mod "Black Guard", which coincidentally also used engine buildnum 9920

I have one question though, it seems that the Flashlight in AoM is still the original one, is there any command I have to use to get the one from MetaHook?
![image](https://github.com/user-attachments/assets/f006d733-0ca0-451f-bd79-e35415e20e1b)
