### ISSUE TITLE
[Caption Mod - Improvement] Subtitle box

### ISSUE THREAD

**Issue by BlackShadow** [hzqst/MetaHookSv#48]
Subtitles box could be a little bit smaller. It takes half of the space when dialogues are stacked.

![image](https://user-images.githubusercontent.com/30868395/127998712-4774b5bc-0327-43b3-a428-1f7cef1f334a.png)

**Comment by hzqst** [comment]
The size and position of subtitle box could be modified in `svencoop/captionmod/SubtitlePanel.res` -> `xpos` `ypos` `wide` `tall`

**Comment by BlackShadow** [comment]
Closing this since it's customizable.
