### ISSUE TITLE
[Caption Mode - Chat] # symbol crashes game

### ISSUE THREAD

**Issue by BlackShadow** [hzqst/MetaHookSv#49]
Typing # symbol first appears blank on chat but if you use more than 1 # symbol game crashes

**Comment by hzqst** [comment]
Should be fixed in latest commit.

**Comment by BlackShadow** [comment]
For some reason when i click anything on the menu or open a map from console game crashes

**Comment by BlackShadow** [comment]
MetaHookSv\Plugins\CaptionMod\SourceSDK\mathlib\sse.cpp(62,1): warning C4838: conversion from 'unsigned int' to 'const int32' requires a narrowing conversion

Compilaton error on sse.cpp

**Comment by hzqst** [comment]
Try disable [Treat Linker Warnings as Errors](https://docs.microsoft.com/en-us/cpp/build/reference/wx-treat-linker-warnings-as-errors?view=msvc-160)
