### ISSUE TITLE
Counter-strike 1.6 critical errors

### ISSUE THREAD

**Issue by oemix12** [hzqst/MetaHookSv#490]
I use Google Translate

1) The video shows that the map textures are "compressed". This does not depend on the map, but on the server. If the map changes, then either the game crashes when loading, or the textures still shrink. (62.122.215.44:27015)
2) On some servers, the game crashes when connecting to it. (37.230.228.96:27015, 46.174.49.13:27015)
I checked on the release version and on the Prerelease

https://github.com/user-attachments/assets/11fd3bfe-0729-45ef-bf27-a674db2a4b12

On most servers, everything works fine.

My laptop specs:
Processor AMD Ryzen 7 4800H with Radeon Graphics 2.90 GHz
RAM 8.00 GB (available: 7.42 GB)
Nvidia GeForce GTX 1650

By the way, metahooksv is awesome +150% to fps, thanks

**Comment by hzqst** [comment]
1. Do you mean there is an issue with **detail texture** (or compressed from what you called)?
2. What's the engine version/buildnum? like 3248 3266 4554 6153 8684 or 9920 ?
3. What's the map? any download link?
4. Can you try [this](https://github.com/hzqst/MetaHookSv/releases/tag/v20240916a)?

**Comment by hzqst** [comment]
Can you try `gl_dump` on console and see which GPU the game is using?

**Comment by hzqst** [comment]
I have no idea what's going on with your issue since I'm not able to connect to that server (62.122.215.44:27015), no network response at all.

**Comment by oemix12** [comment]
https://tsarvar.com/en/@EpicFunKnife This is real time monitoring.

**Comment by hzqst** [comment]
It seems that they (I mean the one who hosts 62.122.215.44:27015) added a brush model into this map with external BSP file `/models/next21_efk/sphere256.bsp`

![image](https://github.com/user-attachments/assets/8d1b3d51-c2bf-4b5e-ba1d-7ef819ecaa13)

![image](https://github.com/user-attachments/assets/d098cfbc-c056-4818-b74b-e5e92c1ad013)

which is not well supported by Renderer.dll for now.

I am considering how to deal with this edge case.

**Comment by hzqst** [comment]
![ba50d373f960097c68faed416a3130b7](https://github.com/user-attachments/assets/78ec8282-f373-4dc1-9756-063e01c62538)

![image](https://github.com/user-attachments/assets/9781b957-c0a6-4b13-93f9-b33be2720b5f)

Should've been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20241010a

**Comment by oemix12** [comment]
everything works fine, you're cool
