### ISSUE TITLE
[Renderer]使用紫黑格子纹理渲染缺失贴图

### ISSUE THREAD

**Issue by DrAbcOfficial** [hzqst/MetaHookSv#496]
![67AFC135B9E42A30064DDB83D3792807](https://github.com/user-attachments/assets/fbdbb14b-a038-43d9-9cc8-224ebe4b1d2b)
![BF0B07599A38BAA6348AB63F03988B61](https://github.com/user-attachments/assets/26aa3204-859d-4c22-a637-05bba337a7af)
目前缺失的纹理会直接跳过渲染，而不是使用紫黑格子纹理进行替代

**Comment by hzqst** [comment]
![Uploading image.png…]()
Fixed in latest commit.
