### ISSUE TITLE
MH_LoadEngine: Failed to locate VideoMode_SearchBase

### ISSUE THREAD

**Issue by Chris2918** [hzqst/MetaHookSv#499]
Used the one-click installer for Sven Coop and launched from the shortcut, but get this error:
![image](https://github.com/user-attachments/assets/78e43eb0-37a9-42cb-9837-71b76f22be71)

**Comment by Chris2918** [comment]
Using the latest build

**Comment by tamagama** [comment]
using the july 29 release fixed it for me.
haven't tested it but later releases probably only work on 5.26 version builds, but im probably wrong.

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20241007a

**Comment by Chris2918** [comment]
Thank you, the fix works
