### ISSUE TITLE
Wide characters in scoreboard have huge font size

### ISSUE THREAD

**Issue by incognico** [hzqst/MetaHookSv#5]
Wide characters in the scoreboard (example: öäüßõ) have a huge font size (but the characters actually show correct!).
![20210325214926_1](https://user-images.githubusercontent.com/2098066/112551762-cd72f600-8dc1-11eb-81d0-5dd46394dbe5.jpg)
I actually like that bigger font, maybe just have it for all nicknames, even those without wide/special characters. It is just a minor annoyance that there are two different fonts and sizes.

**Comment by hzqst** [comment]
The font could be customized in "\steamapps\common\Sven Co-op\svencoop\captionmod\CaptionScheme.res"
SmallScoreboardFont is for scoreboard playernames, LargeScoreboardFont is for scoreboard server name.
