### ISSUE TITLE
Improvements for Texture filtering

### ISSUE THREAD

**Issue by BlackShadow** [hzqst/MetaHookSv#50]
I have few improvement recommendations (bug fix actually) for Texture filtering.

1: When texture filtering is disabled, it doesn't effect skybox.
2: When you disable texture filtering, it doesn't disable it for chrome textures until game restarted.

**Comment by hzqst** [comment]
What is chrome textures?

**Comment by BlackShadow** [comment]
Chrome is a (kind of) reflective texture faced to player.

i.e. Viewmodel hand's textures are chrome

![image](https://user-images.githubusercontent.com/30868395/128603989-f3d78908-d86f-41f8-a066-5f4e8a5044fa.png)

**Comment by hzqst** [comment]
Should be okay to change filter mode for studiomodel textures in the latest commit cf548f06b3e2d60bad9e5a16ca1c7b2847891aa1.

btw if you are trying to add pixel art in game you should use post-process shader instead of GL_NEAREST

**Comment by BlackShadow** [comment]
yes i was using GL_texzture gl_nearest but it doesn't get reset without restarting game

**Comment by BlackShadow** [comment]
Working nice. Closing...
