### ISSUE TITLE
[Feature] Software mode water

### ISSUE THREAD

**Issue by BlackShadow** [hzqst/MetaHookSv#51]
Software mode ripple effect would be really nice addition. It can be added as r_water 3.

**Comment by hzqst** [comment]
Added in c3a2ecedbcce9c2b5717ed01678bde5cad3e6408

**Comment by Zaphero1** [comment]
Oh dang, how do you turn this on? I love the look of the software water, but I can't find a console command or config file where you can swap to "WATER_LEVEL_LEGACY_RIPPLE". Ingame it seems I can only toggle between two different modes, one similar to OpenGL water and one similar to Source Water.

**Comment by hzqst** [comment]
> Oh dang, how do you turn this on? I love the look of the software water, but I can't find a console command or config file where you can swap to "WATER_LEVEL_LEGACY_RIPPLE". Ingame it seems I can only toggle between two different modes, one similar to OpenGL water and one similar to Source Water.

Check https://github.com/hzqst/MetaHookSv/blob/main/Renderer.md#env_water_control and https://github.com/hzqst/MetaHookSv/blob/main/Build/svencoop/renderer/default_entity.txt

**Comment by hzqst** [comment]
> Yeah I've been trying to set the level to "WATER_LEVEL_LEGACY_RIPPLE" in default_entity, but it just looks like the same as "WATER_LEVEL_LEGACY," there's no ripple effect.
> 
> ![image](https://user-images.githubusercontent.com/19298996/213283113-753c945e-f981-4d65-8696-ef2d799e7e70.png) [Example Video 1](https://user-images.githubusercontent.com/19298996/213283616-15baa133-c9be-4a3e-81f3-60f5d8a87903.mp4)
> 
> The only other setting in the documentation that mentions it is speedrate and that it should be set between 500 and 1000 for ripple, but that just makes the water turbulance so that it looks broken. ![image](https://user-images.githubusercontent.com/19298996/213284732-e9e02c1d-4727-465c-a00f-fb7451917624.png) [Example Video 2](https://user-images.githubusercontent.com/19298996/213285023-22a6d018-2f27-4513-a397-57a3b1e193c0.mp4)

then where is your `"level" 'WATER_LEVEL_LEGACY_RIPPLE"` in the next screenshot?

**Comment by Zaphero1** [comment]
> then where is your `"level" 'WATER_LEVEL_LEGACY_RIPPLE"` in the next screenshot?
![image](https://user-images.githubusercontent.com/19298996/213335806-087cd7ba-2244-434c-8690-1d3efd8f4511.png)
Ah accidentally cropped it.

**Comment by Zaphero1** [comment]
Ah wait, would you like for me to make a new issue for this?
