### ISSUE TITLE
Fatal error when launching MetaHook for HalfLife

### ISSUE THREAD

**Issue by FinaFina233** [hzqst/MetaHookSv#514]
VGUl2Extension.dll is required!

**Comment by hzqst** [comment]
You have to add `VGUl2Extension.dll` in `Half-Life\<mod_directory>\metahook\configs\plugins.lst`

![image](https://github.com/user-attachments/assets/ceb7dd0f-aca7-4f84-8f92-1825af89d514)

**Comment by FinaFina233** [comment]
> You have to add `VGUl2Extension.dll` in `Half-Life\<mod_directory>\metahook\configs\plugins.lst`
> 
> ![image](https://private-user-images.githubusercontent.com/12287588/391319260-ceb7dd0f-aca7-4f84-8f92-1825af89d514.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNDY2NjAsIm5iZiI6MTczMzA0NjM2MCwicGF0aCI6Ii8xMjI4NzU4OC8zOTEzMTkyNjAtY2ViN2RkMGYtYWNhNy00Zjg0LThmOTItMTgyNWFmODlkNTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDA5NDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMGE0NTE1NTZjMDJmMTliOTQ3ZDExY2U4OGNmZjVmZmE2NzQ5NGJiYjFmOTBhM2Y2ZjgyMDI4NDlmNTZkZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MNcJQyrB_3HStpJXKhtohXk4y3PBTtOisZj6KLQxvMc)

thanks, I actually did that but mistakenly typed 'I' as 'l'
