### ISSUE TITLE
ragdolls turn into static poses after a few seconds in czero

### ISSUE THREAD

**Issue by Strider223** [hzqst/MetaHookSv#515]
![image_2024-12-07_141103198](https://github.com/user-attachments/assets/f79477fe-2118-453a-9d86-f8a2bc118f92)
something similiar like this was already reported but for some reason they always turn to their default poses after a few seconds

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20241208a

**Comment by Strider223** [comment]
thanks!
