### ISSUE TITLE
SCModelDownloader causes UtilHTTPClient error

### ISSUE THREAD

**Issue by LingKuja** [hzqst/MetaHookSv#517]
Hello. Since version v20241130c, svencoop closes with the following error:

![image](https://github.com/user-attachments/assets/c8bd47b3-4a5d-4d53-82db-68098dd2485b)

I have tried everything, but the issue persists.

EDIT: Please my other comment [here](https://github.com/hzqst/MetaHookSv/issues/517#issuecomment-2526310550), the issue was the SCModelDownloader plugin.

**Comment by hzqst** [comment]
try reinstall [latest build](https://github.com/hzqst/MetaHookSv/releases/tag/v20241207a) from `scripts\install-to-SvenCoop.bat`

**Comment by LingKuja** [comment]
Ok, did as instructed, and I got the same error again. Is there a log I can to upload to help debug?

**Comment by hzqst** [comment]
The error message `Could not get UtilHTTPClient from UtilHTTPClient_SteamAPI.dll` only occurs when you have an out-of-date `UtilHTTPClient_SteamAPI.dll` somewhere in your game directory.

**Comment by LingKuja** [comment]
Followed your suggestion, I deleted the outdated `UtilHTTPClient_SteamAPI.dll` from both the `svencoop\metahook\dlls` folder and from the root Sven Coop folder. Having already replaced the file on the DLLS folder, I also placed the more updated one on the root folder, it works now. Thank you for your support.
