### ISSUE TITLE
[Renderer] Unable to launch Counter-Strike on build v20241209a

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#519]
Engine version 8684.
Error: Could not find GL_UnloadTexture
![image](https://github.com/user-attachments/assets/08133020-bece-434f-bea0-5642629715f8)

**Comment by MysticDeathProject** [comment]
Yes I also have this error
![image](https://github.com/user-attachments/assets/0efe8609-2241-4a93-8a3d-887c1b452944)

**Comment by di57inct** [comment]
Downgrading renderer plugin to [v20241014b](https://github.com/hzqst/MetaHookSv/releases/tag/v20241014b) fixes the issue.

**Comment by MysticDeathProject** [comment]
> Downgrading renderer plugin to [v20241014b](https://github.com/hzqst/MetaHookSv/releases/tag/v20241014b) fixes the issue.

Thank you

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20241210a
