### ISSUE TITLE
运行正版svencoop时出错

### ISSUE THREAD

**Issue by XMOAO** [hzqst/MetaHookSv#53]
覆盖了metahooksv之后进游戏载图出现:
![bug](https://user-images.githubusercontent.com/70386664/129433504-331605c2-2abe-4fbe-bd97-ff6c9444ec42.png)

**Comment by hzqst** [comment]
你是集显吗？还是A卡？什么型号的GPU？

**Comment by XMOAO** [comment]
AMD Radeon HD 8370D 驱动是最新的
集显

**Comment by hzqst** [comment]
先尝试设置让游戏强制使用独立显卡
如果还不行的话，尝试替换着色器文件：`steamapps\Sven Co-op\svencoop\renderer\shader\`[dfinal_shader.fsh](https://github.com/hzqst/MetaHookSv/files/6985873/dfinal_shader.zip)

**Comment by XMOAO** [comment]
替换了着色器之后可以了!谢谢大佬
