### ISSUE TITLE
[CaptionMod ]In-game options

### ISSUE THREAD

**Issue by qabRieL99** [hzqst/MetaHookSv#54]
It'd be nice to be able to change certain settings via the in-game options menu. For CaptionMod, a similar method was used in previous versions.

**Comment by hzqst** [comment]
An advanced dialog has been added in Audio to adjust property of subtitle panel at runtime.

![image](https://user-images.githubusercontent.com/12287588/140072264-4c77cadd-0077-4251-be0c-258aef8b1d0c.png)
