### ISSUE TITLE
Shader crashes the game after last update

### ISSUE THREAD

**Issue by BlackShadow** [hzqst/MetaHookSv#55]
![image](https://user-images.githubusercontent.com/30868395/130048487-be2879b5-920f-41cd-8f4a-5df55fd2cc58.png)

**Comment by hzqst** [comment]
revert to 90a7646b667e2f3bc5f9ac8e89b9944ac988059e solve the issue.

**Comment by BlackShadow** [comment]
![image](https://user-images.githubusercontent.com/30868395/130054174-956491a7-51d1-4dc0-adcc-90a190cc9fbb.png)

Lightning broken

**Comment by hzqst** [comment]
Latest update comes with bindless texture support (require OpenGL 4.6), the decals are now temporary unavailable.
