### ISSUE TITLE
Missing OpenGL extension GL_NV_float_buffer

### ISSUE THREAD

**Issue by quank123wip** [hzqst/MetaHookSv#56]
Using latest version and official release on steam.

**Comment by hzqst** [comment]
what's your graphic card? AMD or intel?

**Comment by quank123wip** [comment]
> what's your graphic card? AMD or intel?

Intel and Nvidia Laptop.

**Comment by hzqst** [comment]
Latest commit a87a6e5ff2d556598e5d2bee9ed0ae237a9550d5 should solve the issue.
