### ISSUE TITLE
[CaptionMod] “prefix” on SubtitlePanel.res is ignored — it’s always set to 1.

### ISSUE THREAD

**Issue by HinataNatsumi** [hzqst/MetaHookSv#58]
“prefix” setting on SubtitlePanel.res is ignored. Prefix is always shown in the dialog even if it’s set to 0.

Game: all. Engine played on: GoldSrc_new (8684), yet to reproduce on SvEngine.

Copy: https://drive.google.com/file/d/1qErLFqXOCLfyxJ06ZuR9f6ZBOAMtZzAs/view?usp=sharing

**Comment by hzqst** [comment]
Should be fixed with latest commit

**Comment by HinataNatsumi** [comment]
Confirm fixed.
