### ISSUE TITLE
贴图分辨率错误?

### ISSUE THREAD

**Issue by duke325** [hzqst/MetaHookSv#59]
![20210901000938_1](https://user-images.githubusercontent.com/29809784/131538296-c06d379c-7b6d-46c5-b99c-30305d0a3b5c.jpg)
![20210901000943_1](https://user-images.githubusercontent.com/29809784/131538307-001cb624-9339-4991-9a7e-3354cb4c2a4b.jpg)
![20210901000947_1](https://user-images.githubusercontent.com/29809784/131538315-c7879fd3-b98a-4ddc-b58e-8c6708e00c2c.jpg)
![20210901000952_1](https://user-images.githubusercontent.com/29809784/131538319-bbe38dba-1d1a-47b3-8bdb-a162f244c0c1.jpg)
![20210901000833_1](https://user-images.githubusercontent.com/29809784/131538322-5c01e2aa-209b-44c3-b279-3bca26f0740b.jpg)
原本是正常的 装了metahook后贴图出现了问题uwu

**Comment by hzqst** [comment]
尝试更新最新版本，如果不行试试启动参数增加-nobindless

**Comment by duke325** [comment]
更新完修复了 感谢uwu
