### ISSUE TITLE
r_wsurf_vbo breaks certain frames of textures.

### ISSUE THREAD

**Issue by mariotime1287** [hzqst/MetaHookSv#7]
In the MertaHookSv version of the renderer plugin, when r_wsurf_vbo is set to 0, almost all waterfall textures are frozen. Additionally, when r_wsurf_vbo is set to 1, almost all textures with an on/off variant will stay stuck in one of the two variants. For example, HEV chargers will show up as full even when empty, and almost all buttons will stay either on/off. While this is not game breaking, it's incredibly annoying. 

Edit: I'm aware that the issue is (somewhat) talked about on the description of the wsurf_vbo option, the fact that the waterfalls aren't animated properly at all with the option off is certainly a bug, and the fact that the renderer is so unoptimized without it makes the mod almost unplayable unless you're willing to sacrifice the animations of buttons. 

Also, good work on these amazing mods regardless. I just wish more people knew about them, because they deserve much more attention.

**Comment by hzqst** [comment]
Animated textures are known to be broken due to batch-draw optimization. I will add animated texture support later for shaders however some performance may be sacrificed.

**Comment by hzqst** [comment]
Should be fixed with latest commit.

https://user-images.githubusercontent.com/12287588/122534789-734a9f80-d055-11eb-96a2-cd8510a60a6f.mp4
