### ISSUE TITLE
Water Shader Artifacts

### ISSUE THREAD

**Issue by TyrannoWright** [hzqst/MetaHookSv#72]
Only getting this visual effect on the latest build here on GitHub. Older builds on GameBanana and ModDB don't seem to have this problem. Color artifacts get worse as FXAA and HDR are enabled. Map used to display this is hl_c09.

![Screenshot 2021-09-11 233840](https://user-images.githubusercontent.com/10506744/132976633-932bc446-8dc8-47d5-9caf-84aac8f9c508.png)

**Comment by hzqst** [comment]
Could you have a try with latest commit? if still doesnt work, please check if the debug draw (enable with r_water_debug 1 or r_water_debug 2 ) on the left top looks incorrect or not?

**Comment by TyrannoWright** [comment]
Still persists with the newest commits, though new artifacts show with reflections.

r_water_debug 1
![r_water_debug 1](https://user-images.githubusercontent.com/10506744/133011332-01425fb6-b995-4119-a4af-c9ffb5133147.png)

r_water_debug 2
![r_water_debug 2](https://user-images.githubusercontent.com/10506744/133011359-31f9b432-9581-4c89-9814-0ab216f4bb2f.png)

**Comment by hzqst** [comment]
What is your graphic device, NVIDIA or AMD or Intel?

**Comment by TyrannoWright** [comment]
AMD RX 480 4GB

**Comment by hzqst** [comment]
I am not able to repro the artifacts with Nvidia GTX 970 and AMD 6800XT but some other guys with older AMD card told me the same issue. I will buy a 2nd-hand RX 400 series card days later, if possible.

Thanks anyway for reporting the bug.

**Comment by hzqst** [comment]
Able to repro in Radeon T 540X, and hould be resolved in dfeca56136a2be38a342b81b2c51c666095b9a1b. Could you please have a try?

**Comment by TyrannoWright** [comment]
All fixed up. Great work
![Screenshot 2021-10-01 102350](https://user-images.githubusercontent.com/10506744/135662004-1eb9c407-7828-404a-97c7-3312a195164e.png)
.
