### ISSUE TITLE
Incorrect color blend with sprites

### ISSUE THREAD

**Issue by hzqst** [hzqst/MetaHookSv#73]
![{S8Z14R2}ZC0QJ8NOV34L_J](https://user-images.githubusercontent.com/12287588/132978007-9b0dcd3e-0495-41c5-a651-3379982da1cd.png)

![1S(7)~~KQ T X~8)~_KTXLJ](https://user-images.githubusercontent.com/12287588/132978004-0b6f52cc-0b88-443e-95b5-a110378cf39a.png)

**Comment by di57inct** [comment]
Notice the blood color. I should be way more saturated. Related?
![de_dust2x20004](https://user-images.githubusercontent.com/3608544/189657711-2ccc7e45-9565-42ad-934d-9558559a3e8a.jpg)
