### ISSUE TITLE
metarender replace texture incorrect scale

### ISSUE THREAD

**Issue by gigirs50** [hzqst/MetaHookSv#81]
old metarender correct scale
![old metarender](https://user-images.githubusercontent.com/7074540/133933873-347e929a-155c-44a4-a999-843e2452e314.jpg)

new metarender incorrect scale
![new metarender](https://user-images.githubusercontent.com/7074540/133933886-5cd5e53f-f105-4855-a7ff-3d77721b63c4.jpg)
i use this script
![2021-09-19_17-39-18](https://user-images.githubusercontent.com/7074540/133933896-ecf81d1b-2367-4d2c-8a25-c66e633addb0.png)

**Comment by hzqst** [comment]
What is the texture size of ringlastra.bmp and ringwall.dds ?

**Comment by gigirs50** [comment]
ringlastra.bmp 256x256 
ringwall.dds 1024x1024

**Comment by gigirs50** [comment]
[model e texture.zip](https://github.com/hzqst/MetaHookSv/files/7192427/model.e.texture.zip)
model and texture with the script thanks

**Comment by gigirs50** [comment]
it only works if the new texture is the same size as the original

**Comment by hzqst** [comment]
Keyvalue `"replacescale" "[width_scale] [height_scale]"` was added in commit bf9ece5224fabee244696aa28ae10c2013b80699
.e.g if you would like `ringwall.dds` to be scaled from 1024x1024 down to 256x256 or the same size as `ringlastra.bmp` :
```
{
    "classname" "studio_texture"
    "basetexture" "ringlastra.bmp"
    "replacetexture"  "resource/tga/ringwall.dds" 
    "replacescale" "0"
}
```
or
```
{
    "classname" "studio_texture"
    "basetexture" "ringlastra.bmp"
    "replacetexture"  "resource/tga/ringwall.dds" 
    "replacescale" "0 0"
}
```
or
```
{
    "classname" "studio_texture"
    "basetexture" "ringlastra.bmp"
    "replacetexture"  "resource/tga/ringwall.dds" 
    "replacescale" "0.25"
}
```
```
{
    "classname" "studio_texture"
    "basetexture" "ringlastra.bmp"
    "replacetexture"  "resource/tga/ringwall.dds" 
    "replacescale" "0.25 0.25"
}
```
Any one of them are okay to do the job.

**Comment by gigirs50** [comment]
> Keyvalue `"replacescale" "[width_scale] [height_scale]"` was added in commit [bf9ece5](https://github.com/hzqst/MetaHookSv/commit/bf9ece5224fabee244696aa28ae10c2013b80699)
> .e.g if you would like `ringwall.dds` to be scaled from 1024x1024 down to 256x256 or the same size as `ringlastra.bmp` :
> 
> ```
> {
>     "classname" "studio_texture"
>     "basetexture" "ringlastra.bmp"
>     "replacetexture"  "resource/tga/ringwall.dds" 
>     "replacescale" "0"
> }
> ```
> 
> or
> 
> ```
> {
>     "classname" "studio_texture"
>     "basetexture" "ringlastra.bmp"
>     "replacetexture"  "resource/tga/ringwall.dds" 
>     "replacescale" "0 0"
> }
> ```
> 
> or
> 
> ```
> {
>     "classname" "studio_texture"
>     "basetexture" "ringlastra.bmp"
>     "replacetexture"  "resource/tga/ringwall.dds" 
>     "replacescale" "0.25"
> }
> ```
> 
> ```
> {
>     "classname" "studio_texture"
>     "basetexture" "ringlastra.bmp"
>     "replacetexture"  "resource/tga/ringwall.dds" 
>     "replacescale" "0.25 0.25"
> }
> ```
> 
> Any one of them are okay to do the job.

super!! what about normal map textures they still work on this new metarender?

**Comment by hzqst** [comment]
normalmap currently only works with brush surfaces, which should be configured in `[mapname]_detail.txt` 

read [doc](https://github.com/hzqst/MetaHookSv/blob/main/Renderer.md#normal-textures) for usage.
