### ISSUE TITLE
CaptionMod Subtitle Scale

### ISSUE THREAD

**Issue by mariotime1287** [hzqst/MetaHookSv#90]
It'd be nice to have a console command to be able to scale the textbox smaller and larger.

**Comment by hzqst** [comment]
An advanced dialog has been added in **Audio** to adjust property of subtitle panel at runtime.

![image](https://user-images.githubusercontent.com/12287588/140072264-4c77cadd-0077-4251-be0c-258aef8b1d0c.png)
