### ISSUE TITLE
% in chat

### ISSUE THREAD

**Issue by incognico** [hzqst/MetaHookSv#99]
There is a difference in `SayTextAll` and `ClientPrintAll` regarding the percent sign `%`

Working fine in vanilla & metahooksv:
`g_PlayerFuncs.SayTextAll(plr, "" + percent_int + "% of the server).\n");`

`ClientPrintAll` however needs `%%` to make a `%` appear in the vanilla client, like so:
`g_PlayerFuncs.ClientPrintAll(HUD_PRINTTALK, "" + percent_int + "%% of the server).\n");`

MetaHookSv is displaying `%%` while the vanilla client shows `%`.

**Comment by hzqst** [comment]
fixed in 56552da7616b5ab47444b967387d33f4ad522227
